### PR TITLE
JS bugfixes (save button + goto publishing status)

### PR DESCRIPTION
**Pull request by rarila**
- Fix save button does not change state back enabled after save
- Fix not changing to meta tab when sidebar publishing stated is clicked

### CODE REVIEW

**Comment by bobdenotter** [comment]
Awesome!! I noticed that first second one today, and was thinking i had to dive in, to see it it was just on my end. I will do this tomorrow morning, because then I can do a cherry-pick for release/2.1 with a clear head! :+1:

**Comment by rarila** [comment]
One thing left: the button stays in focus state. Ideas welcome.

**Comment by bobdenotter** [comment]
`$(this).blur();` ?

**Comment by rarila** [comment]
Hmm…

**Comment by rarila** [comment]
Question is, if displaying a rotating wheel wouldn't be better anyway

**Pull request merged**
