### PR TITLE
Portuguese language split

### PR DESCRIPTION
**Pull request by horus68**
Actual "pt" language renamed to pt_BR (Brazil)

Added: new language files for pt_PT (Portugal)

### CODE REVIEW

**Comment by rarila** [comment]
Ah, great! Thanks!

But I’m afraid that we get merge problems after a possible merge of #5031
So I suggest to wait as I believe it’s much easier to redo this one as solving the merge conflict of the other then. What do you think?

**Comment by horus68** [comment]
No problem to me... I also have those regenerated files if you need!
On Crowdin you can download both!

**Comment by horus68** [comment]
A new language that can be uploaded now:
[RFC] Language folders should be named as xx_XX · Issue #5038 · bolt/bolt - https://github.com/bolt/bolt/issues/5038

**Comment by GawainLynch** [comment]
Could you please resubmit with the adjusted strings from #5031?

**Pull request closed without merging**
