### PR TITLE
[2.2] Retrieve existing relations before setting them from POST. Fixes #4044

### LINKED ISSUE #4044: No related entries on preview
Hello,

I have contenttype `A` and contenttype `B`.

On `A` I can select one of `B`. On the template for `B` I can fetch `A` with related().. But When I preview `B` the relation to `A` is `false`.

Looks like a bug to me.

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #4044

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hold off on merging this one.. Needs tweaking.

**Comment by bobdenotter** [comment]
Should be GTG now. :beer:

**Comment by bobdenotter** [comment]
Works on PHP 5.3 now!

**Comment by GawainLynch** [comment]
:+1:

**Pull request merged**
