### PR TITLE
d/t typo

### PR DESCRIPTION
**Pull request by evertalbers**

### CODE REVIEW

**Comment by bobdenotter** [comment]
*ahem*

**Comment by GawainLynch** [comment]
Which of the Dutchies can't speel? :stuck_out_tongue:

**Comment by evertalbers** [comment]
Now you mention it Gawain, the word "sucessful" keeps popping up in the Boltforms config.yml :-)

**Comment by GawainLynch** [comment]
Hey… As I always say… "I speak 12.5 languages… 12 programming languages and a bit of English"

**Pull request merged**
