### PR TITLE
Fixes "non-interactive configuration" of composer-install by providing extra vars in composer.json

### PR DESCRIPTION
**Pull request by skript-cc**
So here goes my first pull request, please help me out if I'm doing something wrong.

I posted the issue this weekend in the bolt/composer-install repository, see https://github.com/bolt/composer-install/issues/7. I also described the solution to this problem put forward by this PR.

**Quick summary**
*Problem*: "I want to install Bolt in separate directory, but I can't do this when doing a composer install non-interactively."
*Solution*: "Do a composer install instead with a slightly modified version of the composer.json file, where an extra option named 'bolt-separate-web-dir' can be set."

This PR also modifies the default values so that by default the web root is installed as a separate directory. This way the code reflects the recommendations from [the documentation](https://docs.bolt.cm/installation-advanced), which states:

> As of version 2.0 the location of app resources is completely configurable so you only need to store public assets inside the web root directory. We would strongly recommend that you use this strategy if you have control over your hosting environment.

### CODE REVIEW

**Comment by skript-cc** [comment]
Btw, I'm sorry for the number of commits, much of them are unnecessary. They are only the result of my struggle to test my changes locally.

**Comment by GawainLynch** [comment]
> Btw, I'm sorry for the number of commits, much of them are unnecessary. They are only the result of my struggle to test my changes locally.

@skript-cc Zero stress… One thing I find really handy for these things is [`git rebase`](https://help.github.com/articles/about-git-rebase/). 

But get familiar with rebasing first in a test repo where you can afford to lose commits. Things *are* retrievable, but that is not for beginners :grin:

**Comment by skript-cc** [comment]
Yep, I know about rebasing, I only didn't know that a PR would include all of them... What's the best thing to do? Rebase my commits and resubmit this PR?

**Comment by GawainLynch** [comment]
Well, if you're game…

```
cd you-bolt-directory
git checkout release/2.2
git rebase -i 9204d653dd49e0fcf9f8a405c8031f12a922c739^
```

Then you change `pick` to `fixup` for all **except** the first (top) one in the list… Save the file, and that will combine them into one commit.

Then you just `git push --force`

**Comment by skript-cc** [comment]
Wooha, nice!

**Comment by GawainLynch** [comment]
Pretty powerful stuff, hey!

I use it all the time on branches that I am working on… "Oh damn it, I left a `dump()` in 3 commits ago", so I just rebase interactively and set that commit to `edit`, the rebase will stop there and everything is good to go. Beware of later conflict though!

**Comment by GawainLynch** [comment]
@rossriley: are you OK with this too?

**Comment by GawainLynch** [comment]
Sorry for the delay, @skript-cc… It's been a busy few weeks for all of us in Real Life Land :grin: 

Thank you! :+1:

**Pull request merged**
