### PR TITLE
[v4] Remove session deprecations

### PR DESCRIPTION
**Pull request by CarsonF**

### CODE REVIEW

**Comment by GawainLynch** [comment]
* Remove `tests/phpunit/unit/Session/Handler/Factory/MemcacheFactoryTest.php`
* Update MemcachedFactoryTest class `@requires extension memcached 3.0.0`
* Redis tests … well

**Comment by GawainLynch** [comment]
@CarsonF if you're curious about the `'save_path' => 'PERSISTENT=foo host1:11212:2'` change …

Using `PERSISTENT=` in `save_path` was removed during the [PECL library's 3.0-dev](https://github.com/php-memcached-dev/php-memcached/commit/dc5b22a8dace7373c1ef9d2946e89a660ed35b20#diff-25c5e7d3aa23f27466a7f0bbc2c251ecL105)

… Sunday, and C code, what better way to relax :smile:

**Comment by CarsonF** [comment]
Yes, was happy to remove it from src just missed the tests. Thanks!

Mind if I squash it down?

**Comment by GawainLynch** [comment]
Squash away mate, don't need the numbers, need clean commits.

**Comment by CarsonF** [comment]
Ok I'm good with it now.

**Pull request merged**
