### PR TITLE
Portuguese Brazil language

### PR DESCRIPTION
**Pull request by horus68**
Portuguese language for pt_BR (Brazil)
Include: Some untranslated keyword based messages that where ignored by #5031 regenerated files because on v2 translation there was a wrong # in front of the translated value

Just for the records example of the "losted" strings from v2, and now fixed
`"contenttypes.entries.text.new": # "Novo Post"`

### CODE REVIEW

**Comment by GawainLynch** [comment]
ping @rarila

**Comment by rarila** [comment]
That's not wrong ``#``, that's a hint in a comment generated from generic messages.

**Comment by horus68** [comment]
but can this be merged?

**Comment by rarila** [comment]
They are automatically created so it is likely that there are grammatically errors in there. So they should be checked before mergin.

**Comment by horus68** [comment]
Before submit I had fixed masculine/feminine concordance errors as plural/singular.
I think its ok to merge!

Also please merge related #5064

**Comment by bobdenotter** [comment]
@horus68 Looks good to me! Thank you for your contibution! :+1:

**Pull request merged**
