### PR TITLE
Stop chrome from doing autocomplete on new passwords.

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes: #4898 

This is Chrome:

### CODE REVIEW

**Comment by geggleto** [comment]
HA

**Comment by bobdenotter** [comment]
Hold off on merge, plz.. Now it's broken in Firefox. :-/

**Comment by GawainLynch** [comment]
> Hold off on merge, plz.. Now it's broken in Firefox. :-/

Pfft… Who uses Firefox anyway :stuck_out_tongue_winking_eye:

**Comment by geggleto** [comment]
@GawainLynch ++

**Comment by bobdenotter** [comment]
Ok, working correctly on Chrome, Firefox _and_ MS Edge, now!

**Pull request merged**
