### PR TITLE
Change: changing 'Extends' menu to 'Extensions'.

### LINKED ISSUE #6143: [RFC] Rename 'extend' to Extensions
Hi!
The things you put in Bolt are called _extensions_, the website where you find the things is called _https://extensions.bolt.cm/_ ... 

So please call the menu item "**Extensions**" 
(It is now 'extend', maybe logical for native speakers, but not clear at all)

Extra request:
Could we move the name extensions up one level?
so rename Extra's -> Extensions?

screen shot 2016-12-08 at 11 49 03

I am not sure what is all under 'extras', but if it is only extension stuff, why hide it under a shady / unclear name? (Extra? Extra what? Extra sauce? Fries? Mmmmm Fries...)

Details
-------

 - Relevant Bolt Version: [ 3.2 ]

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #6143.

While working on this I stumbled upon an issue with backend pages added by extensions, so we should hold this one until #6151 is fixed.

### CODE REVIEW

**Comment by bobdenotter** [comment]
screen shot 2016-12-11 at 19 55 55

**Comment by GawainLynch** [comment]
So this is for master?

**Comment by bobdenotter** [comment]
I intended it for 3.3. Is that an issue?

**Comment by GawainLynch** [comment]
Wait, no … I'm confused. 

Why is a translation change (that I thought we'd deliberately agreed _not_ to use "Extensions" for (.e.g. there are themes & libraries there too), not specifically objecting, just missing context on the direction change.

Other point is that this will affect all current extensions adding menus, so isn't that kind of a 4.x thing?

**Comment by GawainLynch** [comment]
Oh wow that took more brain power than I had to read up on … both 6143 and the code behind this PR :laughing: 

Thanks mate! :+1:

**Comment by GawainLynch** [comment]
Oh, and this is 100% unrelated to #6151 as there is a PR in to address that :koala: escapee.

**Pull request merged**
