### PR TITLE
[Travis] Composer install testing

### PR DESCRIPTION
**Pull request by GawainLynch**
This move the Travis Composer install test set-up to use a "real" Composer project, that includes updated vendor directories and theme.

### CODE REVIEW

**Comment by GawainLynch** [comment]
YES! The only damn number I wanted and scored it…

**Comment by bobdenotter** [comment]
> YES! The only damn number I wanted and scored it…\

So, you having #1000, #4000 and #5000 was sheer coincidence? ;-)

**Comment by GawainLynch** [comment]
Yes, that's what I am trying to say… 

I was thinking about this while having a lay in bed earlier, but I probably PR more than anyone in the history of *this* project, so statistically I am just as likely to get a thousand as any other number when compared to other people.

So, yes, all of them were :smile:

**Comment by SahAssar** [comment]
Teach the controversy! @GawainLynch uses his connections to score special PR numbers while leaving nothing but the crumbs to rest of us! We are the 99% percent!

unnamed

**Pull request merged**
