### PR TITLE
K.i.s.s. the slug!

### PR DESCRIPTION
**Pull request by rarila**
- Streamlined interface
  - No drop down anymore
  - Direct slug editing
  - Less styles
  - Less javascript
  - Double click removed
- Display of linked fields
- Use widget internal (un-)binding

(See #4470 for discussion. For now I have left the :lock: symbol in)

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm still not sure why this needs work.. I mean, I like this things that are "less", but now the icon says "locked" and you can edit it. I really don't like that part. Slugs should _not_ be editable. especially not on existing records, but we can't get away with disabling it altogether. Right now it's _way_ too easy though. 

Displaying what it's linked to doesn't really make sense to me. If it's up to we we just leave that out.

**Comment by rarila** [comment]
But that is exactly the annoying thing what @GawainLynch and I were talking about. Also in its present incarnation it means:

- :unlock:
  - The slug is autogenerated from linked fields.
  - Calling ``edit`` on it, changes the state to :lock:.

- :lock:
  - The slug *is* editable

**Comment by bobdenotter** [comment]
Ok IMHO, the slug should _never_ be editable.

**Comment by GawainLynch** [comment]
> Ok IMHO, the slug should never be editable.

I humbly disagree… If for example you "duplicate" a record, you're left with `old-slug-1`… and editors do weird stuff all the time… mine drive me mental.

**Comment by bobdenotter** [comment]
That's why i said "but we can't get away with disabling it altogether." I know we'll have to provide _some_ method to modify them, but we should make it absolutely harder than having an "open" form field to change it on a whim. 

What we had before was good: Either a button, or a double-click to trigger the prompt.

**Comment by GawainLynch** [comment]
Yeah, and this is my problem… it is too easy to change and even still with this, while better, it is still confusing…

* An unlocked symbol means I can't change it and hitting the backspace key takes me off page
* A locked symbol means I can edit it…

I am not trying to put forward opinions on UI/UX (Gawain's Third Rule), but as an end user this is *still* confusing… it is confusing in 2.2, it is confusing in master as well.

**Comment by bobdenotter** [comment]
How about we change it to a single tri-state button: 

 - Locked (won't change, can't be edited, default position after opening an existing record)
 - Auto (changes according to the `uses: ` value. default postion on _new_ records)
 - Edit (can be edited, by people who've [never read the classics](http://www.w3.org/Provider/Style/URI).)

**Comment by GawainLynch** [comment]
@bobdenotter I think that reply has made my morning… and nearly awoken the house with the laughing it inspired… "…by people who've never read the classics." :+1: 

The end-user in me would be most pleased with that approach.

**Comment by rarila** [comment]
@bobdenotter I think you hit the point! We were trying to press a three state problem into a two state solution.

This addition now fixes that and I'm quite happy with it. It makes a round an logical solution now. All annoying popups are gone, you still be warnend and editing mode is even auto ended to get at locked state as soon as possible.

**Comment by GawainLynch** [comment]
Slight flaw… "lock" and "link to" both follow "linked" field regardless.

**Comment by bobdenotter** [comment]
Glad you both like it. I think this is a good solution. Will try it later, when i'm back at a desk, and i have time to breathe .:-)

**Comment by rarila** [comment]
@GawainLynch Oh, I thought I had that one squashed out :-(

**Comment by rarila** [comment]
Ok, bug fixed, some cleanup, spinner added, no mor focus outline in readonly mode, …

**Comment by bobdenotter** [comment]
Looks good to me.. One tiny nitpick: 
screen shot 2015-11-24 at 18 06 53

Could you put "Link to:" and "Title" on the same line, plox?

**Comment by rarila** [comment]
@bobdenotter Could get a wide popup with ``uses: [title1, title2, title3]`` and other non short locales (e.g. German: "Verknüpfen mit")

**Comment by rarila** [comment]
@bobdenotter perhaps some css magic with max-width, text-overflow, … will do the trick.

**Comment by bobdenotter** [comment]
> perhaps some css magic with max-width, text-overflow, … will do the trick.

I think that would work for me. :-)

**Comment by rarila** [comment]
Done with it

**Comment by bobdenotter** [comment]
Looks good to me! :shipit:

**Pull request merged**
