### PR TITLE
Changed column type from 'string' to 'text' on templatefields

### PR DESCRIPTION
**Pull request by pedronofuentes**
Template fields allows you to configure extra fields in a template that they can be any field type supported by Bolt. They are stored serialized in a `string` column in the content type table.

It caused that if you configure a field that needs more storage space (for example a `html` field) and you add more content that is supported by the `string` column Bolt can't save.

Changing the column type to `text`solves it as it's the maximum storage type of Bolt's field types.

### CODE REVIEW

**Comment by pedronofuentes** [comment]
I saw the failed tests. I'm going to fix it.

**Comment by bobdenotter** [comment]
Cool. Thanks in advance! :-)

**Comment by GawainLynch** [comment]
Easy one for you…
```
cd /path/bot/bolt/
git checkout change-column-type-for-templatefields
cp tests/phpunit/unit/resources/db/bolt.db app/database/
./app/nut database:udpate
cp app/database/bolt.db tests/phpunit/unit/resources/db/
```

**Comment by pedronofuentes** [comment]
Oh! Thank your very much :)

I was looking for the code that generated the database and I didn't realize about the predefined database in tests.

**Comment by GawainLynch** [comment]
We're green… :traffic_light:

**Pull request merged**
