### PR TITLE
[I18N] French France translations

### PR DESCRIPTION
**Pull request by pygillier**
Hi, 

here are fr_FR translations based on latest (afaik) en files. 
This PR is linked to #3796

### CODE REVIEW

**Comment by GawainLynch** [comment]
@pygillier  We are absolutely migrating to lang_LOCALE, 
@rarila How do we procede? Do we want to just remove the current [French base](https://github.com/bolt/bolt/blob/master/app/resources/translations/fr/) translations?

**Comment by pygillier** [comment]
Good news :) 

I'm checking several tools (ala launchap, lokali.se & others) to see if translations can be automated.

**Comment by rarila** [comment]
@GawainLynch I would say so, as the current one is AFAIK pretty outdated and rather useless.

**Comment by bobdenotter** [comment]
This one is good to go, right?

**Comment by GawainLynch** [comment]
Oui! We just need to swap out the non-locale `fr` files in the process

**Pull request merged**
