### PR TITLE
Fixed: Add `'name'` to query to fetch popular tags, to prevent SQL error.

### LINKED ISSUE #5749: [BUG] Exception in populartags because of SQL query bug
Details
-------

 - Relevant Bolt Version: 3.0.3 (but the same problem is on 3.1.1)
 - Install type: tarball
 - PHP version: 7.0
 - Used web server:Nginx 1.10
- PostgresSQL 9.5

(btw. you should probably add question for SQL backend to bug template :))

Reproduction
------------
Put <sitename>/async/populartags/tags?limit=40

Result:
```
Bolt - Błąd krytyczny.
Klasa: Doctrine\DBAL\Exception\DriverException
Komunikat: An exception occurred while executing 'SELECT name, COUNT(slug) AS count FROM bolt_taxonomy WHERE taxonomytype = ? GROUP BY slug ORDER BY count DESC LIMIT 40' with params ["tags"]: SQLSTATE[42803]: Grouping error: 7 BŁĄD: kolumna "bolt_taxonomy.name" musi występować w klauzuli GROUP BY lub być użyta w funkcji agregującej LINIA 1: SELECT name, COUNT(slug) AS count FROM bolt_taxonomy WHERE t... ^
Kod: 0
Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException()
[root]//vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php, linia 116

Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
[root]//vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php, linia 836

Doctrine\DBAL\Connection->executeQuery()
[root]//vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php, linia 206

Doctrine\DBAL\Query\QueryBuilder->execute()
[root]//vendor/bolt/bolt/src/Controller/Async/General.php, linia 229

Symfony\Component\HttpKernel\HttpKernel->handleRaw()
[root]//vendor/symfony/http-kernel/HttpKernel.php, linia 62

Symfony\Component\HttpKernel\HttpKernel->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, linia 586

Silex\Application->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, linia 563

Silex\Application->run()
[root]//public/index.php, linia 14
```

Generated query and result:
```
blogitko3=> SELECT name, COUNT(slug) AS count FROM bolt_taxonomy WHERE taxonomytype = 'tags' GROUP BY slug ORDER BY count DESC LIMIT 40;
BŁĄD:  kolumna "bolt_taxonomy.name" musi występować w klauzuli GROUP BY lub być użyta w funkcji agregującej
LINE 1: SELECT name, COUNT(slug) AS count FROM bolt_taxonomy WHERE t...
```

Fix is trivial and should work on every SQL database:

```
diff --git a/vendor/bolt/bolt/src/Controller/Async/General.php b/vendor/bolt/bolt/src/Controller/Async/General.php
index 29c2c43..74f2054 100644
--- a/vendor/bolt/bolt/src/Controller/Async/General.php
+++ b/vendor/bolt/bolt/src/Controller/Async/General.php
@@ -219,7 +219,7 @@ class General extends AsyncBase
             ->select('name, COUNT(slug) AS count')
             ->from($table)
             ->where('taxonomytype = :taxonomytype')
-            ->groupBy('slug')
+            ->groupBy('name', 'slug')
             ->orderBy('count', 'DESC')
             ->setMaxResults($request->query->getInt('limit', 20))
             ->setParameters([
```

Generated query and result:
```
blogitko3=> SELECT name, COUNT(slug) AS count FROM bolt_taxonomy WHERE taxonomytype = 'tags' GROUP BY name, slug ORDER BY count DESC LIMIT 40;
       name       | count 
------------------+-------
 2015             |    79
 kryminał         |    78
 panowie          |    72
 2016             |    62
 panie            |    61
 polska           |    56
[...]
```

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #5749

### CODE REVIEW

**Comment by GawainLynch** [comment]
Shouldn't this be 
```
             ->groupBy('slug', 'name')
```

**Comment by bobdenotter** [comment]
> ->groupBy('slug', 'name')

I did some testing, and didn't notice any difference in the output (neither from adding `name`, nor the order). 
It should only matter if there are two tags with different "name", but clashing "slug". Since that shouldn't happen in the first place, I figured it wouldn't matter, but i'll happily reverse the order if you'd prefer that.

**Comment by psychonaut** [comment]
Actually leaving only 'name' should be proper solution here. Because You groupping names in this query.

**Comment by GawainLynch** [comment]
@bobdenotter: You just pushed as I was about to say "Oh yeah, @psychonaut is right!" :laughing:

**Comment by bobdenotter** [comment]
@psychonaut I think you're right.

**Comment by bobdenotter** [comment]
Haha! :-)

**Pull request merged**
