### PR TITLE
Major change: Change the 'About' link in the profiler to a slightly more useful 'Dashboard' link.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by bobdenotter** [comment]
This one, in case you were wondering: 

screen shot 2016-04-13 at 18 12 04

**Comment by bobdenotter** [comment]
That's what i get for not running the tests locally. Will fix! ^_^

**Comment by jkazimir** [comment]
This is a major, huge, risky change!

I immediately am thinking back to #1555, as a good example of just how tricky doing something like this may be!

**Comment by bobdenotter** [comment]
Test passing locally now.

**Comment by GawainLynch** [comment]
> Tests passing locally now.

I can't get over this… about is about as about as about gets… event the tests object, damnit! :stuck_out_tongue_winking_eye:

**Comment by jkazimir** [comment]
@GawainLynch What are you going on _about_?

/me hides

**Comment by GawainLynch** [comment]
I am about to get over it…

**Pull request merged**
