### PR TITLE
Nut command to perform Bolt set-up (first time, or post-update) tasks

### PR DESCRIPTION
**Pull request by GawainLynch**
This gives us a `setup:run` command, that will either run first time set-up, or updates if certain criteria are met … like existing/connecting DB, existing users.
setup-run

### CODE REVIEW

**Comment by CarsonF** [comment]
Should this be merged with the `init` command?

**Comment by GawainLynch** [comment]
> Should this be merged with the init command?

The what? :stuck_out_tongue_winking_eye: 

I'll pick this up on Slack, but I have tweaks the message, and also now the non-interactive execution (`-n`) will now behave the same as `init` if the config has Sqlite as the DB and no file exists, e.g.

setup-run-n

However, normal runs with a configured, and connectable database, will look like:

setup-run-n-normal

**Comment by bobdenotter** [comment]
Ooooh, i like those changes. I'm sure this behaviour more like what the user intends. 👍 

GTG, AFAIK. 

BBQ.

**Comment by GawainLynch** [comment]
Seeing as this is turning into an ongoing discussion, and nobody has merge time … I've added more.

* Run a requirements check via `bolt/requirements` 
image

* If it is initial set up, you will be prompted to edit some your config, settings that are basic, and we know we can change with `YamlUpdater`
setup-run-config

**Comment by bobdenotter** [comment]
@GawainLynch I haven't merged this one in yet, because you're adding more commits. Let me know when it's GTG! :-)

**Comment by GawainLynch** [comment]
Oh, it is GTG as far as I am concerned … but had some ideas while waiting for merge, so I added them in to see if they still meet with people's vision and approval of how Nut, and the `setup:run` command behave.

For the record, current additions:
  * `nut database:update` without a `-n` (or `--no-interaction`) will ask for confirmation if changes are pending (defaults to "yes")
  * `nut setup:run` with run the `nut database:update` command in the same interactivity mode
  * Addition of `bolt/requirements` (forked from Symfony Framework's internal work) to provides system & PHP, etc, "requirements" and "recommendations"
    * Runs as first step

So if you're good with that, go for it … we'll stabilise/tag `bolt/requirements` easily before Bolt 3.4 (it's tiny) … and refine later.

**Comment by bobdenotter** [comment]
I'm still happy with this, so let's merge in! :-)

**Pull request merged**
