### PR TITLE
Add "require" option to select fields

### PR DESCRIPTION
**Pull request by rarila**
On multiple wish of one individual ;-)

### CODE REVIEW

**Comment by CarsonF** [comment]
There's still the empty value. Shouldn't
```twig
{% set values = lookups|selectfield(lookupfield, option.multiple, field.keys|default('id')) %}
```
be
```twig
{% set values = lookups|selectfield(lookupfield, option.multiple or option.required, field.keys|default('id')) %}
```
?

**Comment by rarila** [comment]
[Must](https://www.w3.org/TR/html-markup/select.html#select-constraints):

>A select element with a required attribute and without a multiple attribute, and whose size is “1”, must have a child option element.

>The first child option element of a select element with a required attribute and without a multiple attribute, and whose size is “1”, must have either an empty value attribute, or must have no text content.

**Comment by CarsonF** [comment]
Hmmmm ok. As long as it's enforced though. I can't save it empty right?

**Comment by rarila** [comment]
Car

**Comment by CarsonF** [comment]
Good enough for me :+1:

**Pull request merged**
