### PR TITLE
User Role-based Hierarchy.

### PR DESCRIPTION
**Pull request by MrAdamCook**
userEdit() function modified to check which roles the currentuser can add/edit to other users.
This prevents a 'developer' role from giving himself (or others) the 'root' role.

userAction() function modified to prevent the currentuser from enabling, disabling or deleting himself.

before() function modified to prevent the currentuser from editing, deleting, disabling or enabled users with roles higher than his/her own.
This stops the user deleting the 'root' access.

### CODE REVIEW

**Comment by MrAdamCook** [comment]
This also resolves open issue #2264.

**Comment by bobdenotter** [comment]
Hi @MrAdamCook, This is neat! I'll try it out, and give feedback. 

First thing I noticed: Can you update permissions.yml.dist for this as well?

**Comment by tobias2k** [comment]
Took a quick glance; Controllers/Backend.php has a regex blooper, line
1952 - I don't think you should use regular expressions here at all, but
instead throw the current route against a list of routes to match, or,
better yet, do things properly and set some request state in a before()
handler for the relevant routes. Either way, the regex that is currently
in place (/(user)\w?/i) doesn't look right at all. The parentheses don't
do anything at all, and neither does the \w?. The regex basically
amounts to stripos($route, 'user') !== false, and it will match all
sorts of undesirable things, such as 'Lusers', 'AbuserReport', etc.

And one more thing: preventing users from changing their own roles
doesn't add any security unless you also prevent users from creating
users. The current mindset is that "useredit amounts to full access",
and preventing users from modifying themselves doesn't change that - if
you can create new users, you can use that path to modify your own
account indirectly, and users will find out pretty quickly.

On Sun, Feb 08, 2015 at 04:58:40AM -0800, Adam Cook wrote:
> userEdit() function modified to check which roles the currentuser can
> add/edit to other users.  This prevents a 'developer' role from giving
> himself (or others) the 'root' role.
> 
> userAction() function modified to prevent the currentuser from
> enabling, disabling or deleting himself.
> 
> before() function modified to prevent the currentuser from editing,
> deleting, disabling or enabled users with roles higher than his/her
> own.  This stops the user deleting the 'root' access.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/bolt/bolt/pull/2757
> 
> -- Commit Summary --
> 
>   * User Role-based Hierarchy.
> 
> -- File Changes --
> 
>     M src/Controllers/Backend.php (29)
> 
> -- Patch Links --
> 
> https://github.com/bolt/bolt/pull/2757.patch
> https://github.com/bolt/bolt/pull/2757.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/pull/2757

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by MrAdamCook** [comment]
That's fair enough - Still trying to pick up on all the possibilities with Bolt, only really picked it up yesterday for a client. So I'll improve the way it handles picking up the user pages and update.

Also I think I may have possibly confused you on the prevention of users from their own actions and editing. I've created an imgur album with some screenshots and descriptions which will hopefully make it clearer.
http://imgur.com/a/VwEMs

However, I have picked up on a new potential issue.
A user can edit his/herself, but can also remove their own / highest access role. This might not be a huge issue. But might be more ideal if their highest access role (or all of them) are locked/disabled fields. What do you think?

**Comment by bobdenotter** [comment]
> A user can edit his/herself, but can also remove their own / highest access role. This might not be a huge issue. But might be more ideal if their highest access role (or all of them) are locked/disabled fields. What do you think?

This might've been solved with these PR's: #2764 and #2765.

**Comment by MrAdamCook** [comment]
Looks like it has. I'll merge and confirm tonight.

**Comment by MrAdamCook** [comment]
Not quite.
The logged in user can still remove their own 'admin' and 'developer' roles.

**Comment by GawainLynch** [comment]
Just tested and something has caused a recent regression.

**Comment by GDmac** [comment]
Bolt currently isn't a "full-fledged" community solution out of the box (forum, comments, accounts, etc). Another cms i work with has an option to let users delete their own account. There are some precautionary measures as: when an admin deletes an account, should comments and posts be assigned to another user? Also (more important) at least one super-admin account has to stay up.

**Comment by GawainLynch** [comment]
Changes cherry-picked into master

**Pull request closed without merging**
