### PR TITLE
Fix possible bug with db options getting out of sync

### PR DESCRIPTION
**Pull request by CarsonF**

### CODE REVIEW

**Comment by GawainLynch** [comment]
LGTM...  Nitpicks though:

tweakDatabaseDefaults() over setupDatabase()
- Are these really defaults?
- Are '*tweaking*' them?
- `setDatabaseParams()`, `setDatabaseOpts()`, etc?

**Comment by bobdenotter** [comment]
Merging in, 'cause i want to get the maintenance release out. We'll discuss naming later. ^_^

**Comment by CarsonF** [comment]
@GawainLynch Where were you yesterday when we were talking about this on IRC?? I wasn't really happy with the name either. Feel free to suggest something else or change it yourself

**Comment by GawainLynch** [comment]
> Where were you yesterday when we were talking about this on IRC

Working. :grin:

> Feel free to suggest something else or change it yourself

Yeah, @bobdenotter touched on this on IRC today.

**Pull request merged**
