### PR TITLE
Add option for google maps api key

### PR DESCRIPTION
**Pull request by SahAssar**
See https://github.com/bolt/bolt/wiki/Dev-meeting-2016-06-28 for more info.

### CODE REVIEW

**Comment by GawainLynch** [comment]
LGTM

**Comment by GawainLynch** [comment]
Test failures are Codeception 2.2.2

**Comment by GawainLynch** [comment]
Can I also humbly ask for a docs PR?

**Comment by SahAssar** [comment]
Docs PR coming in tomorrow (and probably amending this PR to link to it in the config), but I'm not really sure how to fix/interpert "Test failures are Codeception 2.2.2"... Do I need to fix this or is this something upstream/unrelated?

**Comment by GawainLynch** [comment]
You need to do nothing… This is enough to get tests passing:
```
composer require codeception/codeception:2.2.1
git reset --hard HEAD
./tests/scripts/run-codeception-tests
```

**Pull request merged**
