### PR TITLE
More clean ups… and a riddle.

### PR DESCRIPTION
**Pull request by GawainLynch**
Virtual beers awarded for guessing:
1. The riddle in cset a8e0ceac921b912674ca8b9954383318101003c8 commit message
2. Who really needs 2.1 out

### CODE REVIEW

**Comment by rarila** [comment]
@rarila is drinking his virtual :beers:

**Comment by GawainLynch** [comment]
:trophy: for @rarila

**Comment by bobdenotter** [comment]
Riddle solved, merging in! :-)

**Comment by GawainLynch** [comment]
For those silently watching:
1. It was the Morse code for 'I' and 'E'
2. It was me... I want to work on 2.2

**Pull request merged**
