### PR TITLE
Disabled generator meta tag

### PR DESCRIPTION
**Pull request by WedgeSama**
Allow the generator meta tag to be disabled. Still enable by default.

### CODE REVIEW

**Comment by GawainLynch** [comment]
This comes up from time to time, and I am afraid that it is something that the project is not willing to do.

Also your master branch on your fork is somewhat out of date, that after handler has been deprecated and stubbed and the way this is being handled has completely changed which makes this unmergeable anyway.

Out of curiosity, why would you like the meta tag removed?

**Comment by WedgeSama** [comment]
Damn, i took a look at previous pull/issues before doing this pull request, miss the one talking about this topic.

I want to remove it for three reasons (one maybe better then the others) :
- When I use somethink, I like to have the possibitity to enable/disable/custom on all automatic generated code. Bolt already give a good hand for that but not enough for me (disable the generator is one of the missing stuff)
- Add a line with none essential information for users (no many bytes but save few bandwidth). I know this is not a big thing, but add to others, it can has an impact.
- Sometimes, clients do not want everyone know which technologies are use on they web site (I understand this is not a relevant reason but it is one)

Currently, I only use 2.1, I just take a quick look at the 2.2 beta and I do not seen any deprecate information on that (maybe I did not look at the good place). I hope you now know why I made this pull request ;)

**Comment by GawainLynch** [comment]
> Damn, i took a look at previous pull/issues before doing this pull request

They're around… and it comes up in IRC from visitors a bit mostly.

> * Add a line with none essential information for users (no many bytes but save few bandwidth). I know this is not a big thing, but add to others, it can has an impact.

For this I use Nginx with ngx_pagespeed (or Apache with mod_pagespeed) as that makes this a non-issue. PageSpeed generally saves hundreds if not thousands of KiB so as making those 39 bytes irrelevant in terms of saving bandwidth.

> Currently, I only use 2.1, I just take a quick look at the 2.2 beta and I do not seen any deprecate information on that (maybe I did not look at the good place). 

Yeah, we branched `release/2.2` nearly a week ago (Bolt 2.2 will be released any day soon!) and there were a number of *massive* refactor branches that landed soon after… Over 700 commits and ~30,000 lines of code changed in a 36 hour period :grin: 

`Application::afterHandler()` [now looks like this](https://github.com/bolt/bolt/blob/master/src/Application.php#L436-L441)

> I hope you now know why I made this pull request ;)

Yes, and again, we're sorry to have to reject this… We do value a broad community of contributors. :+1:

**Comment by bobdenotter** [comment]
> Sometimes, clients do not want everyone know which technologies are use on they web site (I understand this is not a relevant reason but it is one)

To expand a little on this: I recognize this feeling, but it's really not a valid argument. You can always detect the technology that's used to create a site. It's like removing the logo of your car. Everybody that knows a little bit about cars will still be able to tell what brand it is. :-)

**Comment by WedgeSama** [comment]
> For this I use Nginx with ngx_pagespeed
Add this on my to test list, thanks.

> we're sorry to have to reject this
No problem, I understand why this is rejected.

**Pull request closed without merging**
