### PR TITLE
On "Save and return to overview", save and return to overview.

### LINKED ISSUE #2735: Issue 'Save and go to overview' is still there in 2.0.6 RC2
I just installed 2.0.6 RC2 and I noticed that the issue with saving entries is still there. This prevents us from going live with our website.

When I want to save an entry and immediately go to the overview of entries, Bolt stays in the edit window. When I use this option again, Bolt brings me to the overview page. I always have to do this twice to make it work. This does happen with both buttons (right top corner and left bottom) and also in different browsers.

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #2735

### CODE REVIEW

**Comment by bobdenotter** [comment]
This breaks the current behaviour. If you have more than one page of entries, go to any page but the first, in the overview. Or filter on a taxonomy or keyword.. Then, edit that entry and click 'save and return', and you'll get returned to the overview.

**Comment by GawainLynch** [comment]
Figs are climbing the wall…

**Comment by GawainLynch** [comment]
OK… so updated version calls abort() on editContent() when `editreferrer` is set. Local testing has this returning to the specified page with query intact, e.g. pager or filter.

The added commit is required as the :koala: was too busy eating :leaves: when `release/2.2` was branched to remember that the Composer test requires us to stay on the `release/2.2` branch and not the new heavily divergent master.

**Comment by bobdenotter** [comment]
Whoop! Merging in!

**Comment by GawainLynch** [comment]
I know one user that's going to be quite happy :+1:

**Comment by gwbonline** [comment]
That's me!

**Comment by GawainLynch** [comment]
:grin:

**Pull request merged**
