### PR TITLE
Rebuilding assets, fixing tags cloud

### PR DESCRIPTION
**Pull request by marcingajda**
This PR fixes the tags cloud visible under the tags field in content editor.

Details
-------
The 3.6.9 version breaks the tags cloud visible under the tags field in content editor with the following error:

```
Uncaught TypeError: Cannot set property 'defaults' of undefined
    at Object.success (bolt.js?c1e803c986:9)
    at n (lib.js?f795c44905:1)
    at Object.fireWith [as resolveWith] (lib.js?f795c44905:1)
    at u (lib.js?f795c44905:1)
    at XMLHttpRequest.<anonymous> (lib.js?f795c44905:1)
```

As pointed out by @bobdenotter it was the problem with updating and building the assets. This PR contains the effect of the following commands:

```
yarn upgrade
yarn install
yarn run grunt build
```

### CODE REVIEW

**Comment by marcingajda** [comment]
Temporary fix:
```
cd vendor/bolt/bolt/app/src
yarn install --strict-semver
yarn run grunt build
cd ../../../../..
composer install
```

**Comment by bobdenotter** [comment]
Hi @marcingajda, 

If you're wondering why i haven't merged this one in, yet.. It's because the tests are failing for some reasons. I'm going to see if I can fix that first.

**Comment by marcingajda** [comment]
@bobdenotter Yes, I know. The errors are not related to this PR so I waited for a reaction from someone responsible for them :)

**Comment by bobdenotter** [comment]
Travis was fixed in #7798. Let's see how it fares now.

**Review by bobdenotter — APPROVED** [review]
And we also have green lights here! Thanks, @marcingajda

**Pull request merged**
