### PR TITLE
Set the canonical for single record pages. Fixes #3039.

### LINKED ISSUE #3039: Canonical doesn't change according to routing.
See screenshot. In both cases it should be `/age-sane-inquam`.

screen_shot_2015-03-06_at_14_44_28

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by CarsonF** [comment]
Shouldn't you leave out the url suffix?

**Comment by GawainLynch** [comment]
What @CarsonF said — wouldn't this default to the protocol the page is being served as:
```php
$app['resources']->setUrl('canonicalurl', sprintf('//%s%s', $paths['canonical'], $content->link()));
```

**Comment by CarsonF** [comment]
That's not what I said at all lol

**Comment by GawainLynch** [comment]
What, you think I can read?

**Comment by bobdenotter** [comment]
> Shouldn't you leave out the url suffix?

No. The canonical should define the protocol explicitly.

**Comment by GawainLynch** [comment]
> No. The canonical should define the protocol explicitly.

Yes! Good point, it's irrelevant to the served page, hence its purpose… Heading back to the Friday Corner.

**Comment by CarsonF** [comment]
>  The canonical should define the protocol explicitly.

Doesn't this go against #3040?

**Comment by bobdenotter** [comment]
> Doesn't this go against #3040?

Yes, this needs revisiting when I'm going to fid #3040.

**Comment by CarsonF** [comment]
:+1:

**Comment by GawainLynch** [comment]
:100:

**Pull request merged**
