### PR TITLE
Session cookie handling at logon/logoff

### PR DESCRIPTION
**Pull request by GawainLynch**
Currently a session is started on loading of the login page, and this sets a session cookie, and that cookie isn't cleared at logoff.

This addresses this limitation meaning that a system user, once logged out, will get full caching from Varish & Co.

### CODE REVIEW

**Comment by CarsonF** [comment]
Shouldn't the cookie be cleared with the `Session`?

**Comment by GawainLynch** [comment]
> Shouldn't the cookie be cleared with the Session?

You really should step back… right… now :tongue:

**Comment by CarsonF** [comment]
Shouldn't sessions be :bomb: :boom:

**Comment by GawainLynch** [comment]
Yeah, It's queued figuring it would encourage you to, you know, fix it…

**Comment by CarsonF** [comment]
It's the codeception tests that scare me

**Comment by GawainLynch** [comment]
Yeah, actually that is what stopped me and made me thing this was dependent on our other work… but still valid as a separate (rebased) PR… they are separate issues, but related to how we're not currently doing this well.

It can (obviously) just be worked around with a query parameter, but that made me want to get :leaves: out for the :koala:

**Comment by GawainLynch** [comment]
Moving this into the new session branch

**Pull request closed without merging**
