### PR TITLE
fix Multibyte String BUG

### PR DESCRIPTION
**Pull request by cx-emerge**
fix Multibyte String BUG

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hi @cx-emerge, 

In practice, how likely is it for a PHP install to have `mb_substr`, but not `mb_ucfirst`?

**Comment by rarila** [comment]
```php
if (function_exists('mb_strtoupper') && function_exists('mb_substr')) {
     return mb_strtoupper(mb_substr($str, 0, 1)) . mb_substr($str, 1);
} else {
     return ucfirst($str);
}
```

… sounds more reasonable to me.

**Comment by cx-emerge** [comment]
``` PHP
if (extension_loaded('mbstring')) {
	return mb_strtoupper(mb_substr($str, 0, 1)) . mb_substr($str, 1);
} else {
	return ucfirst($str);
}
```
sorry, In Windows have this problem, but in Linux do not have this problem.
I think it might be a file encoding issues
http://php.net/manual/en/function.ucfirst.php#84122

**Comment by CarsonF** [comment]
Can we not just deprecate this function and forward it to `title` function?

**Comment by GawainLynch** [comment]
> Can we not just deprecate this function and forward it to `title` function?

:+1:

**Comment by CarsonF** [comment]
@bobdenotter Do you have a problem with using the `title` function instead?

**Comment by GawainLynch** [comment]
Closing as this is handled correctly by Symfony and we should not be implementing our own.

**Pull request closed without merging**
