### PR TITLE
Listing by Taxonomy doesn't respect grouping taxonomies with option 'has_sortorder'

### PR DESCRIPTION
**Pull request by bobdenotter**
Forward port of #4602.

### CODE REVIEW

**Comment by GawainLynch** [comment]
Is `base-2016` worth catching in this too?

**Comment by bobdenotter** [comment]
I want to split the listing and search templates in base 2016. They're practically the same, but I've noticed this confuses a lot of people. 

Or, in the case where we don't split them, they'll need some serious work to make it more clear what's happening. 
Still, for now it wouldn't hurt to keep them in sync in this regard. Give me 5 minutes to update the PR.

**Comment by GawainLynch** [comment]
Zero stress… just thought I'd raise it either way… you have my back, I have yours :wink:

**Comment by bobdenotter** [comment]
Updated.

**Comment by GawainLynch** [comment]
Enough for the :koala:, enough for me :wink:

**Pull request merged**
