### PR TITLE
Restore Symfony fluent-interface chained call syntax

### PR DESCRIPTION
**Pull request by GawainLynch**
This restores the :scream: inflicted in #4378 and brings calm to Symfony addicts and their war on anti-perfection!

@rarila: I have updated the code sniffer rules so this won't increase the count :+1: 
@CarsonF: Any Belgian :beers: are fine :grin: 

**No :koala: were harmed in the making of this PR.**

### CODE REVIEW

**Comment by CarsonF** [comment]
Thank you mate :100:

**Comment by rarila** [comment]
So we now have a sniffer rule that makes sure the semicolon is at the correct position?

**Comment by GawainLynch** [comment]
Technically we always did… The rule set we based ours on allows it, one of the Squiz rules over rides it.

These sill fails test:
```php
    $moo = 'cow' ;

    $foo->bar()
        ->baz()
;
```

**Comment by rarila** [comment]
:leaves: 

Didn't saw a PR on that because of ninja edit

**Comment by GawainLynch** [comment]
I don't know what you mean :wink:

**Pull request merged**
