### PR TITLE
Add foreign key checks to schema management checks

### PR DESCRIPTION
**Pull request by GawainLynch**
This is a forward port of the changes in #3872.

@ntomka could you be so kind as to review/test when you have a second? :beers:

### CODE REVIEW

**Comment by ntomka** [comment]
Certainly! :beers: 

I didn't know where to put these changes and as I wrote, it seemed to work for me in master anyway. I will test this asap.

**Comment by GawainLynch** [comment]
OK… I should be banned from programming… Updated version coming in a minute :frowning:

**Comment by bobdenotter** [comment]
\* twiddles thumbs patiently \*

**Comment by ntomka** [comment]
@bobdenotter Sorry for the late answer, but I was on vacation for days.

I still get the error described in #3872 [here](https://github.com/bolt/bolt/pull/3872#issuecomment-125134748).

**Comment by ntomka** [comment]
BUT if I add the try-catch mentioned there, everything works as expected (related to this PR).

**Comment by GawainLynch** [comment]
You have to add the try/catch to the extension, or core?

**Comment by GawainLynch** [comment]
Was just getting my :beer: ready… and just got to create this… for those following along (code &copy ;@ntomka):

```php
    public function initialize()
    {
        $this->tableName = 'foo_bar';

        $this->app['schema']->registerExtensionTable(function (Schema $schema) {
            // Define table
            $table = $schema->createTable($this->tableName);

            // Add primary column
            $table->addColumn('id', 'integer', array('autoincrement' => true));
            $table->setPrimaryKey(array('id'));

            // Add working columns
            $table->addColumn('userid', 'integer');

            // Index column(s)
            $table->addIndex(array('userid'));

            // Constraints
            $table->addForeignKeyConstraint(
                $this->app['config']->get('general/database/prefix', 'bolt_') . 'users'
                , array('userid')
                , array('id')
                , array("onUpdate" => "CASCADE", "onDelete" => "CASCADE")
            );

            return $table;
        });
    }
```

And after creation of the table:
```
An exception occurred while executing 'CREATE TABLE foo_bar (id INTEGER NOT NULL, userid 
INTEGER NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_8D1AB1FEF132696E FOREIGN KEY 
(userid) REFERENCES bolt_users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY 
IMMEDIATE)': SQLSTATE[HY000]: General error: 1 table foo_bar already exists
```

**Comment by ntomka** [comment]
@GawainLynch To [this](https://github.com/bolt/bolt/blob/master/src/Storage/Database/Schema/Manager.php#L310) place.

I don't get this error.

**Comment by GawainLynch** [comment]
Even without the FK constraint, and that in a try/catch I am getting that exception about the table… It's not related to this PR and I'll look again tomorrow I think… Now is :beer: :clock1:

**Comment by ntomka** [comment]
:beers:

**Comment by GawainLynch** [comment]
@ntomka I am presuming that you're creating a class that extends BaseTable to see your error? (yes, I should be drinking :beer:)

**Comment by ntomka** [comment]
No, I do it the exact way you described it here earlier.

Yes, drink that :beer: before it gets hot! :D

**Comment by GawainLynch** [comment]
@ntomka a7b950622a1ff4e43beae1ac884c0a69150154a6 should remove the need for the try/catch.

@bobdenotter this is now good to go :rocket:

**Comment by ntomka** [comment]
So that if block doesn't necessary for extensions at all. Thank you! :+1:

**Comment by GawainLynch** [comment]
We've fixed a few things as the result of this… A good result! Thank for your help @ntomka :+1:

**Pull request merged**
