### PR TITLE
Timed publish tweak

### PR DESCRIPTION
**Pull request by GawainLynch**
This makes the parameters for timed publishing checks independent of caching.

**[RFC]**
This PR introduces the `performance` configuration key, as a grouping for these types of parameters, with a sub key of `dispatchers` … thoughts on naming?

These should be considered advanced user territory.

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm not too enthusiastic about the name, but I don't have a better alternative yet. 

We should probably also ass some defaults to https://github.com/bolt/bolt/blob/master/src/Config.php#L1034 .

**Comment by GawainLynch** [comment]
> We should probably also add some defaults to

Hmm … interesting point, architecturally. Right his very second the defaults are in the `get()`, i.e.

```
$this->config->get('performance/dispatchers/timed_records', 60)
```

So shift them into `Config`?

**Comment by SahAssar** [comment]
Imo shifting them to config would be better, personally I don't like that we have config defaults spread out so much.

**Comment by bobdenotter** [comment]
I agree with @SahAssar

**Comment by GawainLynch** [comment]
WFM

**Comment by bobdenotter** [comment]
Let's see if we come up with a better name, otherwise we'll merge this in! :-)

**Comment by rossriley** [comment]
By way of an alternative suggestion, I quite like what Drupal does with these and allows performance conscious users to move them out of the request cycle, and install a cron job instead that runs every minute.

I'm not suggesting we do that immediately, but it might make for good naming consistency in the future if we do something like:

```
performance:
    cronjobs:
        timed_records: 60
```

Then in a future version when we offer cron versions of these, the config can be set to false either globally or individually:

```
performance:
    cronjobs:
        timed_records: false
        another_operation: 60
```
or
```
performance:
    cronjobs: false
```

**Comment by GawainLynch** [comment]
At the risk of over thinking this … I can see a genuine need to, and not, use a cron job … ¿porque no los dos?

Would it make sense to have two, e.g.
```
performance:
    dispatchers:
        timed_records: false
    cronjobs:
        timed_records: 30
```

**Comment by bobdenotter** [comment]
Since we already have a [Cron handler](https://github.com/bolt/bolt/blob/release/3.0/src/Cron.php), it makes sense to use that. 

Perhaps flip it around: 

```
performance:
    timed_records: 
        interval: 30
        use_cronjob: true
    foo: 
        interval: 60
        use_cronjob: false
```

**Comment by bobdenotter** [comment]
What should we do with this one? Merge as-is, or update the code to my latest suggestion first? :-)

**Comment by GawainLynch** [comment]
Ha! Yeah, I was looking at this PR last night.

I am tagging this for 3.3 as I want to land the configuration load/validate stuff first and take up the work that will come out of this week's hackathon from @PhillippOhlandt, @SahAssar and myself.

**Comment by GawainLynch** [comment]
> Perhaps flip it around:

I like the overall idea, but something I am trying to work though in my head right now is the `interval` … for a request, as it is caching we're touching, the value of `interval` is and integer of seconds. With cron it is a string: `hourly`, `daily`, 'weekly`, etc …

**Comment by GawainLynch** [comment]
Should be GTG now

**Pull request merged**
