### PR TITLE
[4.0] Remove {{ link() }} as it now is used upstream

### PR DESCRIPTION
**Pull request by GawainLynch**
Per #6614

### CODE REVIEW

**Comment by GawainLynch** [comment]
Yeah, was going to leave a note to hold off … I just did the cascade this morning, and there is no mad rush on this one, so worst case Monday.

**Comment by GawainLynch** [comment]
Rebased against the branch merges, and going green locally.

**Comment by bobdenotter** [comment]
Yup, green lights! 🚦

**Comment by GawainLynch** [comment]
One … more … (major) branch … to … come … Oh my, I am currently brimming with excitement!

Breathe, Gawain, breathe!

**Pull request merged**
