### PR TITLE
Removing `default` and `base-2014` themes. Only `base-2016` should stay.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
I love the branch name :smile_cat:

**Comment by bobdenotter** [comment]
There should be only one test failure left: 

```
There was 1 failure:

1) Bolt\Tests\Twig\TextHandlerTest::testLocaleDateTimeCdo
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-2012-06-14 09:07:55
+June 14, 2012 09:07

/Users/bob/Sites/bolt-testing/tests/phpunit/unit/Twig/Handler/TextHandlerTest.php:72
```

Relevant code: 

```
        $result = $handler->localeDateTime('2012-06-14 09:07:55', '%B %e, %Y %H:%M');
        $this->assertSame('2012-06-14 09:07:55', $result);
```

Why did that work?

**Comment by GawainLynch** [comment]
It passes here… have you set a locale format somewhere else?

**Comment by GawainLynch** [comment]
Oh… nvm, Travis failing too

**Comment by bobdenotter** [comment]
Weird stuff, right? :-)

**Comment by bobdenotter** [comment]
Looking at the output:

```
--- Expected
+++ Actual
@@ @@
-2012-06-14 09:07:55
+June 14, 2012 09:07
```

What is printed for `actual` does actually make sense, right? How would / should that code produce `2012-06-14 09:07:55` ?

**Comment by GawainLynch** [comment]
Yeah, but it is mocked earlier up and `setlocale()` should return a false.

**Pull request merged**
