### PR TITLE
extension to twig_extension

### PR DESCRIPTION
**Pull request by jmschelcher**
should correct issue #2487

### CODE REVIEW

**Comment by rossriley** [comment]
Looks good. Any chance we could have camel case for variables since we standardize on that across the codebase, so $twigExtensions rather than $twig_extensions.

**Comment by jmschelcher** [comment]
updated !

**Comment by bobdenotter** [comment]
Merging in, thank you again!

**Comment by jmschelcher** [comment]
thanks to you for this great CMS !

**Pull request merged**
