### PR TITLE
Allow 'name' in contenttype to override translation, for 2.1.x

### PR DESCRIPTION
**Pull request by bobdenotter**
A 2.1.x version of #3239

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hold with merging.. needs additional tweak.

**Comment by GawainLynch** [comment]
Molasses-CI build killed then.

**Comment by bobdenotter** [comment]
Nah, nevermind.. This is good enough for now, if we're going to replace it in 2.2 regardless. :-) 

(restarted Take-your-time-Travis)

**Comment by GawainLynch** [comment]
Looks like things are back to normal at packagist… that was quick!

**Pull request merged**
