### PR TITLE
Sortable Select Fields

### PR DESCRIPTION
**Pull request by rossriley**
This is Part 1 of the process discussed in #4865 

This PR adds the option to declare a select field as sortable, eg:

```
    selectentry:
        type: select
        values: entries/id,title
        autocomplete: true
        multiple: true            
        sortable: true
```

It also includes the select2 plugin and css that will be used to add sortable relations in a following PR.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Oooh, shiny! 🌟

**Comment by rarila** [comment]
Shouldn’t we pull ``select2.sortable`` from github instead of adding it to our repo?

**Comment by bobdenotter** [comment]
> Shouldn’t we pull select2.sortable from github instead of adding it to our repo?

If that's a possibility, yes, I think we should.

**Comment by rossriley** [comment]
Well it's not an official plugin, one I half adapted and modified from one that  was compatible with the old version of select2.

**Comment by bobdenotter** [comment]
Ah, right. Then let's merge this one in, right? :-)

**Comment by rarila** [comment]
ah, ok

**Comment by rarila** [comment]
Hmm, a tiny comment [here](https://github.com/bolt/bolt/blob/release/3.0/app/src/lib/Versions.md) where it was from and that it is patched would probably be nice for future reference

**Pull request merged**
