### PR TITLE
Flip array replace arguments

### PR DESCRIPTION
**Pull request by CarsonF**

### CODE REVIEW

**Comment by bobdenotter** [comment]
water

**Comment by GawainLynch** [comment]
Strangely `git blame` doesn't assign any blame to that one...

**Comment by bobdenotter** [comment]
Gawain: That's probably because this error has been in there since _before_ we moved `app/src/` to `src/`.

**Comment by CarsonF** [comment]
I'm to blame #2707

**Comment by GawainLynch** [comment]
Nah mate, it was the gnomes!

**Comment by CarsonF** [comment]
@bobdenotter's water gif is the real winner here!

**Pull request merged**
