### PR TITLE
Add foreign key checks to IntegrityChecker

### PR DESCRIPTION
**Pull request by ntomka**
This PR is related to #3745. That change added foreign keys only on table creation leaving alters out. So I added few more lines to handle new or modified foreign keys after creation.

I don't know for sure if this is needed in master branch.

### CODE REVIEW

**Comment by GawainLynch** [comment]
> I don't know for sure if this is needed in master branch.

Potentially… Thoughts @rossriley ?

**Comment by rossriley** [comment]
yes, let's keep the master/2.2 the same with IntegrityChecker. I personally haven't touched this particular method yet so if we have a master version too we can get them both merged in.

**Comment by ntomka** [comment]
@rossriley If I use an extension to add a table it is created with correct foreign keys, but if I change the definition I get an exception [here](https://github.com/bolt/bolt/blob/master/src/Storage/Database/Schema/Manager.php#L310) as `$this->app['schema.tables']` contains only Bolt's base tables. If I surround this statement with a try block to pass the thrown exception everything works as expected, the change is committed to database.

So it seems to me my change in this PR is not needed in master, but it is possible that I'm doing something completely wrong. :)

**Comment by bobdenotter** [comment]
Is this one 'good to go'?

**Comment by GawainLynch** [comment]
@bobdenotter I think so, I was going to marry it with a forward… wait… did I just say "marry"… 

Seriously… well I tried first go… but I wanted to combine it with a forward port to master so it didn't get lost. My apologies, @ntomka

**Comment by ntomka** [comment]
I can't get your point @GawainLynch. I'm married and I'm proud of it! :gem: 

As I stated above changes in master maybe already resolved the issue in this PR, so it is only affects 2.2 branch (and faced another problem in master when changing FK definitions, but that's another story).

You should try a sample in both master and 2.2, like this in an extension:

```PHP
$this->app['integritychecker']->registerExtensionTable(function (Schema $schema) {
    // Define table
    $table = $schema->createTable($this->tableName);

    // Add primary column
    $table->addColumn('id', 'integer', array('autoincrement' => true));
    $table->setPrimaryKey(array('id'));

    // Add working columns
    $table->addColumn('userid', 'integer');

    // Index column(s)
    $table->addIndex(array('userid'));

    // Constraints
    $table->addForeignKeyConstraint(
        $this->app['config']->get('general/database/prefix', 'bolt_') . 'users'
        , array('userid')
        , array('id')
        , array("onUpdate" => "CASCADE", "onDelete" => "CASCADE")
    );

    return $table;
});
```

Try to change the FK constraint. I know in master this looks a bit different, but how you define FKs is the same.

**Comment by GawainLynch** [comment]
> I can't get your point @GawainLynch. I'm married and I'm proud of it!

Yes, and your wedding photos are wonderful… They put a smile on Erin and my faces :+1:

**Comment by GawainLynch** [comment]
On the DB thing… it's just been a time constraint on my part… RL work versus Bolt core versus having written too many damn extensions :frowning: 

Help wanted :flags:

**Pull request merged**
