### PR TITLE
Filter db tables

### LINKED ISSUE #2769: Listing all tables can make DBAL mad
DBAL's Schema Manager tries to create objects for all tables in a database, but fails if it doesn't recognize a type ([here](https://github.com/doctrine/dbal/blob/v2.5.1/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L423)).

Bolt should *only* care about tables its own tables (with the prefix specified).

Unfortunately the only way I can find to get around this is by overridding the platform classes.
`getListTablesSQL` needs another where condition for our prefix.

[SqlitePlatform](https://github.com/doctrine/dbal/blob/v2.5.1/lib/Doctrine/DBAL/Platforms/SqlitePlatform.php#L435)
[MySqlPlatform]
(https://github.com/doctrine/dbal/blob/v2.5.1/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L349)
[PostgreSqlPlatform](https://github.com/doctrine/dbal/blob/v2.5.1/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L259)

### PR DESCRIPTION
**Pull request by CarsonF**
Look what I found! DBAL has a config option to filter tables!

Should fix #2769 and #3936.

### CODE REVIEW

**Comment by bobdenotter** [comment]
awwweesssooommee

**Comment by CarsonF** [comment]
:shipit:

**Comment by bobdenotter** [comment]
Shouldn't this be applied to `master` as well?

**Comment by GawainLynch** [comment]
Yes, but we're taking a slightly different approach… /me also nags @CarsonF :stuck_out_tongue:

**Comment by bobdenotter** [comment]
Should we then merge this into master, only to make sure we don't forget?

**Comment by GawainLynch** [comment]
Nah, it's headed for the SP in master

**Pull request merged**
