### PR TITLE
Use ISO/IEC 80000 format

### PR DESCRIPTION
**Pull request by GawainLynch**
Wrong is wrong.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Eew. I still have nightmares from when phpmyadmin suddenly started putting everything in "Mebibytes". "The maximum upload size is 8.192 KiB". Uhm, wait, so?

We could also fix this the other way round, and just divide by 1000, instead of 1024. ;-)

**Comment by rarila** [comment]
Could we use feet, gallons, ounces, fahrenheit, jiffies and dog years, please ;-)

**Comment by bobdenotter** [comment]
"This image is 0.0004 furlong by 0.000001 parsec"

**Comment by GawainLynch** [comment]
To be honest, I was most objecting to case rather than base... However I figured tht either @rarila or @tobias2k wouldn't force me to up my ante...

**Comment by bobdenotter** [comment]
Enough chitchat. merging in!

**Pull request merged**
