### PR TITLE
Add 'status' to `querySelectList()`, so it can be used in relations.

### PR DESCRIPTION
**Pull request by bobdenotter**
This change will allow you to do this, for example:

```yml
    relations:
        entries:
            label: "Choose an entry"
            format: "{{ item.status != 'published' ? '(Not published) ' : '' }} {{ item.title|escape }} (№ {{ item.id }})"
```

### CODE REVIEW

**Comment by JarJak** [comment]
Still not compatible with docs https://docs.bolt.cm/3.3/contenttypes/relationships

> For example if you have two fields for firstname and lastname you might put '{{item.firstname}} {{item.lastname}}' here.

**Comment by bobdenotter** [comment]
@JarJak That should work.. Check method `neededFields()` in `bolt/bolt/src/Storage/ContentRequest/Edit.php`, where it compiles a list of fields it needs to get.. `status` needed to be added separately, because it's not a "real" field.

**Comment by JarJak** [comment]
Ok :)

**Comment by GawainLynch** [comment]
@bobdenotter This is "feature" and should go in 3.4 :wink:

**Comment by bobdenotter** [comment]
@GawainLynch I was thinking about that, but I feel it's a "bug", instead of a "feature". Currently, the docs say: 

> How to show the titles for each record that can be selected. This takes a twig string where item is the record that can be selected. For example if you have two fields for firstname and lastname you might put '{{item.firstname}} {{item.lastname}}' here. The default is '{{ item.title|escape }} (№ {{ item.id }})'

I think most people would reasonably assume that they can use fields like they do in a regular twig template, including the `.status`. That doesn't work, so it's a bug. 

(i wouldn't _really_ mind if we bumped it to 3.4, though)

**Comment by GawainLynch** [comment]
Ah, right.

On approach though, this is [better here](https://github.com/bolt/bolt/blob/v3.3.6/src/Storage/ContentRequest/Edit.php#L227) with the addition of:

```
$neededFields[] = 'status';
```

That will keep the logic out of the repo and in the hands of the caller.

**Comment by bobdenotter** [comment]
Will do.

**Pull request merged**
