### PR TITLE
Allow multiple fields with 'type: slug' in a content.

### LINKED ISSUE #2489: Allow for more than one slug
As discussed on IRC: It should be possible to add more than one field with `type: slug`. Currently Bolt crashes if you do this.

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #2489.

### CODE REVIEW

**Comment by bobdenotter** [comment]
so, you can now do this: 

```
  fields:
    title: 
      type: text
    slug:
      type: slug
      uses: [ title ]
    title2: 
      type: text
    slug2:
      type: slug
      uses: [ title2 ]
```

**Comment by GawainLynch** [comment]
Getting this in the UI, alignment not right on the fieldname addition:
dual-slugs

**Comment by GawainLynch** [comment]
LGTM

**Comment by bobdenotter** [comment]
Ping @trafex.

**Comment by TrafeX** [comment]
@bobdenotter Thanks, I'll go test it out!

**Comment by jmschelcher** [comment]
Hi, does that mean that I can use more than 1 relation to that same contenttype (one per contenttype/slug) ?

**Pull request merged**
