### PR TITLE
Fix adjust sidebar height function again

### PR DESCRIPTION
**Pull request by bnelson-cainc**
Remember that fix I submitted for the secondary (black) menu on the left last week?  I found a small issue with it.

It works great as long as the content is longer than the menu, but when the reverse is true, as it is on some of the admin menus, I saw menu items that weren't in the black anymore. I hardly ever use those menus anymore, which is why I forgot to check them.

This small adjustment to the original change fixes that, and hopefully it's perfect now.

Sorry for the extra churn!

### CODE REVIEW

**Comment by bobdenotter** [comment]
@bnelson-cainc Looks like you PR'ed against the wrong branch. :-)

Feel free to PR it against whatever branch you started from, we'll make sure it gets merged down to later branches.

**Comment by bnelson-cainc** [comment]
I actually did the code against the right branch, but when I created the PR on the github website I forgot to check all the drop-downs were correct.  Redo'ing it correctly (I hope!) this time.  :-)

**Comment by bobdenotter** [comment]
@bnelson-cainc You can change the target of the pr in github itself.. Click "Edit" and change it: 

screen shot 2016-12-08 at 17 33 33

**Comment by bnelson-cainc** [comment]
I knew you could do it when you first create a PR, but I forgot about editing it.  I panicked.  :-)  Because I was afraid you'd panic when you saw the diff.  :-)

Thanks for the reminder!

**Pull request closed without merging**
