### PR TITLE
Mais um … para cuidado camino

### PR DESCRIPTION
**Pull request by GawainLynch**
This one unlocks a special surprise!

…details to follow after merge :wink:

### CODE REVIEW

**Comment by bobdenotter** [comment]
Green lights!

**Comment by rarila** [comment]
@GawainLynch Ok merge is done but where are the details?

**Comment by GawainLynch** [comment]
Last few months worth of Tuesday dev meetings … but … Bolt 4.0-dev will be:

* Long-cycle (aiming for late 2017 release), running in parallel with 3.x minor releases
* Use Symfony 3, Twig 2, etc
* Remove a tonne of stuff that we've deprecated over the years
* `master` is (obviously) now for 4.0-dev, and there is a `3.x` branch that will serve as a "master" for future 3.x minor release branches
* Branches will continue to merge from 3.n-stable down to 3.n+1 (beta) branch, 3.n+2 (alpha) branch, `3.x`  branch, and `master`

**Comment by rarila** [comment]
Development details?! Disappointing! Someone mentionend a **surprise**!

**Comment by GawainLynch** [comment]
Haha… There is! This was the precursor to #6079 … in that is fixed the last of the needed SF3 deprecation blockers to make this happen … No :smile_cat: were harmed in the making of either PR :wink:

**Pull request merged**
