### PR TITLE
Fix #4196 - ckeditor on chrome in android is not working

### LINKED ISSUE #4196: ckeditor on chrome in android is not working
If you use the backend on an android device the ckeditor component does not work. If you use the same on firefox (or iOS) it works.

According to the documentation the compatibility flags are changed in ckeditor 4.5 and the ckeditor should work. http://docs.ckeditor.com/#!/guide/dev_browsers - http://docs.ckeditor.com/#!/guide/dev_unsupported_environments

I'm happy to help test a fix, but I'm lost in trying to locate why it's not working.

### PR DESCRIPTION
**Pull request by rarila**
[WIP] Don't merge until :+1: from @jadwigo 

Was it really that easy?

Fixes #4196

### CODE REVIEW

**Comment by rarila** [comment]
Ok, the issue itself is fixed…

But I still would say we should merge it as I don't see a need to not use cke for file edit on mobile while we use it for html fields. Opinions?

**Comment by bobdenotter** [comment]
This is for Codemirror, on the "Edit file" pages.. 

The issue was for CKeditor on "Edit record" pages.

I don't think this is correct.

**Comment by rarila** [comment]
@bobdenotter As I said, the issue itself is solved. I thought, now that the PR is there, to merge it anyway as that behavior makes no sense for me

**Comment by bobdenotter** [comment]
Does codemirror work on android? IMHO the codemirror is only a nuisance when i'm on iphone or ipad.

**Comment by rarila** [comment]
@bobdenotter hmm, ok, didn't thought that is a problem. Can't try at the moment as I can't login from android :-(

**Comment by bobdenotter** [comment]
Try it on codemirror.net.. If you think it adds something worthwhile on mobile, i'll merge this in. ;-)

**Comment by rarila** [comment]
@bobdenotter In a short test I've seen nothing that makes it worse than a plain textarea, but it at least adds syntax coloring which I consider as helpful.

**Comment by rarila** [comment]
@bobdenotter said :+1:

**Pull request merged**
