### PR TITLE
Update MailerServiceProvider.php

### PR DESCRIPTION
**Pull request by geggleto**
- BugFix Removed assignments from if's
- Related to #4764

### CODE REVIEW

**Comment by bobdenotter** [comment]
Because i'm dense I didn't get this straight away, but I agree that the current coding style is confusing. :+1: from me.

**Comment by Boorj** [comment]
that produced an error, actually :(

**Comment by GawainLynch** [comment]
Nothing functionally changes here.

What are you trying to achieve? As I think that if you've resolved something locally, this is not to root cause.

**Comment by GawainLynch** [comment]
nvm… I see, the second one isn't wrapped in `()`. This, people, is why you shouldn't review PRs before :coffee: in the morning! :grin:

**Pull request merged**
