### PR TITLE
Use 'executeQuery'. Fixes publishing for items with 'Timed Publish'. Fixes #3279

### LINKED ISSUE #3279: SQL Error trying to publish timed publications
Timed publication of records for Array failed: An exception occurred while executing 'UPDATE bolt_en_articles SET status = 'published', datechanged = :now WHERE status = 'timed' and datepublish < :now': SQLSTATE[HY000]: General error: mode must be an integer

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by CarsonF** [comment]
Stupid stupid. Who even decided query was better to use anyways.

**Comment by CarsonF** [comment]
Actually it may be because master slave stuff. executeQuery doesn't detect the query it's running to know to switch to master connection

**Comment by bobdenotter** [comment]
@CarsonF Sure about that? We can't just use timestamps for datetime columns, right? 

Anyhow, using this, it won't trigger for me: 

```
        $now = time();

        try {
            // Check if there are any records that need publishing.
            $stmt = $this->app['db']->executeQuery(
                "SELECT id FROM $tablename WHERE status = 'timed' and datepublish < $now"
            );

            // If there's a result, we need to set these to 'publish'.
            if ($stmt->fetch() !== false) {
                $this->app['db']->query("UPDATE $tablename SET status = 'published', datechanged = $now WHERE status = 'timed' and datepublish < $now");
            }
```

**Comment by CarsonF** [comment]
Almost positive db stores them as unix timestamps, which are ints. 

Also, ints work for me and that timestamp string throws an exception. Pretty sure the timestamp string is converted by dbal.

**Comment by CarsonF** [comment]
Haha waitttttt. *facepalm*. We don't even need the variable. sql has `now()`.

**Comment by bobdenotter** [comment]
Ok, the following works, except for the offset you mentioned.. :-(

try {
            // Check if there are any records that need publishing.
            $stmt = $this->app['db']->executeQuery(
                "SELECT id FROM $tablename WHERE status = 'timed' and datepublish < CURRENT_TIMESTAMP()"
            );

            // If there's a result, we need to set these to 'publish'.
            if ($stmt->fetch() !== false) {
                dump($stmt);
                $this->app['db']->query("UPDATE $tablename SET status = 'published', datechanged = CURRENT_TIMESTAMP() WHERE status = 'timed' and datepublish < CURRENT_TIMESTAMP()");
            }
        }

**Comment by bobdenotter** [comment]
PR Fixed!

**Comment by bobdenotter** [comment]
@CarsonF 

> Sorry, "everywhere" meaning in this method. aka these 3 times.

If we only do that here, we'll break the current behaviour.. if we did it properly, we'd also have to make sure we fix the _other_ locations where `datepublish` is modified. Mostly in 'editcontent' i assume.

**Comment by GawainLynch** [comment]
:traffic_light:

**Pull request merged**
