### PR TITLE
Fix backend publish process quirks (#5085)

### LINKED ISSUE #5085: [BUG][UX] back-end publish process quirks
The process of publishing from the content listing has some weird quirks.

The first two steps are normal
image

image

But the third step tells me "there is no undo" which is just FUD for this action.
image

The real quirk comes after I confirm - only the published records are displayed and I have to refresh the page to get the other records back. The _pager_ is hidden too.

image

Details
-------

 - Relevant Bolt Version: 3.0 / master
 - Install type: Composer install
 - PHP version: 5.6
 - Used webserver: Apache
 - For UX/UI issues: Chrome Version 49.0.2623.87 (64-bit) Linux

### PR DESCRIPTION
**Pull request by SahAssar**
Fixes #5085 and #5468

This does two things:
1. check if the request is safe (status change) or unsafe (delete) in listing actions and only ask the user to confirm if it is unsafe.
2. Allow unpublished records in the async zone, since all async routes are also backend routes (right?) and should therefore show unpublished too.

Since it's a bugfix I targeted release/3.0, lemme know if this should go in 3.1 instead.

### CODE REVIEW

**Comment by rarila** [comment]
A few things:

- I would prefer to feed ``modifications`` as function parameter into ``sendQuery()`` as it is of local nature.

- I'm not quite happy with extracting ``sendQuery()`` as what it does is more of ``sendModifyRecordsQuery()``. buicListing (if I remember correctly, though I may be wrong) is more to be seen as general listing object with just one specialized functionality added yet. To show that connection… naming, inlining, …? At least it should be a private method (underscore).

- I think there's no need for ``safeQuery``, just ``if (!actions[action].safe) {`` will do as there's only one action in that function call. You could even simplify it to ``if (action === 'delete') {`` and save some more lines.

- Please add some spaces, eg. ``if(`` => ``if (``, ``)else(`` => ``) else (``, …. Otherwise one could think the OCD is weak in you :smiley:  And a doc block for ``sendQuery()`` would be awesome, too.

**Comment by SahAssar** [comment]
My OCD has failed you, master. My work shall double tomorrow to make up for this! ;)

**Comment by rarila** [comment]
@SahAssar  As discipline you now write 1000 spaces on that blackboard! :black_large_square:

**Comment by SahAssar** [comment]
@rarila Should be fixed now, and my blackboard is filled with spaces!

**Comment by rarila** [comment]
:rotating_light: We have a nice PR here, ready to merge! Well done! :+1: :smile:

**Comment by bobdenotter** [comment]
Let's go, then! 👍

**Pull request merged**
