### PR TITLE
Config update

### PR DESCRIPTION
**Pull request by lenvanessen**
Switched out Sendgrid for Sparkpost, because Sendgrid changed their pricing model and now only offer free trails, and Sparkpost is still free up to 100.000 mails

### CODE REVIEW

**Comment by SahAssar** [comment]
hehe, seems like we will have to do this once a year from now on: #4911

**Comment by SahAssar** [comment]
Hmm, one thing though, could you change your base to the lenvanessen-patch-1 branch? That way we won't get that merge commit :)

**Comment by GawainLynch** [comment]
> Hmm, one thing though, could you change your base to the lenvanessen-patch-1 branch? That way we won't get that merge commit 

Hold my :beer:, I got this.

**Comment by SahAssar** [comment]
@GawainLynch ❤️

**Pull request merged**
