### PR TITLE
Only log content not found errors if slug isn't numeric, since next it next checks by id.

### PR DESCRIPTION
**Pull request by CarsonF**
Only log content not found errors if slug isn't numeric, since next it next checks by id.

Fixes first part of #3176

### CODE REVIEW

**Comment by bobdenotter** [comment]
:+1:

**Comment by gwbonline** [comment]
When is this implemented in Bolt? I have 2.1.4 installed and I still get errors like below when viewing an entry on the frontpage...

730 	Error 	storage 	contentlink 	/bericht/lutsmuur-moet-versterkt-worden 	Requested specific query 'bericht', not found. 

Can someone tell me what this error means?

**Comment by GawainLynch** [comment]
Hmm… This PR made it into 2.1.4.

**Comment by gwbonline** [comment]
I'll wait for a newer release. Maybe it is solved by then. It's not a big problem, I only want as few errors logged as possible. They do mean something I think.

**Pull request merged**
