### PR TITLE
Fixes problem of web profiler bundle template location by using reflection. Fixes #4431

### LINKED ISSUE #4431: Web Profiler Bundle template location
When Symfony is installed along side Bolt, the location of the web profiler bundle changes. [Symfony uses Composer's `replace` functionality](https://github.com/symfony/symfony/blob/2.8/composer.json#L77), which moves the web profiler bundle to `vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle`.

During the Bolt application's initialisation phase, Bolt attempts to load the web profiler bundle's templates into the twig engine, but in doing so, assumes they are always in the same place; `vendor/symfony/web-profiler-bundle/Symfony/Bundle/WebProfilerBundle/Resources/views`.

This causes Bolt to crash with a `Twig_Error_Loader` exception and the message:

> The "/var/www//vendor/symfony/web-profiler-bundle/Symfony/Bundle/WebProfilerBundle/Resources/views" directory does not exist.

### PR DESCRIPTION
**Pull request by emarref**
Use reflection to determine the location of the web profiler bundle, thereby removing the guesswork of configuring twig with the location of the web profiler bundle's templates.

I also don't like brown M&Ms.

### CODE REVIEW

**Comment by GawainLynch** [comment]
For a reason I haven't had the time to look into yet, this change breaks Composer installs:

```
Class 'Symfony\Component\DependencyInjection\ContainerAware' not found
```
```
…/­vendor/­symfony/­http-kernel/­Symfony/­Component/­HttpKernel/­Bundle/­Bundle.php:29
```

**Comment by GawainLynch** [comment]
OK, sorry about the delay.

What's going on here is that creating the ReflectionClass from `Symfony\Bundle\WebProfilerBundle\WebProfilerBundle` tried to invoke the whole `Bundle` chain which ultimately requires `ContainerAware` which we don't include.

Easiest fix would probably be if you changed to use the profiler Twig extension class to reflect and just use a double `dirname()` like:
```php
$refProfilerClass = new \ReflectionClass('Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension');
$webProfilerPath = dirname(dirname($refProfilerClass->getFileName()));
```

If you want to update that, tests should pass and we're good to go.

**Comment by emarref** [comment]
The last build failed due to composer failing to download some dependencies. I'm closing to re-open which will trigger another build.

**Comment by emarref** [comment]
I tried using composer directly to find the location of the bundle class, but the tests kept failing. I've reverted to your suggested solution of testing the extension class now.

**Comment by bobdenotter** [comment]
I'm not at the computer right nor so i can't take a better look, but I do know that Travis has been grumpy today. The failure might not be with your code necessarily. I'll take a look tomorrow, unless somebody beats me to it. :-)

**Comment by emarref** [comment]
Looks like composer is failing to download some dependencies. I'll postpone this fix 24hrs. I think using composer's `findFile()` method would be the tidiest solution. Better than a reflection call on every request anyway.

**Comment by GawainLynch** [comment]
> The last build failed due to composer failing to download some dependencies.

Nope, it is just the GitHub limit being hit, so it pulls in source rather than dist.

The error is easy to reproduce on a Composer install, and this fixes it:
```php
$refProfilerClass = new \ReflectionClass('Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension');
$webProfilerPath = dirname(dirname($refProfilerClass->getFileName()));
```

**Comment by CarsonF** [comment]
@emarref `Symfony\Bundle\WebProfilerBundle\DependencyInjection\WebProfilerExtension` has the same problem as the `Bundle` class. We don't have Symfony's DependencyInjection component, so using that for reflection won't work.

As far as composer, we don't really have composers class loader available. I know there's mention of it in `ResourceManager` but I think that case is rarely used.

and @GawainLynch beat me to the rest of it :)

**Comment by emarref** [comment]
Thanks @CarsonF, are you able to confirm the approach reflecting the extension class fails for you? @GawainLynch confirms it is working for him.

**Comment by CarsonF** [comment]
@emarref Yeah reflecting the `Twig\WebProfilerExtension` class works for me too

**Comment by emarref** [comment]
Ah sorry, just noticed the `Twig` part. I'll update. Thanks.

**Comment by GawainLynch** [comment]
:+1:

**Pull request merged**
