### PR TITLE
Remove utilphp

### PR DESCRIPTION
**Pull request by CarsonF**
- Replaced utilphp with builtin methods.
- Simplified taxonomy slug name lookup.

### CODE REVIEW

**Comment by GawainLynch** [comment]
So long to possibly one of the worst PHP libraries every written :fire: :boom:  :fire: :boom:  :fire: :boom:  :fire: :boom:  :fire: :boom:

**Comment by GawainLynch** [comment]
Test failures unrelated.

**Comment by bobdenotter** [comment]
This will break some extensions at the very least. :-/

**Comment by GawainLynch** [comment]
No, the library is still included … I got Carson to rebase out the composer.json change for exactly that reason.

**Comment by GawainLynch** [comment]
> Yay for this change. Perhaps drop the library itself in 4.0?

You better believe it! ;-)

**Pull request merged**
