### PR TITLE
Removed jshint global declaration of UAParser object

### PR DESCRIPTION
**Pull request by rarila**

### CODE REVIEW

**Comment by bobdenotter** [comment]
My bad! Sorry! :-)

**Comment by bobdenotter** [comment]
Whoops! I'm having troubles merging this in. (And i've grown a bit scared of them after messing up last week). 

Can you do a fetch upstream on your end?

**Comment by rarila** [comment]
Don't worry, this one is not urgent at all. I'll do it again after the other is in. Guess that is faster than rebasing :-)

**Comment by rarila** [comment]
Rebased …

**Comment by bobdenotter** [comment]
Thank you!

**Pull request merged**
