### PR TITLE
Merge pull request #1 from bolt/master

### PR DESCRIPTION
**Pull request by miguelavaqrod**
Update from original

### CODE REVIEW

**Comment by miguelavaqrod** [comment]
Ups... I DO apologize... I was just trying to update my fork.. please... discard this PR
Sorry sorry, sorry...

**Comment by GawainLynch** [comment]
No stress, happens… and it's Friday! :grin:

**Comment by miguelavaqrod** [comment]
Yes... it's time to leave the computer and go for a beer... ;-)

**Comment by GawainLynch** [comment]
Absolutely! About to do the same :-)

**Comment by rarila** [comment]
I recommend two :beers:

**Pull request closed without merging**
