### PR TITLE
.control-label for image, imagelist and textarea (part 2)

### PR DESCRIPTION
**Pull request by Boorj**
please, delete this PR if i did something wrong...

### CODE REVIEW

**Comment by GawainLynch** [comment]
Merged on rebase

**Comment by rarila** [comment]
Here's something going wrong here. There was a reason why the control-label class was not set (can't remember what it was atm) but looking at thIs [code](https://github.com/Boorj/bolt/blob/release/3.0/app/view/twig/_base/_fieldset.twig#L21). So there are two possibilities. Either the code mentioned above has to be changed to always add it or it shouldn't be added manually as whatever reason to just add it to those cases when it is used as inline label is valid.

**Comment by Boorj** [comment]
agree 100%. Let's add that permanently. And I also had that question, asked @GawainLynch in slack.

**Comment by rarila** [comment]
Question is, why you want to add it. Can't check at the moment as I can't access the desktop. But the reason could be that one is a label for a single control and the one liner is morevof a headline for a collection of controls.

Did you run the bootstrap test?

**Pull request closed without merging**
