### PR TITLE
Gender neutral Codeception tests

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by tobias2k** [comment]
The -Guy thing is an existing Codeception convention; if there is
consensus on changing this to a PC term, it's probably best to go with
the kind of naming Codeception seems to be adopting lately, which is
-Tester, not -Person. Personally, I believe -Tester is more meaningful
than -Person, and actually even more truthful in a way (although we're
venturing deep into philosophical terrain here - can we consider an
automated process a "person"?)

On Mon, Feb 16, 2015 at 11:16:39PM -0800, Gawain Lynch wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/bolt/bolt/pull/2847
> 
> -- Commit Summary --
> 
>   * Rename the Codeception TestGuy to TestPerson
>   * Rename the Codeception CodeGuy to CodePerson
>   * Rename the Codeception WebGuy to WebPerson
> 
> -- File Changes --
> 
>     M test/_helpers/CodeHelper.php (2)
>     M test/_helpers/TestHelper.php (2)
>     M test/_helpers/WebHelper.php (4)
>     M test/acceptance.suite.yml (2)
>     M test/acceptance/000-front/000-frontpageCept.php (2)
>     M test/acceptance/100-back-basic/000-loginAsPagesEditorCept.php (2)
>     M test/acceptance/100-back-basic/001-pagesEditorSeesOnlyPagesCept.php (2)
>     M test/acceptance/100-back-basic/010-pagesEditorCanEditPagesCept.php (2)
>     M test/acceptance/100-back-basic/011-pagesEditorCannotEditEntriesCept.php (2)
>     M test/acceptance/100-back-basic/012-pagesEditorCannotPublishPagesCept.php (2)
>     M test/acceptance/100-back-basic/500-loginAsAdminCept.php (2)
>     M test/acceptance/100-back-basic/501-adminSeesAllCategoriesCept.php (2)
>     M test/acceptance/100-back-basic/502-logoutAsAdminCept.php (2)
>     M test/acceptance/100-back-basic/510-createUserAsAdminCept.php (2)
>     M test/acceptance/_bootstrap.php (4)
>     M test/functional.suite.yml (2)
>     M test/unit.suite.yml (2)
> 
> -- Patch Links --
> 
> https://github.com/bolt/bolt/pull/2847.patch
> https://github.com/bolt/bolt/pull/2847.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/pull/2847

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by GawainLynch** [comment]
> The -Guy thing is an existing Codeception convention

I realise that, but it does not make it inclusive nor correct.  Just because one party behaves in an unacceptable fashion doesn't excuse the propagation of that behaviour.

That said, I have no firm opinion on `Tester` versus `Person` with the niggle that it would create a `TestTester` :-P

**Comment by bobdenotter** [comment]
> That said, I have no firm opinion on Tester versus Person

I'd be fine with either. You ~~guys~~ persons decide. :-)

**Comment by GawainLynch** [comment]
Done: s/Person/Tester/

**Comment by bobdenotter** [comment]
This person thanks you.

**Comment by GawainLynch** [comment]
Your choice of gender identification is your own, and those that appreciate inclusion will also (hopefully) appreciate it :+1:

**Pull request merged**
