### PR TITLE
PHPDoc and syntax fixes to Content::getTitleColumnName()

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by CarsonF** [comment]
Why is this happening?? lol

**Comment by GawainLynch** [comment]
Which bit?

**Comment by bobdenotter** [comment]
Ha, still coming to grips with being able to use short array syntax now! ^_^

**Comment by GawainLynch** [comment]
:koala: was busy eating :leaves: and saw nothing :wink:

**Pull request merged**
