### PR TITLE
add translation for taxonomy link

### PR DESCRIPTION
**Pull request by joanlouis**

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm not in favor of this. If you want the name of a taxonomy translated, just translate it in `taxonomy.yml`.

**Comment by joanlouis** [comment]
and how for multi-lingual sites ?

**Comment by bobdenotter** [comment]
You can only set one language at a time, so this will not solve that. Instead, you might find the "labels" extension useful: http://extensions.bolt.cm/view/318f0a8b-973e-11e4-866c-43d66b93a270

**Comment by joanlouis** [comment]
ok.
 I use taxonomy.yml for now. but i don't understand why not use translation in templates.

**Comment by bobdenotter** [comment]
Some of us want us to, and we might eventually. For now, i'm just being the evil dictator, preventing ourselves from losing focus on the "simple" part of the CMS. ^_^

**Comment by joanlouis** [comment]
:+1:

**Pull request closed without merging**
