### PR TITLE
Flush the cache if the Bolt version has changed

### LINKED ISSUE #3182: Invalid cache objects can break upgrade
As pointed out by Netbulae on IRC after updating to 2.1.3

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #3182

### CODE REVIEW

**Comment by bobdenotter** [comment]
Shouldn't we just tie this to the changes in #3129 ?

**Comment by GawainLynch** [comment]
My thought that this case is very lowlevel, fast-path, and provides certain guarantees. Therefore special case. Happy to be over turned though.

**Comment by GawainLynch** [comment]
Oh wait, I think I might have misunderstood your point… pinging you on IRC in 5… 4… 3…

**Comment by bobdenotter** [comment]
Nah, I guess you're right.. This does allow us to remove the "… and flush the cache." from the notice that we set in #3129, though.

**Comment by GawainLynch** [comment]
Yeah, I might append this to do exactly that then.

**Comment by GawainLynch** [comment]
Updated! :tada:

**Comment by bobdenotter** [comment]
Heh. I sort of meant only the "clear the cache" part. The notice itself is a 'feature', to reassure the user: "Hey, we noticed you've update! Good job, old chap. Ta ta!".. something like that. ;-)

**Comment by GawainLynch** [comment]
> Heh. I sort of meant only the "clear the cache" part. The notice itself is a 'feature', to reassure the user: 

Derp derp derp derp… With added derp.

**Comment by GawainLynch** [comment]
Can I also suggest we back port this to `release/2.1` as that is where it is hitting.

**Comment by bobdenotter** [comment]
Merging in, and will cherry-pick into release/2.1

**Pull request merged**
