### PR TITLE
Adding missing .control-label class to fields

### PR DESCRIPTION
**Pull request by Boorj**
Some labels are missing their class..

### CODE REVIEW

**Comment by GawainLynch** [comment]
@Boorj if you want things to go into 3.0 you should target the PRs at the `release/3.0` branch. Zero stress about this one as the person merging will do it manually for you.

**Comment by Boorj** [comment]
no problems, sorry mate.

**Comment by bobdenotter** [comment]
Looks good too! :+1:

**Comment by GawainLynch** [comment]
Merged into `release/3.0`

**Pull request closed without merging**
