### PR TITLE
Add js events to editfile/editcontent ajax saving

### PR DESCRIPTION
**Pull request by SahAssar**
Add js events to allow extensions and custom fields to know about the savestate of content/files. Oh, and 	port #4682 to master.

### CODE REVIEW

**Comment by rarila** [comment]
A few thoughts:

I wonder if ``start.bolt.content.save`` and ``start.bolt.file.save`` would do or is that not precise enough? In other words, can it happen that we save content or a file if we are not in edit mode?

And then I would probably name the gmaps ones ``xxx.bolt.gmaps``(without ``field``) as there is nothing field specific in there. Just a request to load the Google maps api that could also be used elsewhere. 

Name it ``gmapsapi`` instead? I  think ``gmaps`` will do to be short.

Last thing here: shouldn't it be ``start.bolt.gmaps.load``, … to be in line with the other event names?

So we would endup ``status``.``namespace``.``subject``.``verb`` with our custom events.

Hey, I hate designing things that are BC relevant:-)
Opinions!?

**Comment by GawainLynch** [comment]
There is something strange about this PHP… I can't put my finger on it…

**Comment by SahAssar** [comment]
@GawainLynch I found some nice, calming PHP for you to read: http://bit.ly/1ntINPy

**Comment by GawainLynch** [comment]
Oh, I like this one
```php
captial_SCREWYOU_dangit()
```

:wink:

**Comment by SahAssar** [comment]
@rarila I renamed them, your way seems more logical. You mentioned on IRC about going more generic and putting more things into extra parameters, but personally I think that it's better if extension developers have somewhat simple events to listen to and that they don't have to write boilerplate code like
```
$(Bolt).on('start.bolt', function(event, data){
    if(data.type === 'content' && data.action === 'save'){
        /* do stuff here */
    }
});
```
But I'm open to whatever feels like it will work best :) How do you usually do it?

**Comment by rarila** [comment]
@SahAssar you're probably right. It might be shorter to just have longer event names instead lots of conditional code here. But I'm still missing the overall vision inside me here and wonder in what direction this eventing will go in the end. So we probably have to do our best now and simply bite the bitter bc breaking pill in the future if it happens we come to the conclusion that we were wrong.

PS: I still wonder about ``gmap`` vs. ``gmapapi``. Did I tell you that I hate that naming stuff :-)

**Comment by SahAssar** [comment]
@rarila Is there some way that you can think of that gives us the equivalent functionality and that you are more comfortable with?

I went with gmapapi since it only loads that api, it dosen't actually create a "gmap".

**Comment by rarila** [comment]
@SahAssar no, I guess it is ok that way. It's probably the way software debelopment works. You add stuff after stuff and at some point you wonder why you didn't had it done in another way and them shout "refactor" or "rewrite" :smile: 

gmapi: Ok … eh …:bulb: … how about ``gmapi``?

**Comment by jadwigo** [comment]
what's wrong with `googlemapsapi` or something else which is actually telling you what it is without needing to guess

**Comment by rarila** [comment]
@jadwigo we devs like it mysterious, are lazy and serve this code clientside… every byte counts :sunglasses:

**Comment by jadwigo** [comment]
@rarila I know, but http://www.gmapi.com/ exists ...

**Comment by SahAssar** [comment]
Isn't gmapapi pretty unambiguous? Although I have no problem changing it to googlemapsapi if that seems better.

**Comment by jadwigo** [comment]
I would prefer `googlemapsapi` :) just because the provider is `google`, and not `gstar` or anything else that starts with a `g`.

Similarly I would prefer `foursquarelocationapi` over `flocapi` - some extra letters are cheap and figuring out if `f` stands for foursquare or facebook would be annoying.

**Comment by SahAssar** [comment]
@jadwigo Fixed :)

**Comment by rarila** [comment]
Sorry

**Comment by GawainLynch** [comment]
:shipit: and :wrench: later.

**Pull request merged**
