### PR TITLE
Confusing PHPDOC and method name StorageEvent->getContentType()

### PR DESCRIPTION
**Pull request by JarJak**
Added an alias and deprecated old name.

### CODE REVIEW

**Review by GwendolenLynch — CHANGES_REQUESTED** [review]
We're trying to move away from "slug"

**Comment by JarJak** [comment]
@GawainLynch feel free to propose any other name

**Comment by GawainLynch** [comment]
That is still under heavy debate. I am not seeing what problem this solves though.

**Comment by JarJak** [comment]
It improves Developer Expierience

**Comment by GawainLynch** [comment]
> It improves Developer Expierience

That is highly subjective

**Pull request closed without merging**
