### PR TITLE
Fixes ~~two~~ a notice

### PR DESCRIPTION
**Pull request by bobdenotter**
Notice: Undefined index: seo in /xxx/Storage/Field/Type/FieldTypeBase.php on line 97

and:

    Notice: Undefined index: sortorder in /xxx/Storage/Field/Type/TaxonomyType.php on line 201

### CODE REVIEW

**Comment by CarsonF** [comment]
@bobdenotter I think it would be better to validate `sortorder` when `mapping` is initialized, instead of where it is used.

**Comment by GawainLynch** [comment]
Good catch @CarsonF… :+1: 

Also centralising will help with what we're planning for 2.4 config objects and validation.

**Comment by bobdenotter** [comment]
> I think it would be better to validate sortorder when mapping is initialized, instead of where it is used.

Sure thing! Dumb question: Where's that? :-/

**Comment by CarsonF** [comment]
Not sure...maybe @rossriley can point us in the right direction?

**Comment by bobdenotter** [comment]
Rebased, removed the second one (see #4496). Should be GTG now.

**Comment by GawainLynch** [comment]
Hang back on this… @rossriley is looking deeper.

**Comment by bobdenotter** [comment]
*twiddles thumbs patiently* ;-)

**Comment by GawainLynch** [comment]
@bobdenotter just relaying the conversation from IRC here…
```
<rossriley> gawainlynch: i’m pretty sure it’s not a problem now… 
<gawainlynch> rossriley: As in fixed after Bopp PRed?
<rossriley> I just installed the extension, got a notice to update the db and then loaded / 
a page and saved some SEO data and it all got written ok without a notice
<rossriley> that’s on current master
<gawainlynch> Hmm… OK, I'll leave a note for Bopp to re-test then and pull the PR if needed
<rossriley> so, yes I’m not sure if we’ve already sorted it, or I did something different 
to him
```
Can you recheck/retest that you're still getting these notices as we'd prefer to not hide them.

**Comment by bobdenotter** [comment]
I've tested it out, and the other one is not an issue anymore either. Closing this one.

**Pull request closed without merging**
