### PR TITLE
Allow non-strings as query parameters with pager. issue #4109

### PR DESCRIPTION
**Pull request by hugin2005**
Pager doesn't work with array as query parameter. This issue is solved with help of http_build_query().

### CODE REVIEW

**Comment by bobdenotter** [comment]
I had never heard of `http_build_query()`. Thanks! :+1:

**Comment by rarila** [comment]
@bobdenotter Oh, it's rather new, just since pho 5 ;-)

**Comment by hannesl** [comment]
It would be lovely if this got ported to 2.2 – how can I help? I believe the code in question is identical in that branch.

**Comment by bobdenotter** [comment]
It's already backported to 2.2.x.. It'll be in the next release! :-)

**Comment by bobdenotter** [comment]
See: 3853d1c132f12c2806f8237a62c0f4a5756e3a34

**Comment by hannesl** [comment]
Ah, thanks!

**Pull request merged**
