### PR TITLE
Users::token to use csrf provider instead of our own code

### PR DESCRIPTION
**Pull request by CarsonF**
@gawainlynch can this change be applied to `AccessControl` code as well?

### CODE REVIEW

**Comment by bobdenotter** [comment]
Should we also remove this section from `config.yml`? https://github.com/bolt/bolt/blob/master/app/config/config.yml.dist#L331-L342

Or, now that I think about it, this is the part thats' needed for `AccessControl`, right?

**Comment by GawainLynch** [comment]
> Or, now that I think about it, this is the part thats' needed for AccessControl, right?

Currently correct.

**Comment by CarsonF** [comment]
Which is my question :) Should that code be updated as well or am I missing something?

**Comment by GawainLynch** [comment]
The CSRF tokens I don't trust for authentication purposes myself. One of the things I wanted to achieve in 2.3/2.4 was the breaking out of `AccessControl` as much as possible to make a rip-and-replace of the authentication stack easy in v3.

**Comment by CarsonF** [comment]
Fine with me. Let's ship this :shipit:

**Comment by bobdenotter** [comment]
Whoop!

**Pull request merged**
