### PR TITLE
Fixed translations messages nl_NL

### PR DESCRIPTION
**Pull request by sintemaa**
Fixed some broken special chars caused by earlier update & added some more translations

### CODE REVIEW

**Comment by sintemaa** [comment]
Hmm this branching is all new to me. I don't understand why it's showing those other commits that were already merged in another PR. Shoudl I just delete my Forkl & create a new for every PR I make?

**Comment by rarila** [comment]
Hmm, not a new fork, just a new branch for every PR. Don't know what are you doing, but there's certainly something messed up here. Perhaps our git experts can help.

**Comment by rarila** [comment]
It's probably because your master branch is behind bolt:master? Just an idea.

**Comment by sintemaa** [comment]
I'm tried to follow the instructions on Github help to bring my master in sync with bol:master before brnaching, but maybe I did something wrong still?

**Comment by GawainLynch** [comment]
OK,  I am going to close this PR and what follows below is what you need to do to correct your mistakes.

The most important concept to grasp is to never commit any of your changes to `master`… but don't stress, we've all done it :wink: 

OK, this assumes you have command line git installed and ssh set up.

First you change into your bolt source directory and make sure your remotes are set up correctly:
```bash
cd bolt
git remote set-url origin git@github.com:sintemaa/bolt.git
git remote add upstream https://github.com/bolt/bolt.git
git fetch --all
```
Next, we're going to set up a temporary branch so that you can easily interrogate your existing work:
```
git checkout -b saved-branch master
```
Now, we'll get a list of the last 10 commit IDs and messages
```
git log --oneline | head 
```
The first line should look like this, take note of the hash in the first column (this time, it's the only one you care about):
```
072e521 Fixed some broken special chars caused by earlier update & added some more translations
```
Now we're going to switch back to *your* `master` branch and reset it to be in line with Bolt's master:
```
git checkout master
git reset --hard upstream/master
```
Now we're going to create a working branch, with the exception of `hotfix/nl-translations` this is the same way you're going to create each new branch you want to use for a single PR. After the branch is pushed to your `origin` and merged, the branch can be removed.
```
git checkout -b hotfix/nl-translations master
```
You're now in your new working branch.

OK, we're now going to grab that one commit that we need:
```
git cherry-pick 072e521
```
Finally we push it to your GitHub repo and create a new branch for you to use in the PR:
```
git push --set-upstream origin hotfix/nl-translations
```
Once that is all done:
```
git checkout master
```

**Pull request closed without merging**
