### PR TITLE
Prevent Composer from sneaking in any `v2.7.0` Symfony components into Bolt 2.2

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by CarsonF** [comment]
You mind as well remove `symfony/locale` while you're at it :)

**Comment by bobdenotter** [comment]
@CarsonF Good catch, thanks.

**Comment by CarsonF** [comment]
Let's do this! :+1:

**Comment by GawainLynch** [comment]
/me hangs his head in shame… I thought I caught this previously… apologies for missing this.

**Pull request merged**
