### PR TITLE
Fix grammar and typos in contributing.md

### PR DESCRIPTION
**Pull request by Chris92de**
Noticed these and thought this would be an easy first contribution to Bolt from my side ;)

Totally related: Is there even a single person who likes brown M&M's? I don't know any.

### CODE REVIEW

**Comment by GawainLynch** [comment]
:+1:

**Comment by GawainLynch** [comment]
I just don't get the whole debate… they suck… simple :grinning:

**Comment by bobdenotter** [comment]
Pfft, we shouldn't let the Dutch guy write any docs! This is what you get! ;-)

Thanks, @Chris92de!

**Comment by Chris92de** [comment]
@bobdenotter You're welcome ;-)

**Comment by GawainLynch** [comment]
The German person correcting the Dutch person with the Australian person doing the merge… Combined we either helped invent, or redefine, the language! :wink:

**Comment by rossriley** [comment]
I think you should all leave the language alone, it was fine before you all started messing.

**Pull request merged**
