### PR TITLE
trimText shouldn't just trim the text, it should also trim whitespace at...

### PR DESCRIPTION
**Pull request by bobdenotter**
... the beginning and end.

See screenshot:

screenshot 2015-02-22 15 31 50

### CODE REVIEW

**Comment by GawainLynch** [comment]
Ping @rarila... We need to do something about this person... He is taking our whitespace form us!

**Comment by GawainLynch** [comment]
P.S. I hate iPads

**Comment by bobdenotter** [comment]
Have you had a glass of wine or two, @GawainLynch? :wine_glass: :wink:

**Comment by GawainLynch** [comment]
Hehe… Not telling… More the problem was I couldn't do the merge from the iPad and also couldn't get the energy up to walk downstairs and press the green button.

**Comment by rarila** [comment]
@GawainLynch 
```
      |-----------------------------|
      | WE WANT OUR WHITESPACE BACK |
      |-----------------------------|
      |                             |
   \o/|                             |\o
    O                                 O\
   / \                               / \

```

**Comment by rossriley** [comment]
```
      |------------------------------------------|
      | Liberté, Egalité, Fraternité, Whitespace |
      |------------------------------------------|
      |                             |
   \o/|                             |\o
    O                                 O\
   / \                               / \

```

**Pull request merged**
