### PR TITLE
Race around the request …

### LINKED ISSUE #5733: "Publish on .." seems broken.
If you set a publication date on an entry, it gets wiped after publishing. 

Details
-------

 - Relevant Bolt Version: [ master ]

Reproduction
------------

Set the publication date to something in the near future:

screen shot 2016-09-05 at 20 40 44

Get an exception, when that future date happens: 

screen shot 2016-09-05 at 20 41 21

Return to the entry, to see it's gone: 

screen shot 2016-09-05 at 20 41 40

### LINKED ISSUE #5842: Fatal error because cache file doesn't exist.
- Relevant Bolt Version: [ 3.2 | master ]

I get this error, when going to login:

screen shot 2016-09-30 at 14 52 35

Full text of trace: 

----------

Bolt
Uncaught Fatal Error:

Details

UnexpectedValueException in FileCache.php line 271

RecursiveDirectoryIterator::__construct(/Users/bobdenotter/Sites/bolt-origin/app/cache/development/data): failed to open dir: No such file or directory

Stack trace

 \RecursiveDirectoryIterator:: __construct()
[root]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php # 271
 Doctrine\Common\Cache\FileCache:: getIterator()
[root]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php # 175
 Doctrine\Common\Cache\FileCache:: doFlush()
[root]/src/Cache.php # 68
 Bolt\Cache:: doFlush()
[root]/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php # 156
 Doctrine\Common\Cache\CacheProvider:: flushAll()
[root]/src/Storage/Database/Connection.php # 76
 Bolt\Storage\Database\Connection:: executeUpdate()
[root]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php # 208
 Doctrine\DBAL\Query\QueryBuilder:: execute()
[root]/src/Storage/QuerySet.php # 46
 Bolt\Storage\QuerySet:: execute()
[root]/src/Storage/Repository.php # 414
 Bolt\Storage\Repository:: update()
[root]/src/Storage/Repository/UsersRepository.php # 226
 Bolt\Storage\Repository\UsersRepository:: update()
[root]/src/Storage/Repository.php # 357
 Bolt\Storage\Repository:: save()
[root]/src/Storage/Repository/UsersRepository.php # 214
 Bolt\Storage\Repository\UsersRepository:: save()
[root]/src/AccessControl/Login.php # 264
 Bolt\AccessControl\Login:: updateUserLogin()
[root]/src/AccessControl/Login.php # 212
 Bolt\AccessControl\Login:: loginFinish()
[root]/src/AccessControl/Login.php # 134
 Bolt\AccessControl\Login:: loginCheckPassword()
[root]/src/AccessControl/Login.php # 72
 Bolt\AccessControl\Login:: login()
[root]/src/Controller/Backend/Authentication.php # 152
 Bolt\Controller\Backend\Authentication:: handlePostLogin()
[root]/src/Controller/Backend/Authentication.php # 81
 Bolt\Controller\Backend\Authentication:: postLogin()
#
 call_user_func_array()
[root]/vendor/symfony/http-kernel/HttpKernel.php # 144
 Symfony\Component\HttpKernel\HttpKernel:: handleRaw()
[root]/vendor/symfony/http-kernel/HttpKernel.php # 64
 Symfony\Component\HttpKernel\HttpKernel:: handle()
[root]/vendor/silex/silex/src/Silex/Application.php # 586
 Silex\Application:: handle()
[root]/vendor/silex/silex/src/Silex/Application.php # 563
 Silex\Application:: run()
[root]/src/Application.php # 88
 Bolt\Application:: run()
[root]/index.php # 14

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #5842 — Fatal error because cache file doesn't exist
Fixes #5733 — "Publish on .." seems broken. 

So it turns out we just had a race … and nobody won.

### CODE REVIEW

**Comment by bobdenotter** [comment]
giphy

(I bet @CarsonF will have no idea about this gif. ;-) )

**Comment by CarsonF** [comment]
No idea lol

**Comment by GawainLynch** [comment]
https://www.youtube.com/watch?v=Y4QbJRAWvRU

**Comment by bobdenotter** [comment]
Whoop whoop! 🏎

**Pull request merged**
