### PR TITLE
Fixed bug with FR translation

### PR DESCRIPTION
**Pull request by nnussbaum**
On the page : bolt/extend
Unescaped quote in a translation hurt the javascript.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Thanks for bringing this to our attention. I think we had better fix this by escaping the string in the source code though. That way it'll be 'fixed' for other languages too.

**Comment by nnussbaum** [comment]
That would be a better idea :)

**Comment by nnussbaum** [comment]
As translations are enclosed in double quotes, enclosing the translations results in double quotes too makes better sense to me

**Comment by bobdenotter** [comment]
@nnussbaum Thanks for this fix! 👍 

I'll merge this in, and add a ninja-tweak to add an escape filter (`|e`) to it!

**Pull request merged**
