### PR TITLE
Add a brief quick start to the asset build README.md

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
We can merge this in, but this file is eventually going to be phased out, in favor of actual documentation in the docs. :-)

https://github.com/bolt/docs/pull/507

**Comment by GawainLynch** [comment]
Yeah … meant for "Gawain & Bob" right now.

**Comment by bobdenotter** [comment]
👍

**Comment by SahAssar** [comment]
I'm late to the party, but does the non-local grunt work for you? as in `npm run-script grunt` instead of `grunt`? Cause it'd be nice to "require" as few global dependencies as possible.

**Comment by GawainLynch** [comment]
Do not get me started :wink: 

Seriously … for sure … as mentioned, this is for the Team Bob & Gawain for now, so that we have a quick copy/pasta solution that we don't have to go digging to find for now.

I have our JS now loading 100% uncompiled … for me, that's what I need to work on JavaS-crap

**Pull request merged**
