### PR TITLE
[BUG] Wrong sorting in ArrayHandler::orderHelper() in v3

### PR DESCRIPTION
**Pull request by rixbeck**
Fix for #5257 in master branch

### CODE REVIEW

**Comment by CarsonF** [comment]
You know `Content` class implements `ArrayAccess`, right?

**Comment by GawainLynch** [comment]
@rixbeck I am unsure (and just haven't had the time to follow up :disappointed:) how you've hit this problem, and how to reproduce it.

Any chance you can provide a test case?

**Comment by GawainLynch** [comment]
See https://github.com/bolt/bolt/pull/5257#issuecomment-267757987

**Comment by SahAssar** [comment]
Closing this one as it has been inactive for a while and it seems (to me) like PR's are better handled fresh. If/when this is ready please feel free to reopen this one and rebase&retarget it or open a new PR :)

**Pull request closed without merging**
