### PR TITLE
Fixes #3473

### LINKED ISSUE #3473: Bug: Reordering images in an ImageList
Using the default page template in 2.1.8 I have added an ImageList field. When I have uploaded n number of images I want to reorder them. This functionality appears to be supported through drag and drop, however, when I drag and drop an image the page moves around too much to make the functionality useful.

This problem occurs on OSX, Chrome.

### PR DESCRIPTION
**Pull request by rarila**
Ok, let's try in 2.3 and see if something explodes :boom:

Fixes #3473

### CODE REVIEW

**Comment by rarila** [comment]
Cool, see the issue numbers! :-)

**Comment by GawainLynch** [comment]
Whoa… Calling #1555 on this!

**Comment by bobdenotter** [comment]
Well, unlike #1555, this actually fixes a bug. :-)

**Comment by GawainLynch** [comment]
OK then, don't blame me if kittens are crying in a few minutes!

**Comment by rarila** [comment]
:crying_cat_face:

**Comment by Pinpickle** [comment]
@rarila can we have a 2.2 fix for this pleeease? :bouquet:

**Pull request merged**
