### PR TITLE
The return of /app/src - sources for css and js now live there

### PR DESCRIPTION
**Pull request by rarila**
- Move stuff to generate css/js to ``/app/src/`` as described in #3065
- Fix: css sourcemaps are now generated again

TODO:
… no that is called different now ;-)
 INSIGHT:

- @bobdenotter The dist script might have to be adjusted
- @rossriley Anything to change for the composer install?

### Changelog

* CSS/JS sources and generation scripts are now in ``/app/src/``
* CSS sourcemaps are now generated again

### CODE REVIEW

**Comment by GawainLynch** [comment]
Sending this in so I can re-do my stuff :+1: :shipit:

**Comment by rarila** [comment]
@GawainLynch Happy redoing!

**Comment by GawainLynch** [comment]
@bobdenotter added a PR to https://github.com/bolt/bolt-distribution/pull/14

**Comment by rarila** [comment]
@bobdenotter Merged it. You have a free day today. Go out and enjoy the sun :-)

**Pull request merged**
