### PR TITLE
CKEditor update

### PR DESCRIPTION
**Pull request by rarila**
- CKEditor update to v4.4.7
- CKEditor can now just be downloaded and put into ``/view/lib/ckeditor``. Then ``grunt updateLib`` and all things in the ckeditor source archive are corrected (removing of unneeded folders, correcting BOM and CRLF issues)
- Afterwards needed files are copied to locations in ``view/js`` and ``view/css``…
- CKEditor locale files now live nicely in ``view/js/locale/ckeditor``

@GawainLynch Don't forget npm _install_ ;-)

TODO:
``view/css/ckeditor-contents.css`` and ``view/css/ckeditor.css`` probably can be copied together in one file to save another request. It has to be tested, if locale files can be preloded like those of moments/datepicker.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Is this one done, or do you want to add the "@todo" to this PR? :-)

**Comment by rarila** [comment]
Done.

**Comment by rarila** [comment]
This was more of COULDBEDONE :-)

**Comment by rarila** [comment]
A one line comment was removed, that caused that merge conflict :-(

**Comment by bobdenotter** [comment]
All aboard the merge train! :train: :train: :train: :train:

**Pull request merged**
