### PR TITLE
Expand the list of acceptable HTTP return code for PackageManager::ping() in line with RFC 2616

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
No `418`?

**Comment by GawainLynch** [comment]
Oh… my… how on Earth did I **miss** that!

**Comment by CarsonF** [comment]
Why not `$response->isSuccessful()`?

**Comment by GawainLynch** [comment]
Yeah, good idea. I blame BoltCamp where that was originally written.

**Comment by GawainLynch** [comment]
In case you're also thinking of Guzzle, [this is why](https://github.com/guzzle/guzzle/blob/v3.8.1/src/Guzzle/Http/Message/Response.php).

**Comment by CarsonF** [comment]
> In case you're also thinking of Guzzle, this is why.

You mean `isSuccessful` doesn't allow these - 300, 301, 302, 307, 410?

**Comment by GawainLynch** [comment]
```php
    public function isSuccessful()
    {
        return ($this->statusCode >= 200 && $this->statusCode < 300) || $this->statusCode == 304;
    }
```

**Comment by CarsonF** [comment]
Why is this a problem? 

301 and 302 will never be returned because Guzzle follows redirects. 
When would 300, 307, 410 be returned? And why would that be a positive thing?

**Comment by GawainLynch** [comment]
If you can explain to me why at the time we originally did this we were getting weird response codes I can give you the answer. Past that, what is your point?

**Comment by GawainLynch** [comment]
Oh and yes, we were getting 302 directly back from Guzzle.

**Comment by CarsonF** [comment]
Hmm that's weird you were getting 302, maybe redirects were turned off. My point is let's not reinvented the wheel here. 

How about `!$response->isError`? That would allow 3xx responses.

**Comment by GawainLynch** [comment]
> How about `!$response->isError?` That would allow 3xx responses.

Sure, put it on your 2.2 TODO list.

**Comment by CarsonF** [comment]
:disappointed:

**Comment by GawainLynch** [comment]
https://twitter.com/erikaheidi/status/573161393362481152

**Comment by CarsonF** [comment]
That doesn't apply. It's not a different wheel, it's duplicated code. 

Fine, I'll change it in 2.2.

**Comment by GawainLynch** [comment]
> My point is let's not reinvented the wheel here.

...

> That doesn't apply. It's not a different wheel, it's duplicated code.

That has been there since 2.0-dev in an attempt to fix shit that made no sense as to why people were getting problems and it solved a fucking problem…

**Comment by CarsonF** [comment]
Thanks for finding/fixing the problem. Sorry for being difficult :/

**Comment by bobdenotter** [comment]
:+1:

**Pull request merged**
