### PR TITLE
Refactor menu from twig

### PR DESCRIPTION
**Pull request by cooperaj**
Pulled the menu code out of TwigExtension so that I can use it as part of a breadcrumbs extension.

It now loads as a ServiceProvider giving access to the menu array wherever you might need.

### CODE REVIEW

**Comment by GDmac** [comment]
small question, this is front-end menu, yes? 
to distinguish it from other possible menus (backend, chinese restaurant), 
maybe have a little less generic name.

**Comment by GawainLynch** [comment]
We had a quick chat about this from a namespace PoV on IRC just now… 

Feeling is roughly that the namespaced classes should probably be along the lines of `Bolt\Helper\Menu` and `Bolt\Helper\MenuBuilder`… We're starting to explode with directories in `src/`

@GDmac specifically what are you thinking mate?

Other than that, LGTM…

**Comment by bobdenotter** [comment]
With Gawain's addition, i'm all :+1:.

**Comment by rossriley** [comment]
I'll have number 81 with prawn crackers

**Comment by GawainLynch** [comment]
prawn_cracker_with_black_pepper

**Comment by cooperaj** [comment]
In order to keep the helper directory under control is it worth keeping
menubuilder under menu?

**Comment by bobdenotter** [comment]
Looks good to me! Thanks, Adam!

**Pull request merged**
