### PR TITLE
Move tabgroups generation/logic into controller

### PR DESCRIPTION
**Pull request by rarila**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Hehe… I see what you're doing there :stuck_out_tongue_winking_eye:

**Comment by rarila** [comment]
@GawainLynch I don't :see_no_evil: – what do you see?

**Comment by GawainLynch** [comment]
:snail: :eyes:

**Comment by rarila** [comment]
Slugs?

**Comment by GawainLynch** [comment]
> @GawainLynch I don't :see_no_evil: – what do you see?

I see snails…

**Comment by rarila** [comment]
Instead of :camel:?

**Comment by GawainLynch** [comment]
A :camel: is just a :horse: designed by committee

**Comment by rarila** [comment]
If there were :smiley_cat::pouting_cat::kissing_cat::smirk_cat: instead of :camel: @bobdenotter would have merged this PR already .

**Comment by bobdenotter** [comment]
2789604490_066dd1c786_b

**Comment by bobdenotter** [comment]
@rarila Could you do a merge upstream?

**Comment by rarila** [comment]
@bobdenotter yep

**Comment by rarila** [comment]
@bobdenotter done!

**Comment by rarila** [comment]
Everyone sleeps… let's do a selfie :-)

**Pull request merged**
