### PR TITLE
Add a copy of the MIT license

### PR DESCRIPTION
**Pull request by Calinou**
It is good practice to add a copy of the license to the repository.

### CODE REVIEW

**Comment by bobdenotter** [comment]
I wouldn't be against this.. It's not like we _hide_ the fat that we're MIT licensed, but it wouldn't hurt to make it more explicit.

@GawainLynch, thoughts?

**Comment by GawainLynch** [comment]
Well, we're MIT licensed… So it is not required, as that is a free-for-all license that simply serves the purpose of creating a limited liability for the copyright holders… It is simply a point of avoiding ambiguity that has no solid legal precedent… Copyright law is the important part here, not the licence… But IANAL.

That said, apart from a CDO hit over root litter, no objections :+1:

**Comment by GawainLynch** [comment]
Just to add to this discussion, there is already a licence file in [`app/LICENSE.txt`](https://github.com/bolt/bolt/blob/master/app/LICENSE.txt) that could use some attention (read: line breaks) too.

**Comment by bobdenotter** [comment]
In the root is better, I think. I'd say we merge this in, and fix the link in our 'about' page as well as remove the one from `app/`.

**Comment by GawainLynch** [comment]
:+1:

**Comment by bobdenotter** [comment]
Top notch!

**Pull request merged**
