### PR TITLE
[3.4] Select2 4.0.4

### PR DESCRIPTION
**Pull request by GawainLynch**
Select2 4.0.4 was released late last month, and given nobody else got to this **and** it really irks me to be using a 30 month old release of anything with JavaScrap in it … :coffee: task! 

Given we're about to minor, and we're in beta, now seems like a time to take advantage and all.

@bobdenotter I *think* this doesn't have the problem we were seeing, but if it does please just close this and we'll `<insert rant here>`

### CODE REVIEW

**Comment by bobdenotter** [comment]
We had it locked on 4.0.0, because 4.0.3 didn't work in IE. It was utterly broken. I'll spin up the ol' Internet Explorer today, and see if they've gotten their heads out of their asses and fixed it.

**Comment by GawainLynch** [comment]
> IE ~. It was~ is utterly broken

Fixed the text for you :stuck_out_tongue_winking_eye:

**Comment by bobdenotter** [comment]
TBH, IE 11 isn't nearly as bad as what came before, and Edge is fairly decent. Don't care to much about the browser's UI, but no real problems with the rendering engine.

**Comment by GawainLynch** [comment]
Yeah, in my mind Edge !== IE … and regardless, the whole thing is just low hanging pineapples to make fun of irrespective of fact.

**Comment by bobdenotter** [comment]
For reference: #5676

**Comment by bobdenotter** [comment]
Well, that was a morning well spent. 

Unfortunately, the 4.0.4 version does not resolve the problem we have on IE 10 and IE 11 with the omnisearch. 

screen shot 2017-10-03 at 12 32 08

**Comment by GawainLynch** [comment]
C'est la vie

**Comment by bobdenotter** [comment]
Let's make sure we get rid of it in V4. ;-)

**Pull request closed without merging**
