### PR TITLE
Fix for #3992 Invalid messages yaml for pt translation 

### LINKED ISSUE #3992: Invalid messages yaml for pt translation
There is a error in the [messages.pt.yml](../tree/master/app/resources/translations/pt/messages.pt.yml) file at line 225.
You can check this out [here](http://yaml-online-parser.appspot.com/?url=http%3A%2F%2Fraw.githubusercontent.com%2Fbolt%2Fbolt%2Fmaster%2Fapp%2Fresources%2Ftranslations%2Fpt%2Fmessages.pt.yml)

### PR DESCRIPTION
**Pull request by leocavalcante**
This PR fixes #3992 issue, it just corrects the key name.

### CODE REVIEW

**Comment by GawainLynch** [comment]
Close, but it should move to line 456 as:
```yaml
page.extend.pagetitle: "Estender %BOLTNAME%"
```

**Comment by GawainLynch** [comment]
Tudo bem!

**Comment by leocavalcante** [comment]
Glad to help! :smiley:

**Comment by GawainLynch** [comment]
Muito obrigado! :grin:

**Pull request merged**
