### PR TITLE
Extremely minor comment tweaks

### PR DESCRIPTION
**Pull request by jkazimir**
Fix 'JavaScipt' typo, and change initialise to initialize in order to be consistent with the majority of the file, as well as with the method naming.

### CODE REVIEW

**Comment by GawainLynch** [comment]
You can't speak English?

"initialize" isn't a word.

**Comment by jkazimir** [comment]
I know you and the koala's want the 'z' to be upside-down and turn into an 's', but if you look at the method name… http://beta.merriam-webster.com/dictionary/initialize :P

**Comment by GawainLynch** [comment]
Be rather careful with quoting Webster… his reason for canonicalising what became the US dialect was based on racism toward the English.

**Comment by SahAssar** [comment]
Webster's dictionary defines wedding as "the fusing of two metals with a hot torch." Well, you know something? I think you guys are two medals, gold medals.

**Comment by GawainLynch** [comment]
[Erm](http://beta.merriam-webster.com/dictionary/wedding)… You mean **[welding](http://beta.merriam-webster.com/dictionary/welding)**, right?

**Comment by SahAssar** [comment]
...and that's the last time I make a parks and rec reference around here :D

**Comment by rarila** [comment]
I like to suggest a compromise (compromize, if one likes).

Lets simply use [sz](https://en.m.wikipedia.org/wiki/ß) to make both happy: ``initialiße``

**Pull request merged**
