### PR TITLE
Hotfixing mailer handling

### PR DESCRIPTION
**Pull request by GawainLynch**
I am submitting this for 2.1 — @rossriley style @rossriley style

What it adds in existing codepaths is close to zero and is foundational for what we want to attempt in 2.2. It also allows "in the know" people to test their email set up ahead of #2863's additional fixes to address the full range of problems.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Haha, i still love that image.

**Comment by bobdenotter** [comment]
Whoop, merging in!

**Comment by GawainLynch** [comment]
That image is just one of my favourite PR responses that you've ever done @bobdenotter

**Comment by GDmac** [comment]
I'll just leave this here - the down-under version...
oh-you-ausie

**Pull request merged**
