### PR TITLE
[Travis] Composer parallel install 

### PR DESCRIPTION
**Pull request by GawainLynch**
This adds a significant speed boost to building our Travis environment for testing

### CODE REVIEW

**Comment by GawainLynch** [comment]
Example being:
* [Old run](https://travis-ci.org/bolt/bolt/jobs/106546483) ~190 seconds
* [This run](https://travis-ci.org/bolt/bolt/jobs/106662585) ~50 seconds

**Comment by PhillippOhlandt** [comment]
:+1:

**Comment by rarila** [comment]
@GawainLynch Can we require that multiple times ;-)

**Comment by GawainLynch** [comment]
> Can we require that multiple times 

Jokes aside, it globally installs in the Travis environment, so all install/require/create-project calls to `composer` are sped up.

**Comment by rarila** [comment]
``+ + + f a k e t i c k e r + + +  c o f f e e + p r o d u c e r s + f e a r + m a s s i v e + l o s s + i n + s a l e s + + +``

**Comment by bobdenotter** [comment]
Whoop!

**Pull request merged**
