### PR TITLE
[3.5] Twig exception request santitisation handling

### LINKED ISSUE #7175: [bug]  error when missing 'preview' route
I'm getting an error if i'm missing `preview` route:
image

When i add `preview: ...` to my routing.yml - all becomes fine.

> version is 3.4.0

### LINKED ISSUE #7540: Nested arrays in RequestSanitiser cause ContextErrorException
When you suddenly delete any required route from `routing.yml` (like `'homepage'`), on the login page you get a non-informative error:
image
When you put routes back - it works ok. This refers to #7175 . 

1. Can we detect those missing required routes and show more informative error?
2. Can we make a fallback for `homepage`, if those pages are missing? And, probably, show warning. Actually, those routes are necessary only for generating urls. It even doesn't need for controller action to exist. Only mapping `routeName => path`. Sooooo... we can make fallbacks to allow people to exist without those unused routes.

### PR DESCRIPTION
**Pull request by GwendolenLynch**
- Handle nested maps & indexed arrays in RequestSanitiser
- [Tests] Broaden RequestSanitiser tests to cover more data types

Fixes #7540
Closes #7543
Closes #7175

### CODE REVIEW

**Review by rossriley — APPROVED** [review]

**Comment by Boorj** [comment]
nice)  +7 lines of code && +over5000 lines of tests ;) Great job, @GawainLynch !

By the way, i don't think, that it closes #7175 .. ) There was a conversation about fallback for missing `'preview'` route in `routing.yml`

**Comment by Boorj** [comment]
aaaand, i don't think, that it closes #7175 .. )

**Comment by GwendolenLynch** [comment]
> By the way, i don't think, that it closes 7175 .. ) There was a conversation about fallback for missing 'preview' route in routing.yml

For the purposes of tracking what I need to, it does. What is requested isn't coming to v3 for stated reasons.

**Review by bobdenotter — APPROVED** [review]
Looks good to me, as well. 

As for the edge-case @Boorj mentions: I'm also of the opinion that if you modify the routes that are marked "Edit these at your own risk". :-)

Let's :shipit:

**Comment by Boorj** [comment]
I'm of the opinion : if you create a refrigerator and put a bottle of poison with a sign ’you'll probably be poisoned’ in each one, be ready that someone will be poisoned. 'routing.yml' provides convenient way to define routes, and nobody loves tons of garbage there. 

Predefined routes should have a fallback, with a possibility to override them in `routing.yml`. It's a **consistent behavior**, since every Extension has `getDefaultConfig()`, which is overridden by `extension.config.yml`. 

### But...
@bobdenotter  told that Bolt 4 will be using symfony 4, and it will have another routing. So i'm ok with that.

yeah, let's shipit

**Pull request merged**
