### PR TITLE
Change order that options are added in SessionServiceProvider

### PR DESCRIPTION
**Pull request by dwolfhub**
Change order that options are added in SessionServiceProvider to allow custom options

Fixes: #5534

### CODE REVIEW

**Comment by GawainLynch** [comment]
@dwolfhub I am not sure this is going to do anything, as `$app['session.options']` is (currently) hard coded as an empty array, so the `->add()` is just going to do an `array_replace()` affecting matching values

@CarsonF can you remember the intention here, i.e. is `$app['session.options']` supposed to be a catch-all bucket, i.e. ultimately being able to override previously set properties from `$app['session.storage.options']` & friends?

**Comment by CarsonF** [comment]
Commented on #5534 

```php
if (isset($app['session.storage.options'])) {
  $options->add($app['session.storage.options']);
}
```
This was an attempt to maintain BC, it really shouldn't be used going forward.

**Comment by GawainLynch** [comment]
@CarsonF assigning you, but I'll co-sponsor this one with you if you need.

**Comment by dwolfhub** [comment]
I'm gonna close this one and open another one for feedback.

Thanks.

**Pull request closed without merging**
