### PR TITLE
Never add extra jQueries on the backend.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Computer says "no":
```html
There was 1 failure:
1) Bolt\Tests\Extensions\ExtensionsProviderTest::testAddJquery
Failed asserting that 
'<html>
<head>
<meta charset="utf-8" />
<link rel="stylesheet" href="existing.css" media="screen">
	<meta name="test-snippet" />
</head>
<body>
<script src="existing.js"></script>
</body>
</html>' 
contains "js/jquery".
```

**Comment by bobdenotter** [comment]
Then the test is wrong, because it apparently assumes it's in "backend" :-)

**Comment by GawainLynch** [comment]
No argument… But the test needs updating or we'll all have b0rked results and :crying_cat_face:

**Comment by bobdenotter** [comment]
Surely. I'll fix the tests! :-)

**Comment by GawainLynch** [comment]
Oh… look… for you the gnomes fix this stuff… for me they break it!

@rossriley can you sanity check this now please?

**Comment by GawainLynch** [comment]
Hey, I just noticed… The Travis build for the additional commit on this was [5150](https://travis-ci.org/bolt/bolt/builds/54924631)… Ohh that's what dreams are made of!

…no M&Ms were harmed in the making of this PR.

**Comment by bobdenotter** [comment]
/me makes a mental note to cherry-pick this into release/2.1, once this is merged.

**Comment by bobdenotter** [comment]
Like singing on my own birthday: Merging my own PR! :cake:

**Comment by GawainLynch** [comment]
I guess if I've checked, and added to it, then you've checked it… that count… failing that… Look :cat: :cat: :cat: :cat:

**Pull request merged**
