### PR TITLE
Refactor Wars Episode VII: The Extension Awakens

### LINKED ISSUE #4556: [PSA] Upcoming v3 extension breakage
### Status

During the development meeting in 1 December, it was agreed to bump the major version of Bolt for the next release, originally planned to be v2.3.0.

As a consequence, there is a dependency on introducing some breaking changes to extensions, as outlined in the [Bolt Version Roadmap Changes](https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes) discussion on the forums.

While **most** things will still work for v2 extensions in v3, there will be a number of breaking changes, mostly around dropping support for using request objects out of cycle. The main impact will be felt in what will work in the extension's `initialize()` function, for example (but not limited to):

* $app['users']
* $app['session']
* Adding assets (CSS, JavaScript, widgets)

### Upcoming Changes

There has been non-stop development on several branches (mostly by myself & @CarsonF) since the 25 November development meeting that all link into this, specifically the filesystem updates to properly support remote filesystems, and the new extension layout branch with the foundational changes for what will be v3 & v4 extensions. Our main focus is to try and make the transition as smooth as possible for users.

We are looking to optimise the loading of extensions, the flexibility and power of extensions… and add a dose of awesome along the way. :+1:

To that end, it would be good for core developers to start to thinking about transitioning their extensions **once** the updated changes land.

### Immediate Transition Period

The currently documented constraint for extensions is:

```json
    "require": {
        "bolt/bolt": ">=2.0,<3.0"
    }
```

This should remain in place for the time being. Should you need to test extensions/sites in the short term, clone the extension into a local extension.

```
mkdir -p extensions/local/authorname/
cd extensions/local/authorname/
git clone https://github.com/GawainLynch/bolt-extension-clippy.git
```

### PR DESCRIPTION
**Pull request by GawainLynch**
*It is a dark time under the First Bootstrap Order, and 
LocalExtensionWalker has gone missing.*

*There is a disturbance in the force brought about by 
KyloRuntimeException, as many are misunderstanding the 
true nature of the application bootstrapping.*

*In an effort to restore balance to the force, and 
prevent KyloRuntimeException from being thrown, 
Princess Gawain looks to seek out LocalExtensionWalker.*

*To avoid detection in these efforts, init.php must be 
dropped where only the appropriate data is included in 
composer.bb8, which must be delivered to the resistance.*

*George regains control of the script and the Gungans return
in full force. Jar Jar is confirmed not to be a Sith. Dark
times indeed…*

## Background

So this is the initial PR of what *should* be the stable API for Bolt v3 for extensions, as described in the RFC #4596

#### WARNING 1

The `"files": [ "init.php" ]` section **must** be removed from the `"autoload"` section of an extension's `composer.json` file.

#### WARNING 2

Core team: Please do not start porting **other people's** extensions yet, as things *may* have to change slightly. Obviously "go for broke"  on your own :grin:

#### WARNING 3

Things have moved… Things have changed. More documentation to follow, but what is here shouldn't be just glanced over. :grin:

## Extension Loading Class File

```php
namespace Bolt\Extension\Hello\World;

use Bolt\Extension\SimpleExtension;

/**
 * An extension for Bolt to show "Hello, World!" 
 *
 * @author Kenny Koala <kenny@dropbear.com.au>
 */
class HelloWorldExtension extends SimpleExtension
{
    /**
     * {@inheritdoc}
     */
    protected function registerTwigFunctions()
    {
        return [
            'helloworld' => 'callbackHelloworld',
        ];
    }

    /**
     * Twig callback function.
     * 
     * @return string
     */
    public function callbackHelloworld()
    {
        return "Hello, World!" ;
    }
}
```
#### Notes:

The `getName()` function **must** be removed.

Optionally it can be renamed to `getDisplayName()` when a non standard name is desired to be displayed in the admin UI `Extend` page

## Further Reading

Once this has landed, and during stablisation, we'll start on the documentation that will land on https://docs.bolt.cm 

Until that time, the function helpers can best be examined in `Bolt\Extension` classes, specifically 
* `SimpleExtension`

…and the traits:
* `AssetTrait`
* `ConfigTrait`
* `ControllerMountTrait`
* `ControllerTrait`
* `MenuTrait`
* `NutTrait`
* `TwigTrait`

See RFC #4596 for more details

## Composer JSON File (`composer.json`)

An simple example of an v3 extension's `composer.json` file would look like
```json
{
    "name": "hello/world",
    "description": "Programming 101",
    "type": "bolt-extension",
    "keywords": ["hello", "world"],
    "require": {
        "bolt/bolt": "^3.0"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Kenny Koala",
            "email": "kenny@dropbear.com.au"
        }
    ],
    "autoload": {
        "psr-4": {
            "Bolt\\Extension\\Hello\\World\\": "src"
        }
    },
    "extra": {
        "bolt-asset": "web",
        "bolt-class": "Bolt\\Extension\\Hello\\World\\HelloWorldExtension"
    }
}

```
#### Notes:

* The `"files": [ "init.php" ]` section **must** be removed from the `"autoload"` section
* The `"extra" ` section of `composer.json` must have a `"bolt-class"` section, e.g. 
`"bolt-class": "Bolt\\Extension\\Hello\\World\\HelloWorldExtension"` 

## Filesystem Layout

```
/
├─ config
│  └─ config.yml.dist
├─ src
│  └─ HelloWorldExtension.php
├─ templates
│  └─ foo.twig
├─ translations (not yet implemented)
│  └─ en_GB.yml
│  └─ nl_NL.yml
├─ tests
├─ web
│  └─ dropbear.jpg
│  └─ koala.js
│  └─ style.css
└─ composer.json
```

| File/Directory      | Description                              |
| ------------------- | ---------------------------------------- |
| `config/`           | Configuration base files (currently only config.yml.dist is supported) |
| `src/`              | Extension's PHP code |
| `templates/`        | Twig templates. These should be kept separate from public assets |
| `tests/`            | Unit/acceptance test files |
| `translations/`     | Translation files |
| `web/`              | Public/web files: css, JavaScript, images, etc. |
| `composer.json`     | This is for all extension metadata: autoloading, author(s), keywords, etc. |

#### Notes:

* `Extension.php` **must** be moved to `src/` and renamed [1]
* `init.php` should be removed. It is *not* required any longer.
* `config.yml.dist` **must** be moved to `config/config.yml.dist`
* Twig files **must** be moved to `templates/` (sub-directories are obviously allowed)
* Web assets (images, CSS, JavaScript, etc) **must** be moved to `web/`

[1] The base class name for the loaded extension, ending with the word `Extension`, e.g. `HelloWorldExtension.php`

## Bonus Features

* Local extension autoload generation is now done any time a Composer autoloader is generated, via UI, Nut, or command line Composer
* Individual extensions can now be disabled by creating `app/config/extensions.yml`
```yaml
gawain:
    clippy: true
bolt:
    disqus: false
    boltforms: true
```
* Composer autoloader can now be rebuild as required via the UI, `/app/nut extensions:autoloader` or command line Composer
* A Nut command has been added to set up the initial extensions environment: `./app/nut extensions:setup`

#### Notes:

The merging of locally installed `composer.json` files is now handled by the Composer plugin `wikimedia/composer-merge-plugin` that will be auto-added as a root require if a `extensions/local` directory is found.

It will still require installation to be completed via the UI of command line `composer update`.

## Unit & Acceptance Tests

Coverage isn't complete yet, and a number of old tests need to be removed, or ported. The porting is specifically the snippets testing which should be covered with `Bolt\Asset` testing regardless.

Closes #4556

### CODE REVIEW

**Comment by rarila** [comment]
Rejected due to too many commits.
Break it up into several smaller PRs and we may consider merging
 :stuck_out_tongue::stuck_out_tongue::stuck_out_tongue:

**Comment by bobdenotter** [comment]
Plz fix all scrutinizer issues first. :-p

**Comment by bobdenotter** [comment]
Merging in! Looks good to me. :shipit:

**Comment by GawainLynch** [comment]
*LocalExtensionWalker appears standing on the edge of a mountain…*

**Comment by jadwigo** [comment]
Somehow the name "SimpleExtension" sounds a bit ominous... Will there be a "ComplexExtension" too?

(Or rename it to something less biased)

**Comment by GawainLynch** [comment]
Well, all jokes aside, `SimpleExtension` is just that, a simple, easy to use, abstract class to get the average frontender, or not-so-confident backender up and running quickly.

Those that want full power, and have a reasonable knowledge of execution cycle, events, and :koala: dangers will just `extend AbstactExtension` and implement what they need. Which for heavier extensions will also be a performance boost.

Documentation coming for the `SimpleExtension` part… soon :-)

**Pull request merged**
