### PR TITLE
Check that there is a current user before checking isEnabled()

### LINKED ISSUE #2785: Unable to create first user: 'No route found for "POST /bolt/userfirst"'
When trying to create a first user I receive a fatal error:

* Class: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
* Message: No route found for "POST /bolt/userfirst": Method Not Allowed (Allow: GET)
* Code: 0

I think the error is caused by this recent change: https://github.com/bolt/bolt/commit/c0febb5a78c5f17ba89221f04070e9ddce5070f3

Is there an alternative way to creating a first user?

Screenshots of steps:

screen shot 2015-02-11 at 12 09 16
screen shot 2015-02-11 at 12 09 31

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #2785

### CODE REVIEW

**Comment by CarsonF** [comment]
You should use the getter method not the public property... Those things should be killed!

**Comment by GawainLynch** [comment]
> Those things should be killed!

**Comment by CarsonF** [comment]
:spaghetti:?

**Comment by GawainLynch** [comment]
Your point?

**Comment by CarsonF** [comment]
Just be funny. failing.

**Comment by GawainLynch** [comment]
@CarsonF I don't know which one of us needed the :coffee: more...  I just got the joke /facepalm

**Comment by bobdenotter** [comment]
Meging in.. Mmm, pasta :spaghetti:

**Pull request merged**
