### PR TITLE
Update version constraints for Symfony components

### PR DESCRIPTION
**Pull request by GawainLynch**
Guessing that Composer has changed something upstream as Monday's composer version just pulled Symfony 2.7 into my Bolt 2.2 install

### CODE REVIEW

**Comment by CarsonF** [comment]
That seems like a bug no?

**Comment by GawainLynch** [comment]
In which part?

**Comment by CarsonF** [comment]
The change with composer

**Comment by GawainLynch** [comment]
Ah, right… Context is everything :stuck_out_tongue_winking_eye: 

Yeah, the usual jumping around with upstreams though… Only so much benefit on not adapting in the interim.

**Comment by bobdenotter** [comment]
I'm not sure what this would change.. On my test-setup i'm getting Symfony 2.6.11 components either way.

**Comment by GawainLynch** [comment]
Maybe there was something wrong with Monday's Composer build that's now fixed.

**Pull request closed without merging**
