### PR TITLE
Replaced references to Bolt\Application with Silex\Application where possible

### PR DESCRIPTION
**Pull request by CarsonF**
Depends on #4114 

Replaced references to Bolt\Application with Silex\Application where possible. 

Excludes extensions which have it type hinted in the interface :(

`Application::DEFAULT_LOCALE` is next :gun:

### CODE REVIEW

**Comment by CarsonF** [comment]
Go home Scruitinizer you're drunk

**Comment by GawainLynch** [comment]
Scrutinizer is drunk… You want to see what [killed Travis](https://github.com/bolt/bolt/pull/4115/files#diff-d73b469cdd14c7e25186b6050caa0fffR102).

**Comment by rarila** [comment]
@CarsonF Them I'm drunk, too. Because I also see code twice ;-) :recycle:

**Comment by CarsonF** [comment]
Ok reverted that. I'll handle it in the other branch. :shipit:

**Comment by GawainLynch** [comment]
OK, so final thing/question for me. *What are we standardising on, and why?*

I've generally tried to follow — 
* If we're extending a Silex/Symfony class/function, we use `Silex\Application`. 
* The class/function would operate on a Silex Application object independently of Bolt, we use `Silex\Application`
* If I am passing `$app` to an extension function that uses something like `getContent()`, see above
* `use Bol\Application`

**Comment by GawainLynch** [comment]
i.e can we decide and put a short documentation note on the internals section in docs.

**Comment by CarsonF** [comment]
Yeah, sorry for the lack of context. 

I believe `Silex\Application` should be used everywhere. This is because all usages of `Application` are really just a DI container functionality. What we are doing right now is like typehinting `Foo` when we could be typehinting `FooInterface`. 

For GMO, we have some sites that use bolt and some that don't (same repo/framework). We also extend  Application for the same reason as Bolt (to add our services). So we have two Applications now: `Gmo\Application -> Silex\Application` and `Gmo\BoltApplication -> Bolt\Application -> Silex\Application`. All of our services have to be applied to both, and it kinda sucks.

The end goal for me is to have (something like) a `BoltServices` class that connects all of Bolt's SPs. This _single_ class would be injected into `Bolt\Application`, which just makes `Bolt\Application` a convenience class.

**Comment by GawainLynch** [comment]
:+1: from me

**Comment by bobdenotter** [comment]
Then I'm :+1: too.

**Pull request merged**
