### PR TITLE
Stop tab jumping when hovering bottom border

### PR DESCRIPTION
**Pull request by JarJak**
Easy CSS fix for Admin editor tabs

### CODE REVIEW

**Comment by bobdenotter** [comment]
Thanks for the PR, @JarJak 

Can you give a bit more info about what it is that this PR fixes?

**Comment by JarJak** [comment]
@bobdenotter It fixes tab jumping when mouse pointer is on its bottom border.

**Comment by bobdenotter** [comment]
> It fixes tab jumping when mouse pointer is on its bottom border.

I'm sorry, but I don't know what that means.

**Comment by SahAssar** [comment]
I think it means that since the tab changes size (due to the border change on hover) your mouse can get into a position where the tab will repeatedly activate and deactivate the hover event. That means that the tab will look like its "jumping" up and down repeatedly.

**Comment by GawainLynch** [comment]
I don't have this problem in [Lynx](http://lynx.invisible-island.net) :stuck_out_tongue_winking_eye: 

Also, 3.3 is closed. If we have consensus from the UI team we'll move the PR to 3.4.

**Comment by JarJak** [comment]
@SahAssar perfect description, thanks :)
@GawainLynch I thought 3.3 is still maintained

**Comment by GawainLynch** [comment]
@JarJak: No, everything in 3.3 is in 3.4+ … we cascade branch merges.

**Comment by JarJak** [comment]
@GawainLynch so even bugfixes won't be merged into 3.3?

**Comment by GawainLynch** [comment]
As we've done for all but 2.2 & 3.2, a new minor EoLs the previous. 2.2 was LTS, and due to the changes in 3.3 we kept 3.2 alive for approx. 10 or 12 weeks.

**Comment by JarJak** [comment]
Ok, thanks for answer, now I have to convince business to do an upgrade ;) Can you move this PR to 3.4?

**Comment by GawainLynch** [comment]
Haha! Yeah, "convincing the bosses" is always fun :wink: 

Yep, not a problem … I was just cleaning up a merge derp, so I'll get right on it for you :+1:

**Review by bobdenotter — APPROVED** [review]
It took some poking to finally see what it was doing, but I get it now.. Thanks for the PR, @JarJak !

**Comment by GawainLynch** [comment]
:+1:

**Pull request merged**
