### PR TITLE
Multiple file select

### PR DESCRIPTION
**Pull request by EJanuszewski**
Feature implementation for https://github.com/bolt/bolt/issues/3984

Need some feedback on the code, I definitely don't have the same skills as other contributors to bolt :)

I've added the compiled JS, sorry not sure how to undo it because I couldn't find the contributing guides before I started this, I assume you can ignore it on merge.

Details
-------
 - Please include tests with your PR. If you do, we will love you for it. - **Sorry I have no idea how to do tests :(**
 - Check if the change in the PR is a good fit for Bolt, or if it would be
   better off as an extension. - **I believe this is a good base edition**
 - Make sure you're doing the PR to the correct branch: 'master' for 3.0, or
   'release/2.2' for Bolt 2.2.x. - **Assume it doesn't need to wait for 3.0 but can change if required.**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Thanks @EJanuszewski, a good start.

There are still a lot of tabs being used in your changes, if you have a look at the [files page](https://github.com/bolt/bolt/pull/4879/files) of this PR, most will stand out.

**Comment by EJanuszewski** [comment]
@GawainLynch yep I noticed that as I was about to head to bed, I'll sort those this morning

**Comment by GawainLynch** [comment]
LGTM… All good with you @rarila & @bobdenotter ?

**Comment by bobdenotter** [comment]
At first glance it looks good to me. :+1: 

I wonder if this'll be relatively easy to forward-port to 3.0 / master..

**Comment by rarila** [comment]
Haven't checked it logically (being on tablet) but a fast ocd wise check found:
- ``if(`` should be `if (``
- function param ``last``  should be documented

**Comment by rarila** [comment]
@bobdenotter I doubt this can be forward ported

**Comment by GawainLynch** [comment]
> I doubt this can be forward ported

Can someone verify… lets not create a BC break in a late BC branch

**Comment by rarila** [comment]
@GawainLynch all that upload stuff has really heavily changed in 3.0. But on the other side doing it there for sure should be be much easier and straightforward.

**Comment by EJanuszewski** [comment]
@rarila if statements tidied and last documented

**Comment by rarila** [comment]
@EJanuszewski. :+1:

**Comment by GawainLynch** [comment]
> all that upload stuff has really heavily changed in 3.0. But on the other side doing it there for sure should be be much easier and straightforward.

Ok, can someone put up a hand for a matching PR for master so we don't feature drift.

**Comment by GawainLynch** [comment]
@EJanuszewski can we move the checkboxes to the other side same as master, then it looks good to me

**Comment by GawainLynch** [comment]
Thanks mate, much appreciated for all the help! :+1:

**Pull request merged**
