### PR TITLE
Since the username is not unique, we shouldn't use it as array key.

### PR DESCRIPTION
**Pull request by TrafeX**
We didn't saw users that have the same username. This proved to be the cause.

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm curious how yo got duplicate names in the DB, though.. Inserting them straight into the table, perhaps? ;-)

**Comment by TrafeX** [comment]
@bobdenotter No, we have a registration form, validate/handle it and call the `saveUser` method: https://github.com/bolt/bolt/blob/master/src/Users.php#L94 :)

**Comment by bobdenotter** [comment]
Merging this in will break the option to use getUser with a username: 

    {{ dump(app.users.getUser('admin') }} 

It's probably other than you had in mind, but the proper way to fix this would be to add a check to `saveUser` to prevent duplicate filenames.

**Comment by TrafeX** [comment]
@bobdenotter Good catch! I guess we can close this PR. I've created an issue to solve the underlying problem: https://github.com/bolt/bolt/issues/3287

**Pull request closed without merging**
