### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by leggewie**
Just fixing a small typo s/Breifely/Briefly/

### CODE REVIEW

**Comment by GawainLynch** [comment]
Good catch, will send into stable.

**Comment by GawainLynch** [comment]
Merged into `release/3.2` via e2433d0a3cc7f84b382b74e9a17f10cb46884f6b

**Comment by leggewie** [comment]
Thanks for merging, shouldn't this go to master, too?

**Comment by GawainLynch** [comment]
We cascade branches from stable down to master (usually twice a week). What is master now is actually 4.0-dev and won't see the light of day until the end of the year.

The map looks like this right now:

Branch | status |
---------- | -------- |
 `release/3.0` | end of life, no commits accepted |
 `release/3.1` | end of life, no commits accepted |
 `release/3.2` | current stable |
 `release/3.2` | current beta |
 `release/3.4` | current alpha |
 `3.x`              | "master" for the 3.x releases |
 `master`        | 4.0-dev |

**Comment by leggewie** [comment]
On 29.01.2017 20:34, Gawain Lynch wrote:
>
> We cascade branches from stable down to master (usually twice a week).
> What is master now is actually 4.0-dev and won't see the light of day
> until the end of the year.
>

Thank you for the explanation.

I had started to look into this possibility (of you guys going the
opposite direction of what I usually know).  Unfortunately, my internet
currently is so crappy (worse than dial-up) that I'm seriously handicapped.

**Comment by GawainLynch** [comment]
Yes, until 3.0.0 we has a very flat branch structure, and have since moved to a more standardised branching model inline with Symfony mostly. 

The problem we were addressing is that we ended up with very long freezes where features were not able to be merged, sometimes for months. This allows us to have a known stable branch, a frozen beta branch, a feature accepting alpha branch, and a "master" (3.x). 

We'll probably drop the alpha when 3.3.0 is tagged, unless individual circumstances dictate otherwise, and master became 4.0-dev so that we could being removing deprecated code and start on the migration to Symfony 3 (might even be 4 by release), Twig 2 (back under question now due to Fabien bumping that to PHP 7.0+) and a few other libraries.

> Unfortunately, my internet currently is so crappy (worse than dial-up) that I'm seriously handicapped.

I do know that one from personal experience, very well. :disappointed:

**Pull request closed without merging**
