### PR TITLE
Theme improvements

### PR DESCRIPTION
**Pull request by SahAssar**
Fixes everything in #5097 except for making it more colorful. I couldn't make it work, and I asked a few designers at work and they couldn't make it "general, but colorful" either. This re-adds magnific popup as a dependency too, since I'm assuming we want to keep using that as the default popup library.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Cool! I'll check tomorrow morning, And marge it in! 👍

**Comment by bobdenotter** [comment]
Ugh, stupid phone.

**Comment by PhillippOhlandt** [comment]
I just wondered :D

**Comment by bobdenotter** [comment]
:hear_no_evil: :see_no_evil: :speak_no_evil:

**Pull request merged**
