### PR TITLE
Add the possibility to configure accepable image formats in config.yml

### PR DESCRIPTION
**Pull request by pbnPierre**
I need in my project to add svg support in an image attribute so here is a PR to support it.
Are you ok with this feature ?

### CODE REVIEW

**Comment by CarsonF** [comment]
@pbnPierre Remind me, do svgs require different html syntax?

@GawainLynch I think we should default this to image extensions pulled from `Bolt\Filesystem\Handler\Image\Type::getExtensions`. Agree?

**Comment by GawainLynch** [comment]
@CarsonF yeah, that'd be my preference, as is not enabling the setting by default… which I think is the subtle hint you're giving there anyway.

**Comment by SahAssar** [comment]
@CarsonF no, SVG's can be used with the same `` syntax as a png or jpg (but can also be used in an object tag to allow for interactivity/animation). A related issue is that bolt/thumbs can't parse them though, see bolt/bolt-thumbs/issues/22

**Comment by pbnPierre** [comment]
@CarsonF same answer as @SahAssar with img tag you can display SVG files. And I also noticed the problem with the image resizer you mentioned in bolt/bolt-thumbs#22

**Comment by SahAssar** [comment]
@pbnPierre I think the issue that I am having with this PR is that the expectation is that any file allowed in an image field should be able to be parsed by bolt's image functions. @CarsonF and @GawainLynch seems to agree with this since they want the allowed filetypes to be determined by what bolt-thumbs supports rather than being hardcoded. Also, if you **really** want to support SVG in an image field you can simple configure it use the `extensions` property like so (although all image functions will be broken, and no preview will appear):

        image:
            type: image
            extensions: ['svg']

**Comment by SahAssar** [comment]
Alright, closing this one per the previous comment. Reopen if you feel you have a better idea :)

**Pull request closed without merging**
