### PR TITLE
Update form_div_layout.html.twig

### PR DESCRIPTION
**Pull request by mosiyash**
``Trans`` filter in twig templates must be without arguments.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Looks good to me! Thanks, @mosiyash :+1:

**Comment by mosiyash** [comment]
@bobdenotter, i dont know how to update 2.x tags...

**Comment by bobdenotter** [comment]
@mosiyash You mean the 2.2.x release tags? If so, we'll update to a new patch release soon. :-)

**Comment by mosiyash** [comment]
Cool :)

2016-02-03 22:13 GMT+06:00 Bob den Otter <notifications@github.com>:

> @mosiyash <https://github.com/mosiyash> You mean the 2.2.x release tags?
> If so, we'll update to a new patch release soon. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bolt/bolt/pull/4795#issuecomment-179318086>.
>



-- 
C уважением, Никита Мосияш
nikita.mosiyash@gmail.com

**Pull request merged**
