### PR TITLE
Add dev flag to composer.json for passwordlib

### PR DESCRIPTION
**Pull request by rossriley**

### CODE REVIEW

**Comment by GawainLynch** [comment]
:koala: :gun:

**Comment by rossriley** [comment]
I'm pretty sure the travis failure is what this fixes... because it's broken on master and the script calls `composer create-project bolt/bolt:dev-master` then this merge still won't pass.

**Comment by GawainLynch** [comment]
Potentially, or should we be using `1.0.x-dev` as the constraint?

**Comment by bobdenotter** [comment]
:leaves: :leaves: :leaves: :leaves:

**Comment by GawainLynch** [comment]
Tested locally, and if we (temporarily) require passwordlib prior to doing the create-project it installs… sending in and we can debate `@dev` versus `1.0.x-dev` when we're bored and needing a OCD fix :grin:

**Pull request merged**
