### PR TITLE
Change record save flash message. Fixes #3109

### LINKED ISSUE #3109: [Small UI Issue] Save and create new record flash is wrong
If I go to Save>Save and create new record, I get this message

image

It says "this page" when "this page" is in fact a new page that has not been saved. I think it should say "page/slug" or if it doesn't have a slug, "page/id".

### PR DESCRIPTION
**Pull request by Intendit**
Change record save flash message from "this %contenttype%" to "the %contenttype%". Fixes #3109

### CODE REVIEW

**Comment by bobdenotter** [comment]
Muchos gracias. Vielen dank. Bedankt, gast!

**Comment by bobdenotter** [comment]
@Pinpickle This solves the issue, right?

**Comment by Pinpickle** [comment]
@bobdenotter I do believe so!

**Comment by bobdenotter** [comment]
Cool! merging in! :-)

**Pull request merged**
