### PR TITLE
Removal of unused code

### PR DESCRIPTION
**Pull request by rarila**

### CODE REVIEW

**Comment by GawainLynch** [comment]
The JS refactoring done, @rarila? :stuck_out_tongue_winking_eye:

**Comment by rarila** [comment]
@GawainLynch Just discovered something brand-new called PHP and wanted to give it a try.

**Comment by rarila** [comment]
"Good job, 6 issues were fixed" … 313 to go ;-)

**Comment by bobdenotter** [comment]
Whoop!

**Pull request merged**
