### PR TITLE
Clarify message in system log, and don't log the message for user root.

### LINKED ISSUE #6334: "Configuration error: root is not granted to any roles"
When a non-root user is logged into the backend, a lot of these notices show up in the system log: 

> Configuration error: root is not granted to any roles

Which sort-of makes sense, because there _are_ no roles assigned to root. However, Bolt should not add these notices, because root is allowed to do stuff, without having to have a role. 

Details
-------

 - Relevant Bolt Version: [ 3.2 | 3.3 | master ]

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #6334.

### CODE REVIEW

**Comment by CarsonF** [comment]
Would  you mind changing the method to `info` instead of `addInfo`?

**Comment by bobdenotter** [comment]
@CarsonF Done.

**Comment by CarsonF** [comment]
I don't think that logic is right. You still want to `return false` if `$roles` is not an array.

**Comment by bobdenotter** [comment]
I think you're right. Good catch!

**Pull request merged**
