### PR TITLE
[FEEDBACK] Call addOperation in addHandler

### PR DESCRIPTION
**Pull request by Raistlfiren**
Information can be viewed about this PR in #5419.

Fixes: #5419

### CODE REVIEW

**Comment by rossriley** [comment]
While you're pushing this, I've just noticed an anomaly in that the addOperation has a chance of not being added if the operation already exists, so just to be safe it's also best to call `removeOperation($operation)` too just before adding since the handler will get updated no matter what.

**Comment by Raistlfiren** [comment]
I wonder if it isn't better to throw an exception instead of removing the operation. Otherwise, an extension may try to overwrite the functionality of a handler.

**Comment by rossriley** [comment]
Maybe, but then is that such a bad thing, it means someone can write extensions that replace the built in functionality.

We could perhaps make it explicit and have a separate method for `replaceHandler` and then throw an exception in the `addHandler` method.

**Comment by Raistlfiren** [comment]
Possibly. The biggest issue I see is that you can't really expand on the current handlers. If they could be inherited/expanded, then maybe. The biggest issue I see is that there might be new functionality added or bugs fixed in the current handlers (to core). Then the extension handlers are completely outdated and may not be able to handle the new functionality. 

I guess I could see a few rare cases where it would be nice to overwrite a default handler. I feel as though a new handler would be the best solution, and calling the new handler instead of using a "core" one.

**Comment by GawainLynch** [comment]
:+1: from all

**Pull request merged**
