### PR TITLE
Fix adjustable files urls

### LINKED ISSUE #3983: Fix hardcoded file upload paths (files/)
I've found that somewhere in code default *user upload folder name* (`files/`) is hardcoded, like
```js
//...
filename = filename.replace(/files\//ig, '');
//...
```
(taken from https://github.com/bolt/bolt/blob/master/app/src/js/modules/stack.js#L74)

I'm using custom name for that folder (`up`) and, for example, in imagelist fieldset it doesn't allow to preview, because path is hardcoded to *files/* .

### PR DESCRIPTION
**Pull request by rossriley**
Fixes #3983 

Uses the files url to link to the full version of an uploaded file

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm just going to say that i'm happy that we did a shuffle-around of files around version 2.0, and that `git blame` doesn't go back far enough to determine who wrote that in the first place.

**Comment by rarila** [comment]
Arghl, that gives me a nice rebase

**Comment by GawainLynch** [comment]
If that is giving you a rebase… you don't want to see what I have landing soon. :stuck_out_tongue_winking_eye:

**Comment by rarila** [comment]
@GawainLynch Good morning, :koala:-ninja

I doubt you have edited much twig files and I'm sure not one javascript file. :stuck_out_tongue_winking_eye: :stuck_out_tongue_winking_eye:

**Comment by GawainLynch** [comment]
The diff-stat `master..HEAD` just on the `app/view/` directory…
```
 app/view/twig/_nav/_secondary-configuration.twig                               |  81 ++++++++++++-------------
 app/view/twig/_nav/_secondary-extensions.twig                                  |  20 ++++---
 app/view/twig/_nav/_secondary-filemanagement.twig                              |  17 +++---
 app/view/twig/_nav/_secondary-translations.twig                                |  25 ++++----
 app/view/twig/_nav/_secondary.twig                                             |   2 +-
```

**Comment by rarila** [comment]
Nothing in ``editcontent``, so …

**Comment by GawainLynch** [comment]
Awesome! :+1:

**Pull request merged**
