### PR TITLE
Making better excerpts.

### PR DESCRIPTION
**Pull request by bobdenotter**
This PR makes better excerpts of entries / arrays / strings: 

 - Less duplicated code
 - Centers content around a search term, so the excerpt is more relevant
 - Highlights search terms

### CODE REVIEW

**Comment by bobdenotter** [comment]
Screenshots: 

screenshot_2016-02-09_20_33_36

screenshot_2016-02-09_20_35_47

**Comment by GawainLynch** [comment]
So there is a new Bob-charge of 4 Belgian beers per-`empty()` call… I am not going to be able to walk for weeks!

**Comment by bobdenotter** [comment]
@GawainLynch As far as i'm aware, i'm only using `empty` in cases where i'm _actually_ checking for empty strings. Like, empty titles, for example. In these cases using `empty` should be OK, right?

**Comment by GawainLynch** [comment]
No… `empty()` is an PHP "easy mode" that really should dodo… 

From the [PHP manual](http://php.net/manual/en/function.empty.php)… The following things are considered to be empty:
* "" (an empty string)
* 0 (0 as an integer)
* 0.0 (0 as a float)
* "0" (0 as a string)
* NULL
* FALSE
* array() (an empty array)
* $var; (a variable declared, but without a value)

If you want to check for an empty string, you should check for an empty string… if the variable is null, you know (because you haven't sinned with `public $foo = 'bar';` in the first place that the variable hasn't been set… ever.

If it should have been, when you `dump()` or debug, you can immediately see that there is a missing value and it gives a more indicative hint to what the programmer has missed.

**Comment by bobdenotter** [comment]
As @SahAssar pointed out. This PR fixes #4274.

**Comment by bobdenotter** [comment]
@GawainLynch Ok, so now there's one `empty()` left. 

```
        if (empty($focus)) {
            $excerpt = Html::trimText(strip_tags($excerpt), $length);
        } else {
            $excerpt = $this->extractRelevant($focus, strip_tags($excerpt), $length);
        }
```

In this case i'd want to check if it's either an empty array, or an empty string. replacing it with `(is_array($focus) && count($focus) === 0) || (is_string($focus) && $focus === '')` seems messier. What should I do with that, then?

**Comment by GawainLynch** [comment]
> In this case i'd want to check if it's either an empty array, or an empty string, or null. replacing it with (is_array($focus) && count($focus) === 0) || (is_string($focus) && $focus === '') seems messier. What should I do with that, then?

That one is a valid use :+1:

**Comment by GawainLynch** [comment]
Rule #1: Don't let :koala:s near Twig!

**Pull request merged**
