### PR TITLE
Optionally allow spaces in tag names.

### PR DESCRIPTION
**Pull request by hannesl**
This change allows spaces in tags. See #868

I added the option `allow_spaces` in taxonomy.yml.dist and set the default to false, in order to not change the default behavior.

A very simple change that seems to work perfectly!

### CODE REVIEW

**Comment by GawainLynch** [comment]
Fixes #868

**Comment by sbonardt** [comment]
Nice! :+1:

**Comment by bobdenotter** [comment]
Works like a charm!

**Comment by hannesl** [comment]
Thanks!

@bobdenotter Do you think this belongs in 2.2? With the default being that spaces are not allowed, it doesn't actually change any default behavior.

**Comment by sachbearbeiter** [comment]
Thank you very much!!!

**Pull request merged**
