### PR TITLE
Portuguese language for Portugal and Brazil

### PR DESCRIPTION
**Pull request by horus68**
Split Portuguese language for Portugal and Brazil in two languages. 
This includes: 
- Previous "pt" files renamed to "pt_BR" language as the files are from Portuguese Brazil)
- New files for Portuguese neutral (Portugal) uploaded as "pt".

Note: Language code follow Symfony usage as requested in a comment on
[RFC] Language folders should be named as xx_XX · Issue #5038 · bolt/bolt - https://github.com/bolt/bolt/issues/5038

### CODE REVIEW

**Comment by GawainLynch** [comment]
I don't know that you pulled in the changes from #5031 as this in a merge conflict state.

**Comment by horus68** [comment]
I got the en_GB files from master and the translations is for those files.

**Comment by GawainLynch** [comment]
No, I am afraid they are heavily in conflict and not easily merged.

**Comment by GawainLynch** [comment]
> Update: there was an error on my Github sync. I will update new ones!

Awesome, thank you :+1:

**Pull request closed without merging**
