### PR TITLE
Hack slug prefix to "look" right until real fix can be applied with #4014

### PR DESCRIPTION
**Pull request by CarsonF**
Hack slug prefix to "look" right until real fix can be applied with #4014

### CODE REVIEW

**Comment by bobdenotter** [comment]
In the spirit of "Let's get things working and ship it", i'd think we should merge this in. I've added issue #4767 as a reminder that we should fix it properly, though. 

Could you add a comment in the code that refers to this issue, so people who stumble upon it can have a clue what's going on in there?

**Comment by CarsonF** [comment]
@bobdenotter Does that work?

**Comment by bobdenotter** [comment]
For me it does, but Travis disagrees. Sorry, mate. :-)

**Comment by bobdenotter** [comment]
****bumps @CarsonF****

**Comment by CarsonF** [comment]
@bobdenotter ready

**Pull request merged**
