### PR TITLE
Refactor Twig setup

### PR DESCRIPTION
**Pull request by CarsonF**
The problem I had is twig was getting initialized to add globals and extensions before my customizations were added.

Twig shouldn't be initialized until it is needed, so others can extend it further.
I also moved the globals into the TwigExtension class, which also dries them up. Same with the SetcontentTokenParser.

### CODE REVIEW

**Comment by bobdenotter** [comment]
With the debug toolbar enabled, I'm getting errors on every page: 

```
Template "@WebProfiler/Profiler/info.html.twig" is not defined ().
```

Does this work correctly on your end?

screenshot 2015-01-10 10 27 41

**Comment by bobdenotter** [comment]
After I reset my git-checkout, it works as it should! Merging in, thank you!

**Comment by GawainLynch** [comment]
I am having this issue on *all* of my clones of master.  Can we revert please?

**Comment by CarsonF** [comment]
I can try to debug this on Monday. The only thing I can think of is something is calling for twig before  this code is executed. That would be fine for the old code and not for the new code

**Comment by GawainLynch** [comment]
No stress, it is just that we need to keep master always-on post-2.0.0 and this breaks stuff.

I am on limited time at the moment, so didn't have time to debug myself. :grin:

**Comment by bobdenotter** [comment]
Weird.. I'm going to merge in the revert for now, so we can figure out properly what's going on.

**Comment by GawainLynch** [comment]
@CarsonF I think you are on the right track. O e of the things I did notice on one install where I am unit testing the Composer refactor is that the CommandRunner stuff would get called on Dashboard... Something that most certainly shouldn't happen. But I was getting these errors on two other vanilla installs as well, so not limited to my branch.

Increasingly, as I type, I think the Extend loading is responsible. We had some ugly bugs early in 2.0-dev cycle to do with loading and i know we didn't get all cases down. 

If you have the chance to look deeper, it would be much appreciated!

**Comment by CarsonF** [comment]
Ok I think I found [it](https://github.com/bolt/bolt/blob/master/src/Extensions.php#L292). Extensions are added before App::initAfterHandler is called. Extensions can have twig extensions which currently initializes twig.

@bobdenotter I also see [here](https://github.com/bolt/bolt/blob/master/src/Extensions.php#L253) a global variable is added to twig. The commit (b834110) message says "Allow for better detection of installed extensions, without breaking stuff." Can you explain where this global is used?

**Pull request merged**
