### PR TITLE
Refactor Snippets

### PR DESCRIPTION
**Pull request by GawainLynch**
OK, so here is what turned out to be one of the harder refactors so far…

* Snippets are now inserted into one of two queues
  * $app['asset.queue.file'] - for CSS and JS file
  * $app['asset.queue.snippet'] - for valid HTML strings and callbacks to create such HTML
* Queues are extensible by $app->extend()ing $app['asset.queues']
* Queues are processed at final render and inserted into the requested place in the HTML
* Injection into the HTML is managed in $app['asset.injector']
* Remove the use of create_function() and replaced with a closure
  * 20% faster under 5.4+ with 2 items queued, and goes up nearly exponentially for larger arrays
  * create_function() uses eval() and is a minor security risk
  * Even php.net has a big red warning saying not to use it for 5.3.0+
* File assets are (currently) tagged with a hash. This hash is based on a salt that is generated one time per site, then hashed against the file modification time of the file. 
* Blackfire IO response tests on my system using the PHP built-in web server (xdebug off)
  * release/2.2 - 345 ms
  * refactor/snippets - 241 ms
* Inclusion of a Twig filter and function `cachehash`
e.g. adding either of these
```html
<link href="{{ cachehash('/css/base.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ '/css/base.css'|cachehash }}" rel="stylesheet" type="text/css" />
```
Would produce something like:
```html
<link href="/css/base.css?v=abcde12345" rel="stylesheet" type="text/css" />
```

Finally, there was a minor concern about "a lot of code" to do something simple. There is nothing simple about this code in its current form in master, it's fragile and does a lot. So I took the time to run some comparison checks to hopefully illustrate some of that.

This functionality comes from `Bolt\Extensions` and `Bolt\BaseExtension` so the following comparison includes those classes, before and after (after with backward compatible code removed for sake of valid comparison)
###### Logical Lines of Code
* Before: 431
* After:  457

A more interesting nerd statistic is Cyclomatic Complexity… Just a small change :wink:. But I will point out that is, obviously, just a useful indicator and not any sort of rule book.

The more detailed breakdown:

### Before
`phploc src/Extensions.php src/BaseExtension.php`

````
Size
  Lines of Code (LOC)                             2047
  Comment Lines of Code (CLOC)                     753 (36.79%)
  Non-Comment Lines of Code (NCLOC)               1294 (63.21%)
  Logical Lines of Code (LLOC)                     431 (21.06%)
    Classes                                        408 (94.66%)
      Average Class Length                         136
        Minimum Class Length                        23
        Maximum Class Length                       258
      Average Method Length                          4
        Minimum Method Length                        1
        Maximum Method Length                       32
    Functions                                        0 (0.00%)
      Average Function Length                        0
    Not in classes or functions                     23 (5.34%)

Cyclomatic Complexity
  Average Complexity per LLOC                     0.39
  Average Complexity per Class                   80.00
    Minimum Class Complexity                     37.00
    Maximum Class Complexity                    123.00
  Average Complexity per Method                   2.83
    Minimum Method Complexity                     1.00
    Maximum Method Complexity                    29.00
```

### After
`phploc src/Extensions.php src/BaseExtension.php`
```
Size
  Lines of Code (LOC)                             1341
  Comment Lines of Code (CLOC)                     493 (36.76%)
  Non-Comment Lines of Code (NCLOC)                848 (63.24%)
  Logical Lines of Code (LLOC)                     273 (20.36%)
    Classes                                        253 (92.67%)
      Average Class Length                         126
        Minimum Class Length                       119
        Maximum Class Length                       134
      Average Method Length                          3
        Minimum Method Length                        1
        Maximum Method Length                       21
    Functions                                        0 (0.00%)
      Average Function Length                        0
    Not in classes or functions                     20 (7.33%)

Cyclomatic Complexity
  Average Complexity per LLOC                     0.33
  Average Complexity per Class                   46.00
    Minimum Class Complexity                     32.00
    Maximum Class Complexity                     60.00
  Average Complexity per Method                   2.37
    Minimum Method Complexity                     1.00
    Maximum Method Complexity                     8.00
```

`phploc src/Asset`
```
Size
  Lines of Code (LOC)                              959
  Comment Lines of Code (CLOC)                     390 (40.67%)
  Non-Comment Lines of Code (NCLOC)                569 (59.33%)
  Logical Lines of Code (LLOC)                     184 (19.19%)
    Classes                                        164 (89.13%)
      Average Class Length                          16
        Minimum Class Length                         1
        Maximum Class Length                        48
      Average Method Length                          2
        Minimum Method Length                        1
        Maximum Method Length                        9
    Functions                                        0 (0.00%)
      Average Function Length                        0
    Not in classes or functions                     20 (10.87%)

Cyclomatic Complexity
  Average Complexity per LLOC                     0.23
  Average Complexity per Class                    5.20
    Minimum Class Complexity                      1.00
    Maximum Class Complexity                     19.00
  Average Complexity per Method                   1.95
    Minimum Method Complexity                     1.00
    Maximum Method Complexity                     6.00
```

### CODE REVIEW

**Comment by bobdenotter** [comment]
Awesome!! 

awesome

**Comment by rarila** [comment]
:leaves::leaves::leaves::leaves::leaves::leaves::leaves:

**Comment by GawainLynch** [comment]
Just a note that the Scrutinizer results are base on false-positive code duplication in the functions listed, and it's inability under certain circumstance to check where and how an array parameter can be/is used.

**Comment by GawainLynch** [comment]
Derp, left out `src/Extensions/Snippets/Location.php` so stats updated.

**Comment by CarsonF** [comment]
tom-cruise-dance

**Comment by bobdenotter** [comment]
Choo choo!!

**Pull request merged**
