### PR TITLE
Move the getRepeaters call into the nohydrate block

### PR DESCRIPTION
**Pull request by rossriley**
Whoops, looks like I've been responsible for wasting a lot of internet electricity.

@graham73may watch your query count go down after this one.

### CODE REVIEW

**Comment by graham73may** [comment]
I'll definitely give this a go and compare! 

Whilst digging the other day we noticed that some things like menu items were being hydrated. I think it was firing off more calls as well. Is it required when they're only returning basic info?

**Comment by rossriley** [comment]
Yes, that was what I found when debugging this. In the backend at least the culprit was the permission check which for some reason seems to fire off a check for each record in the contenttype, not just the record that you are editing.

So this PR alone dropped 434 queries to 20 for me.

But thanks for designing that hideous contenttype 😄  because it's helped me find where the bodies are buried.

**Comment by graham73may** [comment]
Ah great! I'll send you my new query numbers when I merge this in, should be interesting. :-p

**Comment by GawainLynch** [comment]
> Whoops, looks like I've been responsible for wasting a lot of internet electricity.

You sure it was you? I could have sworn I just saw :koala: paw prints!

> the culprit was the permission check which for some reason seems to fire off a check for each record in the contenttype

Yes, I can't remember *exactly* when I attacked that last (2.2-dev or 3.0-dev), but I removed ~98-99% of those query calls (a few have since been reintroduced :frowning_face:). The persisting problem being how much business logic is still in our BE templates.

Part of this will go away with Symfony Security in v4.0, part of it will get further cleaned up with the work attached to forms & DTOs.

But that said, this is exactly why a couple of people have found me heavily disagreeing with enhancing "owner" properties at the moment.

**Comment by graham73may** [comment]
So this is before (with the other PR to fix query times already merged):
image

This is after (so this PR + the other one):
image


Wow... and to think on Friday that was 160,000 ms!

**Pull request merged**
