### PR TITLE
Config split parsing methods

### PR DESCRIPTION
**Pull request by CarsonF**
Here's the big one....I would look at each commit separately.

### CODE REVIEW

**Comment by GawainLynch** [comment]
These are throwing weird test errors... @rossriley?

**Comment by GawainLynch** [comment]
No kittens crying here :smile_cat:

**Comment by rossriley** [comment]
That's more like kittens committing suicide...

**Comment by GawainLynch** [comment]
> That's more like kittens committing suicide...

Yes, but they're happy!

**Comment by CarsonF** [comment]
Yeah it's all the same logic just different variable names and indentation. Unfortunately, that doesn't diff well.

**Pull request merged**
