### PR TITLE
Fixes server-side error when ajaxy-deleting records that were created programmatically

### LINKED ISSUE #3604: Can't use 'ajaxy delete' on records that were generated programmatically.
See screenshot: 

screen shot 2015-05-31 at 12 31 38

### PR DESCRIPTION
**Pull request by bobdenotter**
Note: This is a fix #3604 for 2.2. Should also be fixed for `master`.

### CODE REVIEW

**Comment by GawainLynch** [comment]
Failures are Crapception and that creates a need for a Composer version dance to get around… merging and we'll keep an eye on why fails occur and deal with accordingly.

**Comment by GawainLynch** [comment]
Passes locally with Codeception 2.0.12… merging!

**Comment by bobdenotter** [comment]
Thanks, gawain!

**Comment by GawainLynch** [comment]
Teamwork, it's what we do :+1:

**Pull request merged**
