### PR TITLE
Allow the database integrity checker to log schema diffs to debug logger when enabled

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Whoop! Let's see if it logs this one: 
screenshot 2015-04-18 09 57 38

**Comment by GawainLynch** [comment]
It certainly did for me. I dumped the debug log from yesterday that had that one in it. But an example from this morning's test:
```
[2015-04-18 06:20:24] bolt.INFO: Database update required ["ALTER TABLE bolt_cron CHANGE lastrun lastrun DATETIME NOT NULL"] []
```

**Comment by bobdenotter** [comment]
This is the one i'm getting: 

    [2015-04-18 10:08:38] bolt.INFO: Database update required ["ALTER TABLE bolt_users DROP INDEX IDX_5585B54F85E0677, ADD UNIQUE INDEX UNIQ_5585B54F85E0677 (username)"] []

Go home Mysql, you're drunk.

**Comment by GawainLynch** [comment]
That's the one… Really annoying. As I mentioned on IRC, both Sqlite and PostgreSQL behave properly :frowning:

**Comment by bobdenotter** [comment]
Yeah, wonder how to fix that, since the index ID's are the same.

**Pull request merged**
