### PR TITLE
Base-2016 is dead, long live Base-2016!

### PR DESCRIPTION
**Pull request by SahAssar**
Well...

 This is the changeover from the "old" base-2016 to the new. It is based on https://github.com/bobdenotter/bolt-foundation-theme and has minimal changes compared to that.

The photos included are also the ones I plan to PR for our default photos in the /files/ directory.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Looks good to me! 

Shouldn't the "default header images" in here not be cropped to letterbox sizes?

**Comment by SahAssar** [comment]
Hmm, AFAIK the headers aren't cropped at all: https://github.com/bolt/bolt/pull/5076/commits/546a0dd81d9355b08fb7a2ab962c2e9df47a66c4#diff-7e824e6aaae91b7efe05e42cf2fa05abR17

Basically, if we don't have `save_files` turned on by default we shouldn't rely on it in the default theme, right? So this just assumes that the "header images" are cropped to ffit.

**Comment by SahAssar** [comment]
Ah, didn't get what you meant with default header images before. Basically I think it is more important to have it still look OK while someone is experimenting with the height of that element than it is to have optimal performance for someone who doesn't care change the image, But I'm open to having it match the max/min heights of normal screens if that gets the filesize down noticeably.

**Comment by GawainLynch** [comment]
Erm…
```
$ ls -lh theme/base-2016/images/
total 1.7M
-rw-rw-r--. 1 gawain gawain 359K Mar 24 07:13 02.jpg
-rw-rw-r--. 1 gawain gawain 190K Mar 24 07:13 03.jpg
-rw-rw-r--. 1 gawain gawain 165K Mar 24 07:13 04.jpg
-rw-rw-r--. 1 gawain gawain 284K Mar 24 07:13 05.jpg
-rw-rw-r--. 1 gawain gawain 168K Mar 24 07:13 06.jpg
-rw-rw-r--. 1 gawain gawain 323K Mar 24 07:13 07.jpg
-rw-rw-r--. 1 gawain gawain 143K Mar 24 07:13 09.jpg
```

```
$ ls -lh files/ 
total 1.1M
drwxr-xr-x. 2 gawain gawain 4.0K Feb 14 14:09 2016-02
-rw-rw-r--. 1 gawain gawain  67K Feb 12 09:06 agriculture-cereals-field-621.jpg
-rw-rw-r--. 1 gawain gawain  34K Feb 12 09:06 alarm-clock-gold-hands-of-a-clock-1778.jpg
-rw-rw-r--. 1 gawain gawain  51K Feb 12 09:06 analog-camera-photography-vintage-1844.jpg
-rw-rw-r--. 1 gawain gawain  50K Feb 12 09:06 apple-desk-iphone-2750.jpg
-rw-rw-r--. 1 gawain gawain  74K Feb 12 09:06 architecture-books-building-2757.jpg
-rw-rw-r--. 1 gawain gawain  47K Feb 12 09:06 bell-bills-cash-register-2738.jpg
-rw-rw-r--. 1 gawain gawain  52K Feb 12 09:06 blur-breakfast-coffee-271.jpg
-rw-rw-r--. 1 gawain gawain  45K Feb 12 09:06 blur-flowers-home-1093.jpg
-rw-rw-r--. 1 gawain gawain  97K Feb 12 09:06 building-frame-garage-1599.jpg
-rw-rw-r--. 1 gawain gawain  45K Feb 12 09:06 california-foggy-golden-gate-bridge-2771.jpg
-rw-rw-r--. 1 gawain gawain  56K Feb 12 09:06 carrot-cooking-eat-1398.jpg
-rw-rw-r--. 1 gawain gawain  39K Feb 12 09:06 configure-disc-jockey-disco-1504.jpg
-rw-rw-r--. 1 gawain gawain  93K Feb 12 09:06 food-fruit-orange-1286.jpg
-rw-rw-r--. 1 gawain gawain 100K Feb 12 09:06 garden-gardening-grass-589.jpg
-rw-rw-r--. 1 gawain gawain    4 Feb 12 09:06 index.html
-rw-rw-r--. 1 gawain gawain  65K Feb 12 09:06 keyboard-old-technology-2318.jpg
-rw-r--r--. 1 gawain gawain 153K Feb 13 19:32 refactor-wars.png
```

**Comment by GawainLynch** [comment]
```
Twig_Error_Loader
Template "_header.twig" is not defined in "index.twig" at line 1.
```

**Comment by SahAssar** [comment]
Images are down to 1.22M now, @GawainLynch ;)

**Comment by GawainLynch** [comment]
@SahAssar can you change [this line](https://github.com/bolt/bolt/blob/master/tests/codeception/acceptance/_bootstrap.php#L64) to:
```php
    INSTALL_ROOT . '/theme/base-2016/partials/_footer.twig'  => true,
```

**Comment by GawainLynch** [comment]
BDFL :+1: 
BPFL :+1:

**Comment by bobdenotter** [comment]
Whoop woop!

**Pull request merged**
