### PR TITLE
Refactor Config

### PR DESCRIPTION
**Pull request by CarsonF**
Most of this is breaking getConfig() into separate methods. 
I made resources a class variable since it is used all over the class.

I'm not sure if anything in here is considered a BC break. BC only counts for using the class right, not extending it? 
I ask because I changed some of the methods to now return their results instead of setting them to class variables.
This wouldn't affect users of the class only people who are extending it.

### CODE REVIEW

**Comment by GawainLynch** [comment]
First comment is that I would consider this in need of time in `canary` that @rossriley is setting up.

**Comment by bobdenotter** [comment]
Just a quick update: Once #2488 has landed, we'll merge this into the 'canary' branch. Soon! :-)

**Comment by rixbeck** [comment]
:+1:

**Comment by CarsonF** [comment]
Well I just rebased onto canary. I'm closing this PR and making a new one for canary branch

**Pull request closed without merging**
