### PR TITLE
Script handler refactor follow up

### PR DESCRIPTION
**Pull request by CarsonF**
Further follow up to script handler refactor.

### CODE REVIEW

**Comment by GawainLynch** [comment]
Otherwise looks good, but I'll go over again in the morning.

**Comment by CarsonF** [comment]
> So this and the composer-installer revert now mean that if you shift bolt_assets the git file and old directory remain … kinda the point of reverting the composer-install change in the first place 😉

How's that? [DirectoryConfigurator.php L185](https://github.com/CarsonF/bolt/blob/541f30fc978a9d43a38b33779566ab0e999f77fb/src/Composer/Script/DirectoryConfigurator.php#L185)

**Comment by GawainLynch** [comment]
```
$ composer create-project
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Bolt\Composer\ScriptHandler::installAssets
> Bolt\Composer\ScriptHandler::configureProject

 Do you want to use Bolt's standard folder structure? (yes/no) [yes]:
 > no

All paths are currently relative to the current working directory (/tmp/foobar)

Paths can have aliases to other paths. These are specified with a word surrounded by percents.
For example, if we defined user as /Users/Me, then %user%/my-site would resolve to /Users/Me/my-site

 ---- ------------------- ---------------------------------------------      
  #    Name                Path                                              
 ---- ------------------- ---------------------------------------------      
  1    site                .                                                 
  2    app                 %site%/app (app)                                  
  3    cache               %app%/cache (app/cache)                           
  4    config              %app%/config (app/config)                         
  5    database            %app%/database (app/database)                     
  6    extensions          %site%/extensions (extensions)                    
  7    extensions_config   %config%/extensions (app/config/extensions)       
  8    web                 %site%/web (web)                                  
  9    files               %web%/files (web/files)                           
  10   themes              %web%/theme (web/theme)                           
  11   bolt_assets         %web%/bolt-web/view (web/bolt-web/view)           
 ---- ------------------- ---------------------------------------------      
                                                          
Customizing!                                      

Writing customized paths to .bolt.yml
Installing bolt_assets to /tmp/foobar/web/bolt-web/view
> Bolt\Composer\ScriptHandler::installThemesAndFiles
Installing files to /tmp/foobar/web/files
Installing themes to /tmp/foobar/web/theme
> nut extensions:setup

Creating/updating composer.json… [DONE]

Updating autoloaders… [DONE]
Generating autoload files
> Bolt\Composer\EventListener\PackageEventListener::dump
Generating autoload files
> Bolt\Composer\EventListener\PackageEventListener::dump

$ ls web/bolt-* -a
web/bolt-public:
.  ..  .gitignore

web/bolt-web:
.  ..  view
```

**Comment by GawainLynch** [comment]
image

Values are as expected, but can you see where it's tripping over … it is never told to move `bolt-public`, only `view/` :wink:

**Comment by CarsonF** [comment]
Oh I see `bolt-public` is ignored. Can we just remove the superfluous `view/` subfolder?

**Comment by GawainLynch** [comment]
> Oh I see bolt-public is ignored. Can we just remove the superfluous view/ subfolder?

:+1: from me

**Comment by GawainLynch** [comment]
```
 ---- ------------------- --------------------------------------------- 
  #    Name                Path                                         
 ---- ------------------- --------------------------------------------- 
  1    site                .                                            
  2    app                 %site%/app (app)                             
  3    cache               %site%/var/cache (var/cache)                 
  4    config              %app%/config (app/config)                    
  5    database            %app%/database (app/database)                
  6    extensions          %site%/extensions (extensions)               
  7    extensions_config   %config%/extensions (app/config/extensions)  
  8    web                 %site%/web (web)                             
  9    files               %web%/files (web/files)                      
  10   themes              %web%/theme (web/theme)                      
  11   bolt_assets         %web%/bolt (web/bolt)                        
 ---- ------------------- --------------------------------------------- 
[snip]

$ ls -a web/bolt*
.  ..  css  fonts  .gitignore  img  js  view
```

OK, WFM :+1: 

Only follow-up we might need to think about. Changing the cache directory, as the app gets invoked at various points, the cache is initially moved correctly, but a new one created (which is safe for a user to delete).

**Comment by CarsonF** [comment]
Hmmm the directories should be moved and done before the app is ever invoked. It's created for syncing files & themes, extensions setup and syncing assets. All of which should come after moving the directories around.

**Pull request merged**
