### PR TITLE
Sync configuration defaults with config.yml

### PR DESCRIPTION
**Pull request by SahAssar**
And remove debug_compressjs, debug_compresscss and 'caching/rendering'
since those are not used anymore

### CODE REVIEW

**Comment by SahAssar** [comment]
@bobdenotter Since `wysiwyg/ck/viewSourceRoles` seems to be completely unimplemented I was considering removing that too (from config.yml), but wanted to check with you first... Thoughts? It was added in https://github.com/bolt/bolt/commit/35fa25853efe8d3dbc8c64780a5ebb3d2fc8b438

**Comment by GawainLynch** [comment]
Also would be worth getting some input from @CarsonF on this as we're about to tear apart that whole class.

**Comment by SahAssar** [comment]
@GawainLynch Agreed, but so far this is just removing keys or changing values, so I'm assuming that it won't change the refactor much.

**Comment by GawainLynch** [comment]
No stress… was more just tagging him for the notification and associated "Look here, Carson"

**Comment by bobdenotter** [comment]
Yes, imho we can merge this in now, regardless of upcoming changes.

**Comment by bobdenotter** [comment]
Just to confirm: `allowedContent` and `viewSourceRoles` both have no effect. 

\*insert emoji of dodo here\*

**Comment by CarsonF** [comment]
👍

**Comment by bobdenotter** [comment]
Whoooop!

**Pull request merged**
