### PR TITLE
Enable HTTP Cache to be passed configuration options

### PR DESCRIPTION
**Pull request by GawainLynch**
I'll add a PR to docs if/when this is agreed upon

### CODE REVIEW

**Comment by bobdenotter** [comment]
How do these relate to these? https://github.com/bolt/bolt/blob/release/3.2/app/config/config.yml.dist#L169-L176 

I can see this being slightly confusing to novices (and me) :-)

**Comment by GawainLynch** [comment]
> How do these relate to these? 

```
+# For more information on performance settings see https://docs.bolt.cm/performance/
```

But you will need to enable request caching first … in the middle of the "I'll add a PR to docs if/when this is agreed upon" part

> I can see this being slightly confusing to novices (and me) :-)

There is a reason that it is commented out. It is not a feature for a novice, and am happy to remove the `.dist` part if that is people's wishes … rebases are easy :wink:

**Comment by GawainLynch** [comment]
Docs: https://github.com/bolt/docs/pull/573

**Comment by GawainLynch** [comment]
Note that docs are being pulled as we're not documented advanced-level user features.

**Pull request merged**
