### PR TITLE
Fixed: Files without recognised extensions don't break the file browser. 

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes: #5759, until a better solution lands.

### CODE REVIEW

**Comment by CarsonF** [comment]
One thing though, it's not really deprecated anymore than the class itself is.

**Comment by bobdenotter** [comment]
Should I then just omit the comment there? It might be good to keep a reference to the issue number in, right?

**Comment by CarsonF** [comment]
Sure, if you want. I don't think it's necessary. It was really just an oversight before.

**Comment by bobdenotter** [comment]
Updated the comment.

**Comment by CarsonF** [comment]
Added explaination to that issue too

**Comment by CarsonF** [comment]
Really the line above it for `setUrl('theme'` could be removed. It isn't needed there as it's set in `setThemePath`. If it looks confusing to you to have both there, otherwise :shipit:

**Comment by bobdenotter** [comment]
I'm a bit wary to remove that one. Afraid it'll come back to haunt us in unexpected ways. :-)

**Comment by CarsonF** [comment]
Ok no worries.

**Pull request merged**
