### PR TITLE
Correctly get templatefields.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Change triggers a fatal error on the resource CT in the acceptance tests.

**Comment by bobdenotter** [comment]
Ok, the following  works and it passes the acceptance tests locally: 

```
        if ($content->getTemplatefields()) {
            $templateFields = $content->getTemplatefields()->getContenttype()->getFields() ?: [];
        } else {
            $templateFields = [];
        }
```

Would that be a good way to check if `getTemplatefields()` is OK?

**Comment by GawainLynch** [comment]
Yeah, they're already injected into the class at that point, so no extra overhead that way… and easy to read.

**Comment by bobdenotter** [comment]
Ok, fixed.

**Comment by GawainLynch** [comment]
Dank je :smiley_cat:

**Pull request merged**
