### PR TITLE
Log DBAL failures for timed (de)publication of contenttype records

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
:100:

**Comment by GawainLynch** [comment]
There is a slim chance this might show us something that is not quite right, at the moment. But my hope is that if this is the case, we might see something during beta.

**Comment by bobdenotter** [comment]
I was thinking this seems pretty "edge casey" to me, but I figured you had a reason for doing this. ;-)

**Comment by GawainLynch** [comment]
Yeah, that was pretty much what is in my head… But I try to stick with the Samuel L. Jackson rule of assumptions… ergo, don't swallow the error.

**Pull request merged**
