### PR TITLE
Fix for uploading to `themes/` folder in backend.

### LINKED ISSUE #5678: Uploading a files in `themes/` seems to be broken.
Uploading a file here: 

screen shot 2016-08-12 at 16 55 31

Gives this error: 

screen shot 2016-08-12 at 16 55 24

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #5678 

This fix is a bit hackish. Open to better suggestions. :-)

### CODE REVIEW

**Comment by rossriley** [comment]
Looks fine to me. I did make a note somewhere that if you mount a new filesystem name then there needs to be a corresponding entry in Resource Manager. 

One thing to check do we set in Configuration/Composer too if so we'll need to add the alias in that class too.

**Comment by GawainLynch** [comment]
This is mounted in `bolt/filesystem` not here, deliberately.

**Comment by CarsonF** [comment]
> Looks fine to me. I did make a note somewhere that if you mount a new filesystem name then there needs to be a corresponding entry in Resource Manager.

Do you mean the opposite?

**Comment by bobdenotter** [comment]
Sorry guys, you've lost me. :-/

**Comment by rossriley** [comment]
Sorry, was on mobile so I couldn't check. Was referring to this: https://github.com/bolt/bolt/blob/release/3.0/src/Provider/UploadServiceProvider.php#L65

No @bobdenotter no problem, just needed to check that we didn't replace `themebase` in the composer configuration but we don't so no need to worry.

**Comment by CarsonF** [comment]
@rossriley Ah gotcha.

@bobdenotter I think what @GawainLynch means is we already have `themes` defined in [FilesystemServiceProvider](https://github.com/bolt/bolt/blob/release/3.0/src/Provider/FilesystemServiceProvider.php#L30).

**Comment by bobdenotter** [comment]
> @bobdenotter I think what @GawainLynch means is we already have themes defined in FilesystemServiceProvider.

Yes, but uploading to the themes folder didn't work.

**Comment by rossriley** [comment]
@bobdenotter sorry for confusing things, this PR is exactly what we need. No need to change anything.

My comment was just a note that in future if we add a new filesystem (themes was added to replace themebase) then we need to add a corresponding `getPath` in ResourceManager which is exactly what you've done in this PR.

**Comment by GawainLynch** [comment]
@bobdenotter see 1af24d0705f2fc3c88583870d462ca9febafdd07

**Comment by GawainLynch** [comment]
Teamwork FTW :+1:

**Pull request merged**
