### PR TITLE
Retrieve existing relations before setting them from POST. Fixes #4044

### LINKED ISSUE #4044: No related entries on preview
Hello,

I have contenttype `A` and contenttype `B`.

On `A` I can select one of `B`. On the template for `B` I can fetch `A` with related().. But When I preview `B` the relation to `A` is `false`.

Looks like a bug to me.

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #4044

### CODE REVIEW

**Comment by bobdenotter** [comment]
Same here, please hold off on merging... I think I'm overlooking something, and want to make sure.

**Comment by GawainLynch** [comment]
Yeah, this doesn't look right for master and I think will break when the other parts of the relationship stuff is pushed… but I might just be missing the obvious myself :grin:

**Comment by bobdenotter** [comment]
What would break? It seems to work correctly on master now, and since it uses `->setRelation()` now, I'm not sure it would break _more_ than before..

**Comment by GawainLynch** [comment]
I'm guessing, as it's still "fluxy"… We're fiddling with those objects at the moment, but if it fixes, it fixes… give me a few, I just want to follow up on this one as there is potential overlap with the changes I am doing right now for that other thing.

**Comment by GawainLynch** [comment]
Oh… Read the code, Gawain… this is all in legacy! Nothing to see here! But more-so that should have been cut-out be our changes and may be why something else is breaking! :grin:

**Comment by bobdenotter** [comment]
Works on PHP 5.4 now!

**Comment by bobdenotter** [comment]
\*twiddles thumbs patiently\* ;-)

**Comment by GawainLynch** [comment]
About [when this lands](https://github.com/bolt/bolt/tree/hotfix/relationship-structure) as a PR… @rossriley is having a look at present.

**Comment by GawainLynch** [comment]
The eagle has landed!

**Pull request merged**
