### PR TITLE
Backport "canonical" Twig function

### PR DESCRIPTION
**Pull request by GawainLynch**
Not sure what to call this, beyond :koala: 

This is another part of the missing backport of #5836 that "someone" was supposed to take care of, and didn't do a good job of … we're looking at **you**, Kenny :koala: !!!

**Edit:** Obviously credit goes to @CarsonF for this work!

### CODE REVIEW

**Comment by GawainLynch** [comment]
Thanks mate, and thanks @CarsonF

**Comment by CarsonF** [comment]
You're missing the actual canonical code though...

**Comment by GawainLynch** [comment]
Are you sure? That part should have been backported ages ago … this was a bit that the :koala: forgot

**Comment by CarsonF** [comment]
https://github.com/bolt/bolt/blob/release/3.2/src/Canonical.php
https://github.com/bolt/bolt/blob/master/src/Canonical.php

**Pull request merged**
