### PR TITLE
Remove realpath() use from Bolt\Configuration\Environment

### PR DESCRIPTION
**Pull request by GawainLynch**
If it's green… it's now merge worthy! :+1:

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm getting conflicting messages here. ;-)

**Comment by GawainLynch** [comment]
@bobdenotter it was a really weird bug that we thought we'd gotten to the bottom of… 

The commit you reference was a "THIS WILL BREAK EVERYTHING" debug commit that we planned to rebase out once it had run and given us some extra Travis information :grin:

**Comment by bobdenotter** [comment]
GTG now?

**Comment by GawainLynch** [comment]
Very GTG

**Comment by rixbeck** [comment]
lol

Sent with AquaMail for Android
http://www.aqua-mail.com

**Pull request merged**
