### PR TITLE
Fix broken links, add links to changelog.md

### LINKED ISSUE #6974: Multiple broken and missing links in changelog.md
I first noticed that the link to commit #6787 link was broken in the changelog. I then noticed that multiple other links were broken. While we're at it, does anyone notice that most of the links before the 3.0 release are missing entirely? So we have lots of "See #2077", or "Fixes #2025", but each requires manual typing to find the link.

I think 15 minutes with a Vim regex could easily correct these links (PR coming!) with no source code regressions.

### PR DESCRIPTION
**Pull request by mborn319**
I put "WIP" on this one just because 1) I didn't manually check every link, and 2) y'all may not be a fan of my six commits. Sorry, I wasn't sure how to squash these and wasn't sure if that was necessary anyway.

Fixes: #6974 

Just for kicks, here's basically the Vim regex I used to update these.
`:%s/#\([0-9]*\)$/[#\1](https:\/\/github.com\/bolt\/bolt\/issues\/\1)/gc`
Replaces all #xxxx at the end of the line with a link to issue #xxxx.

### CODE REVIEW

**Comment by GawainLynch** [comment]
As mentioned in #6974 … this could cause a planet ending #1555 event … **merge with caution**!

**Comment by GawainLynch** [comment]
> y'all may not be a fan of my six commits.

Oh, no stress. I was too busy running with the collective humour around this and the linked issue I missed the text.

Personally, I am a bit obsessive about source code commits these days, but this is not a thing we'll be back tracking trying to figure out why an obscure bug crept in … so go for commit count :+1:

**Comment by mborn319** [comment]
@GawainLynch Good to know you're taking this seriously!

**Comment by GawainLynch** [comment]
Serious is my third middle name, right after "Derpy" & "Stupid" :rofl:

**Comment by mborn319** [comment]
See new commit. I'd be very interested to hear what proofreading software helped you catch that typo...

**Comment by GawainLynch** [comment]
> I'd be very interested to hear what proofreading software helped you catch that typo

Well, this explanation fits with the theme of this PR, the "software" product page is: http://caffegoriziana.com/cms/portfolio/gocaffe-bio/ (I also highly recommend the Brasil Santos). I was just sipping my early morning coffee, opened the rendered version of the commit and went on a visual pattern match … followed by a CTRL-f for `((` and `))`.

Thanks for all this, it really is very much appreciated. Out of courtesy I'll let @bobdenotter give this the quick once over when he gets out of bed in a couple more hours and then send it in :+1:

**Comment by bobdenotter** [comment]
This one's GTG as well, right?

**Comment by GawainLynch** [comment]
Yes mate, the change log is you baby … just wanted you to have the chance to OK it too

**Comment by bobdenotter** [comment]
Ah, right! Will look over it, and merge in if nothing pops up.

**Pull request merged**
