### PR TITLE
Merge pull request #1 from bolt/master

### PR DESCRIPTION
**Pull request by miguelavaqrod**
Update from original

### CODE REVIEW

**Comment by miguelavaqrod** [comment]
What!!!! I promise I was on my own repo...
Oh my god...

**Comment by miguelavaqrod** [comment]
Please... close it.. I will not do it again... :-(

**Comment by GawainLynch** [comment]
You're best of doing this locally.  Create an upstrea

**Comment by miguelavaqrod** [comment]
Yes.. you are right,, I am more comfortable using command line... it seems I do not master github.
Sorry again and thanks for your patience

**Comment by bobdenotter** [comment]
@miguelavaqrod No worries, really! ^_^

**Pull request closed without merging**
