### PR TITLE
changed example code for page binding starting line 85

### PR DESCRIPTION
**Pull request by uk61**
Example code was not working, exchanged it with the code give in the bolt docs, see also https://discuss.bolt.cm/d/110-solved-can-i-fetch-canonical-url/4

### CODE REVIEW

**Comment by GawainLynch** [comment]
The files in master are a different version. The files in 2.2 behave this way, and v3 is backwards compatible, but that is deprecated

**Comment by SahAssar** [comment]
Hey @uk61, sorry if I was a bit fuzzy on the forums, but this needs to go in the 2.2 branch. Master is still being worked on quite heavily and isn't quite the place for these PR's. :)

**Comment by GawainLynch** [comment]
@uk61 yeah and sorry if that came out harsh… I am away from home right now, busy, under-caffeinated and unable to use a web browser properly… Thank you for making the effort too :+1:

**Comment by uk61** [comment]
Yo, no problem, want me to make a pull request for the 2.2 branch then?

**Comment by SahAssar** [comment]
@uk61 Yeah, that would be great! (IIRC).

**Pull request closed without merging**
