### PR TITLE
Fix #2961 (No fields are shown in editor)

### LINKED ISSUE #2961: No fields are shown in editor..
See screenshot. No fields are shown: 

screen shot 2015-02-27 at 10 06 39

The database seems OK, and after "loripsumming" it, they show fine in the _frontend_.

### PR DESCRIPTION
**Pull request by rarila**
Fixes #2961

### CODE REVIEW

**Comment by rarila** [comment]
@GawainLynch Then I tell you there is a regression in the regression of the regression! ;-)

**Comment by GawainLynch** [comment]
iPads... They suck.

**Comment by bobdenotter** [comment]
> iPads... They rock.

Yes, they do indeed. :metal:

**Comment by rarila** [comment]
I regress… regret

**Pull request merged**
