### PR TITLE
Fix spelling mistake

### LINKED ISSUE #3687: E-mail Typo in new user message
There is a typo in "app/view/twig/email/firstuser.twig". The word "received" is misspelled "recived".

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #3687

### CODE REVIEW

**Comment by rarila** [comment]
Funky!

**Comment by GawainLynch** [comment]
> Funky!

Monkey!

**Comment by rarila** [comment]
No, not from The Monkeys…
"Groovy groovy jazzy funky …"

**Comment by rarila** [comment]
I see :leaves: …

**Pull request merged**
