### PR TITLE
adding extension and library requirements

### PR DESCRIPTION
**Pull request by dwolf555**
adding pdo and gd extensions as well as curl library to composer.json to make sure minimum requirements are met

### CODE REVIEW

**Comment by CarsonF** [comment]
What in core requires GD and Curl?

**Comment by bobdenotter** [comment]
Thumbs requires GD, and Guzzle requires Curl. Not sure if either of those packages has these dependencies in their own `composer.json`.

**Comment by CarsonF** [comment]
Both do.

**Comment by bobdenotter** [comment]
Wait, did you add that second sentence as a ninja-edit?

**Comment by CarsonF** [comment]
Ahh. I'm going back to IRC!

**Comment by bobdenotter** [comment]
Ok, @dwolf555, so gd and curl are already implicitly required but other dependancies. If you leave in just the `"ext-pdo": "*",`, we'll merge this in. ^_^

**Comment by bobdenotter** [comment]
Whoop! Thanks!

**Pull request merged**
