### PR TITLE
Tweaking the layout of the debug toolbar, explicitly setting some styles

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Yolo-merging this, because it's pretty trivial.

**Comment by GawainLynch** [comment]
Ah yeah, sorry was dealing with fall-out from Slack installs and forgot :frowning:

**Comment by bobdenotter** [comment]
No worries. I merged it myself mere seconds after opening the PR.. I just wanted to have it "on record", instead of pushing to master directly. :-)

**Comment by GawainLynch** [comment]
Ah, you are correct (of course)… and yeah… :smile_cat:

**Pull request merged**
