### PR TITLE
Just a typo in german translation

### PR DESCRIPTION
**Pull request by sbani**
In german it's "der" not "de". 
Just look at the other "no-proper-type"

### CODE REVIEW

**Comment by rarila** [comment]
While at it: ``Bitte contenttypes.yml bearbeiten dies korrigieren`` doesn't sound that correct either ;-)

**Comment by sbani** [comment]
Yeah sounds strange. I will read the whole file later today

**Comment by sbani** [comment]
Updated the commit with new fixes

**Comment by rarila** [comment]
That's probably because I converted them from "du" to "sie" on the fly a while ago. Someone (can't remember his complete name at the moment) changed from "sie" to the even more formal "Sie". Also ok with me. I decided to use my time to code instead of translating as there are enough German non core devs around now. :)

**Comment by sbani** [comment]
Thanks.

I know my boss will task our working student to translate it. So there will be a translation from an expert.
I think we release next week. We won't have to wait that long :)

**Comment by rarila** [comment]
Perhaps we should add a ``de-de-du``, a  ``de-de-sie``and a  ``de-de-bigsie`` translation ;-)

**Comment by sbani** [comment]
Good idea. I will task her to do that when she's working on it. But we have to wait for release next week minimum.

**Comment by rarila** [comment]
You noticed the ``;-)`` ?

**Comment by sbani** [comment]
:) nope haha just thought: "Ok... as long as she's doing it and not me" :)

**Pull request merged**
