### PR TITLE
[4.0] Remove fields()

### PR DESCRIPTION
**Pull request by GawainLynch**
Per #6788

### CODE REVIEW

**Comment by rossriley** [comment]
candidate for :beer: merge

**Comment by GawainLynch** [comment]
@bobdenotter: When the results of 6788 are merged down later this week, I'll rebase and clean this up. :+1:

**Comment by bobdenotter** [comment]
As discussed, in general i'm agreeing with these changes. After rebase, it should be GTG, imho.

**Comment by GawainLynch** [comment]
Yeah, might also do it in a new PR, 'cause branch name … Will cascade the core branches shortly after I finish the docs ones :+1:

**Pull request closed without merging**
