### PR TITLE
Make addCss() and addJavascript() function declaration and handling consistent

### PR DESCRIPTION
**Pull request by GawainLynch**
There are several reasons that this got overlooked:
* Gnomes
* :koala:'s not having the right :leaves: 
* Coding sober

Depends on #3528

### CODE REVIEW

**Comment by bobdenotter** [comment]
Looks like some other commits snuck into this one.

**Comment by GawainLynch** [comment]
Yes, it depends on the 2.3 bits... I tagged it as such, in my defence :grin:

**Comment by GawainLynch** [comment]
Just thinking about it, if you're happy it's low enough risk, I can just rebase against master, amend the PHP comment and it can go into 2.2... Easy. 

I just thought it was late in the game for 2.2, but it would give us consistency of this two functions.

**Comment by bobdenotter** [comment]
Mergin' in!

**Pull request merged**
