### PR TITLE
Don't save password field on failed login attempts

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by GawainLynch** [comment]
@rarila I am wondering if this was what you were hitting too!

**Comment by Boorj** [comment]
:+1:  yoohoo!

**Comment by bobdenotter** [comment]
:green_apple: :green_book: :green_heart: :tea: :recycle: GREEN ALL ACROSS THE BOARD! :green_apple: :green_book: :green_heart: :tea: :recycle:

**Comment by GawainLynch** [comment]
@bobdenotter: You actually found *every* green emoji… I am impressed!

**Pull request merged**
