### PR TITLE
Added protip for testing email settings.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Can… happy… to commit… but the original idea for that route was a work-around until we implemented something in the admin area that allowed it to be done more simply… thoughts?

**Comment by GawainLynch** [comment]
My worry being BC

**Comment by bobdenotter** [comment]
When we get around to doing that, we remove it again from the .dist file, imho. 

This trick was _very_ convenient when helping krands debug his issues yesterday (forms wouldn't email, and he didn't know if it was forms, or mail itself that was broken)

**Comment by CarsonF** [comment]
Yeah I worry about BC too. Once the user does first install that comment is in their config forever, even after major version updates.

**Comment by bobdenotter** [comment]
I'm open to better suggestions. ^_^

**Comment by bobdenotter** [comment]
closing this one for now.

**Pull request closed without merging**
