### PR TITLE
Don't re-fetch record on preview

### LINKED ISSUE #5146: [BUG] Preview page with not publish status catch Fatal error
When i want preview page and status now not publish (Timed publish, Not published, Draft) - Controller generate error: 
```
PHP Fatal error: Bolt core
Error: Call to a member function setFromPost() on a non-object
File: /src/Controller/Frontend.php
Line: 203
````

Details
-------
 - Relevant Bolt Version: master
 - Install type: Github checkout
 - PHP version: 5.5

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #5146

### CODE REVIEW

**Comment by bobdenotter** [comment]
I seem to recall there was a very specific reason that we _did_ re-fetch the record on preview. I'mma think 'bout this.

**Comment by joshuan** [comment]
@bobdenotter blame say that added because #4044

**Comment by SahAssar** [comment]
I'm pretty sure that the reason was specifically for inbound relations, since outbound relations will be present in the post data anyway.

**Comment by bobdenotter** [comment]
Looks good to me (after last commit!)

@joshuan Yes, that's the one! :-)

@SahAssar Yes, correct. :-)

**Pull request merged**
