### PR TITLE
Clarify error message for missing assets in extensions.

### PR DESCRIPTION
**Pull request by bobdenotter**
We assume that the action to take is evident, but in practice it needs pointing out quite often.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Currently, the only way I know is by "Removing and re-adding the extension", because you can't trigger the process using one of the `app/nut` commands. Right, @GawainLynch ?

**Comment by GawainLynch** [comment]
Yeah, we're not offering any "sync" so that part is incorrect to add.

**Comment by CarsonF** [comment]
Technically, for managed extensions, there's no need to. As their assets should be static, not changing, and they are synced when installed or updated.

**Comment by bobdenotter** [comment]
Updated.

**Comment by CarsonF** [comment]
Shouldn't this exception only show up for extension devs that make a mistake specifying their assets?

**Comment by bobdenotter** [comment]
In an ideal world, yes. I've had it happen a few times though, that i "lost" my assets. Often my own fault, but the pointer makes sense.

**Comment by CarsonF** [comment]
I just worry that this is now misguiding extension devs

**Comment by bobdenotter** [comment]
I think the current version is OK. Let's merge it, and onwards. :-)

**Comment by GawainLynch** [comment]
Well, I am not seeing the confusing part myself … but the ordering is wrong. The bulk of our users should be using normal extensions, so should be mentioned first IMHO.

**Comment by bobdenotter** [comment]
> The bulk of our users should be using normal extensions, so should be mentioned first IMHO.

Agreed, but it will happen a _lot_ less often with managed extensions, while it happens quite often when someone is poking around creating their own. That's why I put the usecase i expect happens most at the front.

**Comment by GawainLynch** [comment]
> Agreed, but it will happen a lot less often with managed extensions

Where are we setting up the tally board?

It's a system log message … better one's in later PRs welcome I guess.

**Pull request merged**
