### PR TITLE
Refactoring getUser

### PR DESCRIPTION
**Pull request by Shyim**
Hey,
i have refactored the getUser function to make it effective when a single user will be getted

### CODE REVIEW

**Comment by bobdenotter** [comment]
It seems your changes caused a few regressions: https://travis-ci.org/bolt/bolt/jobs/59294637#L3460

Could you look into this? :-)

**Comment by Shyim** [comment]
i have no idea why the phpunit fails.
i have diffed the output of the function before the change and after its the same output on every test.

**Comment by GawainLynch** [comment]
I'll have a look for you, I am pretty sure I know what needs to be done it is just fiddly and will probably need to wait until the weekend… someone bug me on Sunday if this isn't fixed :grinning:

**Comment by GawainLynch** [comment]
Pulled locally and tests updated.

**Pull request merged**
