### PR TITLE
Timed publishing fix

### LINKED ISSUE #4139: Timed Publication timezone issue
Hello,

Server and bolt.cm have the same timezone and output the same time to me. 

When I set the publication date to (now + 1 minute) and the status to "Timed publish" it doesn't work. 

I have to subtract 2 hours to make it work.

I am in the timezone `Europe/Berlin`. 

Any other places where I have to check the timezone?

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #4139

Tested on
- PostgreSQL
- MySQL
- Sqlite

### CODE REVIEW

**Comment by bobdenotter** [comment]
Good find, mate! :+1:

**Comment by rarila** [comment]
Not tested on ``KoalaSQL``? \*duck\*

**Comment by GawainLynch** [comment]
> Not tested on `KoalaSQL`

Yeah, I already know how it goes on :koala:SQL 

Maybe we should check MongoDB though :stuck_out_tongue_closed_eyes:

**Comment by bobdenotter** [comment]
Whoop whooop!

**Comment by PhillippOhlandt** [comment]
+1

**Pull request merged**
