### PR TITLE
Optimisation for backend by caching requests for users.

### PR DESCRIPTION
**Pull request by bobdenotter**
As pointed out by @rossriley: No need to fetch users every single time. This PR fetches them once, and returns from memory if possible. This yields a significant improvement in queries / time taken. 

Before: 

screenshot 2015-07-20 20 11 16

After: 

screenshot 2015-07-20 20 25 29

### CODE REVIEW

**Comment by bobdenotter** [comment]
Would you look at that! 

screenshot 2015-07-20 22 10 57

**Comment by rossriley** [comment]
Can we have 2.2 version too... this is awesome.

**Comment by bobdenotter** [comment]
@rossriley Surely. I'll backport this to 2.2.x after it has landed.

**Comment by GawainLynch** [comment]
Just a few issues I a looking at :grin:

**Comment by GawainLynch** [comment]
@bobdenotter acceptance tests were broken due to the permissions changes. I have modified the flow a bit and it passes locally… So back over to you for approval I guess.

**Note:** With your original changes, we already know if we have a `\Bolt\Content` object and `isAllowedSingle()` only cares about the owner ID at that point anyway, which we will have if either an object of array has been passed into `isAllowed()` in the first place… so we're not needed to re-request the object at that stage… Query count unchanged.

**Comment by bobdenotter** [comment]
Hooray for teamwork! :tada:

**Comment by bobdenotter** [comment]
Booom!

**Pull request merged**
