### PR TITLE
Refactor Wars Episode I: The Phantom WSoD Menace

### LINKED ISSUE #4629: Replace our request caching with Symfony's HttpCache
Here are the problems I see with our current _request caching_ implementation:
1. Only _duration_ is supported for cache expiration. vs. HTTP protocol which supports timestamp and lifetime expiration and invalidation via ETags and last modified time.
2. Don't reinvent the wheel. Part of being *simple* for users/developers is less custom code.
3. It only works with routes that go through the [`Frontend`](https://github.com/bolt/bolt/blob/release/3.0/src/Controller/Frontend.php#L75-L81) controller as fetching the cached response is done there.
4. Separation of concerns. `Frontend` and `Render` should not need to know about caching as that is not their responsibility.

Symfony's [HttpCache](http://silex.sensiolabs.org/doc/providers/http_cache.html) is the answer. Heck we already load the [Silex integration](https://github.com/bolt/bolt/blob/release/3.0/src/Application.php#L160-L162) of it.

Setting the response cache headers also allows a _Gateway Cache_, such as _Varnish_, to be used. This is faster than _Symfony's HttpCache_, which is a _Reverse Proxy_.

As with lots of code changes for 3.0, the push is towards Bolt as a framework / platform. Leveraging this is another step in that direction. Not to mention less code, cleaner code, and moar better.

### PR DESCRIPTION
**Pull request by GawainLynch**
Turmoil has engulfed the Bolt Republic. 

The taxation of sanity due to outlying exception handling systems is in dispute.

Hoping to resolve the matter with a refactoring blockade of deadly commits, 
the greedy Request Cycle Federation has stopped early service execution to the 
small planet of Naboo.

While the congress of the Republic endlessly debates the alarming chain of 
events that led to this branch, the Supreme Chancellor has secretly dispatched 
two Jedi Knights, the guardians of peace and justice in the galaxy, to finish the 
branch and resolve the conflict…

qui-qonjin

Backstory
-------------

This branch does several things:
* Move the exception handling to Symfony
* Post-configuration exceptions are sent to a controller and rendered
* Made "lazy" proxies for several services so their constructors are not involed before boot
* Remove internal use of LowlevelException & LowlevelDatabaseException 
* Move system configuration checks into the request cycle (except configuration file existence)
* Performance gains

**NOTE:** This is only Phase I and there will be more to come. Specifically I will need to collaborate with the UI team to get the Twig templates sorted properly

Changelog
--------------

- Fixed: Database is no longer initialised prior to boot
- Fixed: System checks now run at start of request cycle
- Removed: Internal use of `LowlevelException` & `LowlevelDatabaseException` (See `BootException)`
- Removed: Internal use of `LowlevelChecks` (See `Validator)`
- Added: Exception controller to display error pages rendered from Twig templates
- Added: `debug_error_use_profiler` option to replace Whoops! with Symfony Profiler page
- Added: Lazy loading service provider for EntityManager
- Added: Lazy loading service provider for SchemaManager

**Updated**

- Added: Twig, Doctrine, Bolt & request caching done per-environment, and per service
- Added: Symfony HTTP Cache for request caching (replaces Doctrine file cache use)

Closes #4629

### CODE REVIEW

**Comment by bobdenotter** [comment]
Awesome! 👍

**Comment by SahAssar** [comment]
I propose we use :frog: instead of :koala: from now in since the gungans have apparently appeared in the bolt universe now. :+1:

**Comment by rarila** [comment]
> … I will need to collaborate with the UI team …

Fear is the path to the dark side.

**Comment by rarila** [comment]
> This is only Phase I and there will be more to come. Specifically I will need to collaborate with the UI team to get the Twig templates sorted properly.

Don't get technical with me. What mission? What are you talking about? I've just about had enough of you. Go that way, you'll be malfunctioning in a day you near-sighted scrap pile.

**Comment by jkazimir** [comment]
Where are my Gungans!? 😱

**Comment by bobdenotter** [comment]
Merging in! Whooooop! 💯

**Pull request merged**
