### PR TITLE
Washers for Bolt's Nuts

### LINKED ISSUE #3172: Cannot write to log from nut command
Hi, Bolt team!! Latest Bolt 2.1.3 here.

When I try to write to the system log (with the new Monolog implementation) from a nut command, nothing gets writen. Debugging  'Logger\Handler\SystemHandler::write()'  I can see that the following code is eating an exception with message **"Accessed request service outside of request scope. Try moving that call to a before handler or controller."**

```php
        try {
            $this->app['db']->insert(
                $this->tablename,
                array(
                    'level'      => $record['level'],
                    'date'       => $record['datetime']->format('Y-m-d H:i:s'),
                    'message'    => $record['message'],
                    'ownerid'    => isset($user['id']) ? $user['id'] : '',
                    'requesturi' => $this->app['request']->getRequestUri(),
                    'route'      => $this->app['request']->get('_route'),
                    'ip'         => $this->app['request']->getClientIp(),
                    'context'    => isset($record['context']['event']) ? $record['context']['event'] : '',
                    'source'     => $source
                )
            );
        } catch (\Exception $e) {
            // Nothing.
        }
```
Of course I can't move the call to a before handler or controller because is being called from a nut command. 

I assume the problem is the three calls to `$this->app['request']`, that do not make sense from a CLI call.

### PR DESCRIPTION
**Pull request by GawainLynch**
* Fixes #3172
* Set $app['request'] in BaseCommand to enable logging and getContent() functionality in Nut commands
* Add an audit log wrapper function to BaseCommand
* Logs (by default) system modifying events in the system log
* Adds a 'nut' context to the system log UI
* PHPDoc love

### CODE REVIEW

**Comment by bobdenotter** [comment]
Sweet! :+1:

**Comment by magabriel** [comment]
You guys rock! Ability to call getContent() from commands is great for us
CLI-addicts.

**Comment by GawainLynch** [comment]
Yeah, it's been on my TODO forever… You might also then like what's [coming with this](https://github.com/bolt/bolt/compare/bolt:master...GawainLynch:feature/nut-database-record-import-export?expand=1)

**Comment by magabriel** [comment]
Great!

**Pull request merged**
