### PR TITLE
Fixing a link in the base-2016 theme

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Erm … this change was done in #5618 yesterday … or am I missing something?

**Comment by bobdenotter** [comment]
Seems like it was also fixed yesterday, but currently it's still in the codebase the wrong way: 

https://github.com/bolt/bolt/blob/release/3.0/theme/base-2016/partials/_recordfooter.twig#L16

I can't really see what went wrong in the history of that file, though. Werid.

**Comment by GawainLynch** [comment]
You reverted it here: a33b545a88044191710ca6b6cc392d19ae150cc6

No harm, no foul :smile:

**Comment by bobdenotter** [comment]
Dammit!  😂

**Pull request merged**
