### PR TITLE
[wip] Use 'ajaxy' save for "edit file" functionality.

### LINKED ISSUE #3500: Built in editor writes files with ^M line endings..
.. and it shouldn't

### PR DESCRIPTION
**Pull request by bobdenotter**
This feature allows "ajaxy save" for file edits. Major benefits of this: 

 - You can leave a page open in the browser, and do multiple quick edits to a single file, because you won't lose your cursor position after saving.
 - You can `undo` after saving. \0/

See the spiffy gif:

wlpcggwyrf

Fixes #3500

### CODE REVIEW

**Comment by bobdenotter** [comment]
@rarila I have one question for you, that i couldn't figure out: https://github.com/bolt/bolt/pull/3497/files#diff-335a7a0be4630b2099b188ba56f9de81R51

**Comment by GawainLynch** [comment]
OK, tests… fun…

For things like `BackendAdminCest::editConfigTest()` what you need to do is replace:

```php
$I->see("File 'config.yml' has been saved.");
```
with:
```php
$I->amOnPage('bolt/file/edit/config/config.yml');
```
That will refresh the page, and the tests below will verify that the changes "stuck"

**Comment by rarila** [comment]
@bobdenotter There is no ``bolt``. Global objects are uppercase: ``Bolt.data('editcontent.msg.saving')``

**Comment by GawainLynch** [comment]
l7gtc

**Comment by bobdenotter** [comment]
> $I->see("File 'config.yml' has been saved.");

@GawainLynch Is that true? After a successful save, these texts should be displayed (ajaxy) under the 'Save' button.

**Comment by GawainLynch** [comment]
True… the crawler doesn't understand JavaScript. When I have time and the 2.3 development slows down a bit I want to have a look at PhantomJS for testing that stuff, but for now this is what we'll need to do to ensure coverage.

**Comment by GawainLynch** [comment]
Ah, OK, the tests are expecting a `submit` and this changes it to a `button`… this kind of raises a problem. It's valid for the feature, but makes a chunk of functionality un-testable.

**Comment by GawainLynch** [comment]
OK, have a solution and tests are working better now. But in the process hit a bug in the PR. Shall dig deeper.

**Comment by GawainLynch** [comment]
OK so the relevant commits:
* [Tests](https://github.com/bolt/bolt/commit/ffefa0610cbe6889d85d5d916f425fd231ff5e41)
* [Bug](https://github.com/bolt/bolt/commit/56530c0c7f9854ed3b47f77bab09064d6a153f6b)

**Comment by GawainLynch** [comment]
Derp… just came back to this while porting to our branch and reliased it's still labelled "WiP"… :koala: :gun:

**Pull request merged**
