### PR TITLE
First round of fixes for Symfony deprecations

### PR DESCRIPTION
**Pull request by GawainLynch**
Lowers deprecation count from 340 to 182. c.f. #4508 

Requires #4698 first

### CODE REVIEW

**Comment by GawainLynch** [comment]
When do we drop PHP 5.4 again :frowning:

**Comment by bobdenotter** [comment]
With Bolt 3.0 ;-)

**Comment by GawainLynch** [comment]
Yeah, we can't remove the deprecations until we can't run the platform… makes perfect sense :frowning:

**Comment by ScreamZ** [comment]
Also need Symfony 2.8 for FQCN in addition to PHP 5.5+ ;)

**Comment by GawainLynch** [comment]
@ScreamZ master has been locked onto 2.8 for quite some time already.

**Comment by bobdenotter** [comment]
Whoop!

**Pull request merged**
