### PR TITLE
Update heredocs

### PR DESCRIPTION
**Pull request by CarsonF**

### CODE REVIEW

**Comment by GawainLynch** [comment]
All aboard HMS Obsessive :ship:

**Comment by CarsonF** [comment]
It would bug you more if your editor pointed it out to you! ha

**Comment by GawainLynch** [comment]
a) I am a crew member on HMS Obsessive
b) vi knows to stay out of my way

:grin:

**Comment by bobdenotter** [comment]
beaker

**Comment by CarsonF** [comment]
There's a difference between in your way and unable to help you catch your derps because you don't let it

**Comment by CarsonF** [comment]
@bobdenotter I'm taking that as "I love it, let's merge!"

**Comment by bobdenotter** [comment]
It's mainly: "Oh my gosh, I can't possibly overlook all of the changes in this PR. So dangerous!" ;-)

**Comment by GawainLynch** [comment]
> @bobdenotter I'm taking that as "I love it, let's merge!"

#1555...  all I am saying!

**Comment by tobias2k** [comment]
And meanwhile, here I am wondering why people still think it's OK to use heredoc syntax in 2015...

**Pull request merged**
