### PR TITLE
Update CKEditor to 4.5.2 and horizontal rulez!

### PR DESCRIPTION
**Pull request by rarila**
This PR is dedicated to a valuable, admirable and jocular person. May the ataractics help soon!

### CODE REVIEW

**Comment by GawainLynch** [comment]
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>

**Comment by GawainLynch** [comment]
Though, I am wondering where we draw the <hr>

**Comment by rarila** [comment]
As it seems, everywhere

**Comment by GawainLynch** [comment]
We should make PRs like this a <hr>

**Comment by rarila** [comment]
We have alternatives: :straight_ruler: :triangular_ruler:

**Comment by rarila** [comment]
>Nothing is as cool,
>as a horizontal rule.

**Comment by GawainLynch** [comment]
Those are the <hr>?

**Comment by GawainLynch** [comment]
Everybody wants to <hr> [the world](https://www.youtube.com/watch?v=ST86JM1RPl0)

**Comment by rarila** [comment]
What about Kangourules?

**Comment by rarila** [comment]
Shouldn't we instead link that HR button just [there](https://www.youtube.com/watch?v=BYufX9aMftc)?

**Comment by GawainLynch** [comment]
What the… did I just watch!

**Comment by rarila** [comment]
:notes:
I'm a rocker :metal:
I'm a ruler :straight_ruler: 
I'm a right out of controller :musical_note:
…

**Comment by GawainLynch** [comment]
Doesn't that cross the <hr>

**Comment by GawainLynch** [comment]
I am drawing a <hr> here and leaving this to @bobdenotter to merge :stuck_out_tongue:

**Comment by bobdenotter** [comment]
[Seven red lines](https://www.youtube.com/watch?v=BKorP55Aqvg).

**Comment by rarila** [comment]
Hold the <hr>

**Comment by GawainLynch** [comment]
@rarila that crossed the <hr>

**Comment by rossriley** [comment]
You Rule

**Comment by bobdenotter** [comment]
Whoop!

**Pull request merged**
