### PR TITLE
Cleanup and stuff.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Calling #1555 on this one!

**Comment by rarila** [comment]
ARGHL, @bobdenotter. Wanna kill the poor :koala: ?

**Comment by GawainLynch** [comment]
Haha… Return of the Plural! 

I blame… oh wait…

**Comment by rarila** [comment]
Alzheimer anyone?

**Comment by bobdenotter** [comment]
just me, forgetting to `git pull` first. It's fixed now.

**Comment by rarila** [comment]
The :koala: Is saved… phewww

**Pull request merged**
