### PR TITLE
[WIP] Refactor/mo widgets mo problems

### PR DESCRIPTION
**Pull request by bobdenotter**
Note: This is a **WORK IN PROGRESS**

Widgets
=======

Widgets in Bolt are small blocks of content, that can be used to display content. 

By design, the widget has no access to the context of the page it is being displayed on. This is because a Widget is a small block of content that can be placed on various locations on a website. This should work regardless of what's on the page. 
Or, to flip it around: If the contents of a widget would change according to what's on the page, it would become a part of the page itself, and strictly speaking it wouldn't be considered a 'widget' anymore. 

Allowing for widgets in your theme
----------------------------------

```
{{ widget('frontend', 'main_top') }}
```

You are free to choose any name for the `position`, but it is good practice to stick with the default names if possible. This way it'll be easier for developers to use extensions in your theme, without having to dig through the template code to find which widget areas are defined. 

Commonly used widget positions for the frontend are:

 - main_top
 - main_break
 - main_bottom
 - aside_top
 - aside_middle
 - aside_bottom
 - footer

Defined positions for the backend are:

 - dashboard_aside_top
 - dashboard_aside_middle
 - dashboard_aside_bottom
 - dashboard_below_header
 - dashboard_bottom
 - overview_aside_top
 - overview_aside_middle
 - overview_aside_bottom
 - overview_below_header
 - overview_bottom
 - editcontent_aside_top
 - editcontent_aside_middle
 - editcontent_aside_bottom
 - editcontent_below_header
 - editcontent_bottom
 - files_below_header
 - files_bottom
 - editfile_below_header
 - editfile_bottom
 - login_top
 - login_middle
 - login_bottom

CSS 
------

Styling widgets in your theme should be minimal. Every widget is rendered in a container that looks like this: 

```
<div class='widget {{ widget.class }}' id='widget-{{ widget.key }}' data-key='{{ widget.key }}'>
  [ Widget content goes here ]
</div>
```

You can style the widget holder and its contents in CSS. However, try to refrain from doing this too precisely, because you ultimately have no control over what will be displayed in the widget itself. 

At the same time, we urge widget developers to _not_ override used fonts, colors and text styles unless absolutely necessary. The less you change in the CSS, the more seemless the widget will integrate in websites. When it comes to widgets in the frontend, there are not many options to influence what they will look like, by design. 

 - You, as the template designer, merely allow for widgets to be added to the theme. 
 - The developer of the website determines _which_ widgets will be shown where on the site
 - The developer of the Widget Extensions makes the widgets work, regardless of where they are placed.

Adding widget functionality for extensions
------------------------------------------

To register a widget for use in an extension, use the following. 

```
            $widget = new \Bolt\Asset\Widget\Widget();
            $widget
                ->setType('frontend')
                ->setLocation('..')
                ->setCallback([$this, 'functionName'])
                ->setCallbackArguments($array)
                ->setDefer(true)
            ;
            $this->addWidget($widget);
```

If `defer` is true, the rendering of the widget is done in a seperate request, so it doesn't potentially block the rendering of the page. 
It does this by writing out an empty `<div>`, into which the rendered HTML is inserted via an ajax call. 

The cache duration, if set using `->setCacheDuration()`, keeps the rendered widget in cache for a set amount of time. This can be useful if the widget takes some time to render, but doesn't display real time information.

Note: It is the responsibility of the developer of the widget to check for authentication of a widget that is rendered 'defered' via Ajax. 

Note: You should not use 'defer' for the `login_top`, `login_middle` and `login_bottom` positions. If you use defer on those, they will not show up when you're not already logged on. 

Examples
-------------

### Adding a button to the backend, right above the footer on every page

Initialise the widget: 

```
        $widget = new \Bolt\Asset\Widget\Widget();
        $widget
            ->setType('backend')
            ->setLocation('footer')
            ->setCallback([$this, 'backendButton'])
        ;
        $this->addWidget($widget);
```

And add the callback function

```
    public function backendButton()
    {

        $html = sprintf("<a href='%s' class='btn btn-default'><i class='fa fa-%s'></i> &nbsp;%s</a>",
            $this->app['url_generator']->generate('dashboard'),
            'heart',
            'Click me!'
            );

        return $html;
    }
```

### Adding a widget to the sidebar on the dashboard

Add the widget: 

```
        $widget = new \Bolt\Asset\Widget\Widget();
        $widget
            ->setType('backend')
            ->setLocation('dashboard_aside_top')
            ->setCallback([$this, 'backendDashboard'])
        ;
        $this->addWidget($widget);
```

Add the callback function: 

```
    public function backendDashboard()
    {
        $currentuser = $this->app['users']->getCurrentUser();
        $twigvars = [ 'title' => "Hello, " . $currentuser['displayname'] ];

        $this->app['twig.loader.filesystem']->addPath(__DIR__);
        $html = $this->app['render']->render('assets/dashboard_widget_aside.twig', $twigvars);

        return $html;
    }
```

And create a template file like `assets/dashboard_widget_aside.twig`:

```
<div class="panel panel-default panel-news">
    <div class="panel-heading">
        <i class="fa fa-fw fa-smile-o"></i>
        {{ title }}
    </div>

    <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et certamen honestum et disputatio splendida! omnis est enim de virtutis dignitate contentio.
        </p>

        <p>
            <a href="{{ path('dashboard') }}" class="btn btn-secondary">
                <i class="fa fa-music"></i>
                Click me!
            </a>
            <a href="{{ path('about') }}" class="btn btn-default">
                <i class="fa fa-thumbs-up"></i>
                No, click me!
            </a>
        </p>

    </div>
</div>
```

The result of this is: 

screenshot 2015-10-18 09 57 07

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
nice!

**Comment by rarila** [comment]
I would vote for ``main`` instead of ``maincolumn``.

- Shorter
- Doesn't need to be a column in real
- Is more like footer, aside, …
- Fits html naming

**Comment by rarila** [comment]
I'd like to mentions, that when it comes to CSS for widgets in the backend there's also only hope ;-)
There's for sure a big refactor needed and we are far away from having something like a public "API" for CSS. So be warned and careful to watch out for changes.

**Comment by bobdenotter** [comment]
@rarila 

> I would vote for main instead of maincolumn.

Agreed. Consider it done.

**Comment by GawainLynch** [comment]
@bobdenotter it might be worth including that the widget also handles a (*lower priority*) `->setContent()` that allows passing in of HTML content directly.
```php
            $widget = new \Bolt\Asset\Widget\Widget();
            $widget
                ->setType('frontend')
                ->setLocation('..')
                ->setContent('<blink>Oh look… Shinies!</blink>')
                ->setDefer(true)
            ;
            $this->addWidget($widget);
```

Also we're currently not using named parameters in our Twig, and there is no `max` value anywhere… do we need one?
```twig
{{ widget(position = 'maincolumn_top', max = 3) }}
```

**Comment by bobdenotter** [comment]
> Also we're currently not using named parameters in our Twig, and there is no max value anywhere… do we need one?

We can always add that later. If there's need for it. On one hand, it might be nice to have, at the same time it might be hella confusing for endusers if the widgets are cut off for some (to them) unknown reason.

**Comment by SahAssar** [comment]
Just dropping by to say that I'm really looking forward to this, and that named parameters are awesome!

**Comment by GawainLynch** [comment]
Ha, well there you go, this does work:

```twig
{{ widget(type = 'frontend', location = 'main_top') }}
```

**Comment by bobdenotter** [comment]
Adding the rendered CSS gives a merge conflict. After merging in, we should rebuild CSS and JS.

**Comment by bobdenotter** [comment]
:traffic_light: :vertical_traffic_light: :traffic_light: :vertical_traffic_light: :traffic_light: :vertical_traffic_light: :traffic_light: :vertical_traffic_light:

**Pull request merged**
