### PR TITLE
[4.0] Deprecations removal

### PR DESCRIPTION
**Pull request by GawainLynch**
razors-edge

### CODE REVIEW

**Comment by bobdenotter** [comment]
Did you find that image in your copy of Dungeon Master's Guide™? 😉

**Comment by GawainLynch** [comment]
I totally had to put on Thunderstruck while submitting this one too :metal:

**Comment by bobdenotter** [comment]
screen shot 2017-09-12 at 17 13 34

👍

**Comment by GawainLynch** [comment]
You want to see what Ross, Carson & I have in store soon :wink:

**Pull request merged**
