### PR TITLE
Updating Grunt modules.

### PR DESCRIPTION
**Pull request by bobdenotter**
Updating some grunt modules, because the old ones weren't working on recent versions of Node/NPM.

Don't merge yet!

### CODE REVIEW

**Comment by bobdenotter** [comment]
@rarila I'm getting an error, when doing 'grunt updateLib'. Hopefully you know what's going on..

```
$ grunt libcssimg --verbose
```

```
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ default, docJs, docPhp, libcssimg, lintBoot, lintHtml, prepareCkeditor, updateBolt, updateLib

Running tasks: libcssimg

Running "libcssimg" task
Read css: ../view/css/lib.css
Reading ../view/css/lib.css...OK
Create dir: ../view/img/lib
Warning: URL not handled: ../lib/jquery-ui-1.10.3/images/ui-bg_flat_75_ffffff_40x100.png Use --force to continue.

Aborted due to warnings.
```

**Comment by rarila** [comment]
I should, as I have written this :-)

It happens [here](https://github.com/bolt/bolt/blob/v2.2.7/app/src/grunt/libcssimg.js#L56) and is where the css is checked for img urls, the img is copied and the url rewritten for the new path.

From just looking at the code and the error the path in css changed from ``url(lib/…`` to ``url(../lib/…`` for some reason. Further investigation needed…

**Comment by bobdenotter** [comment]
Bumping @rarila 

Could you look into this? It's pretty broken, and I can't package any 2.2.x releases if needed.

**Comment by rarila** [comment]
Simply change [libcssimg.js#L10](https://github.com/bolt/bolt/blob/release/2.2/app/src/grunt/libcssimg.js#L10)  to:

```javascript
            repl = {
                'jquery-ui':    /^\.\.\/lib\/jquery-ui-.+?\/images\/ui-/,
                'select2':      /^\.\.\/lib\/select2\//,
                'jquery-upl':   /^\.\.\/lib\/jquery-fileupload\/img\//
            },
```

Not further testet, but the error is gone and ``grunt updateLib -v`` displays nice values.

**Comment by bobdenotter** [comment]
This one should be done now!

**Comment by GawainLynch** [comment]
:+1:

**Pull request merged**
