### PR TITLE
Include Slack channel count badge

### PR DESCRIPTION
**Pull request by GawainLynch**
Tagging as an RFC as I have no great opinion on this one, just having fun and seeing what we can do.

The currently implemented options are:
  *  — Active users
  *  — Active/total ratio 
  *  — Total user count

### CODE REVIEW

**Comment by rossriley** [comment]
1-millionth-visitor

**Comment by GawainLynch** [comment]
I like Ross' suggestion better :stuck_out_tongue_winking_eye:

**Comment by bobdenotter** [comment]
I like options 1 and 3. 2 is nice 'n all, but the numbers don't really fit in the lozenge. ;-)

**Comment by GawainLynch** [comment]
Let me know which one, if at all, you want and I'll update or close the PR :wink:

**Comment by bobdenotter** [comment]
Can we make 2 a bit wider so it fits the text? If so, i'd like that one. If not, number 3.

**Comment by GawainLynch** [comment]
Yeah, it is just an SVG in `template/badge.svg.twig` in the Slack invites site repo, but I have no idea what I am doing with images, let alone SVGs. However, it should be a 10 second job for someone who knows what they are doing.

I even tried to use the Slack branding ones, but quickly found out that I was completely out of my depth versus the amount of time I had.

**Comment by bobdenotter** [comment]
Like so? https://github.com/bolt/bolt-slack-invites/pull/2

**Comment by GawainLynch** [comment]
Like that … deployed, so if you refresh this page you'll see the updated versions in the OP :smile: 

Thanks mate :+1:

**Pull request merged**
