### PR TITLE
Manual coverage testing

### PR DESCRIPTION
**Pull request by GawainLynch**
This change removes the code coverage from every PHPUnit run, and instead allows execution of a PHP script to test against both `master` and a PR's branch (plucked from a PR number).

```bash
php tests/scripts/coverage.php 3023
```
Optionally you can give the name (or path) of at directory in `tests/phpunit/`:
```bash
php tests/scripts/coverage.php 3023 Configuration
```
or a specific file:

```bash
php tests/scripts/coverage.php 3023 tests/phpunit/Configuration/ResourceManagerTest.php
```

And if changes in coverage are calculated, it will output to the console Mardown that can be pasted into the PR's discussion:

#### Totals
| Classes | Methods | Lines |
|---------|---------|-------|
| 15 | 24 | 13 |

#### Individual Classes
| Class | Methods | Statements |
|-------|---------|------------|
| \Bolt::Application | 12 | 11 |
| \Bolt::Config | 12 | 15 |
| \Bolt\Configuration::Composer | 22 | 5 |
| \Bolt\Configuration::ComposerChecks | 10 | 23 |
| \Bolt\Configuration::LowlevelChecks | 9 | 14 |
| \Bolt\Configuration::ResourceManager | 16 | 28 |
| \Bolt\Configuration::Standard | 13 | 15 |
| \Bolt\Exception::LowLevelDatabaseException | 23 | 5 |
| \Bolt\Exception::LowlevelException | 8 | 24 |
| \Bolt\Field::Base | 10 | 10 |
| \Bolt\Field::Manager | 16 | 10 |
| \Bolt::Library | 13 | 26 |
| \Bolt\Provider::ConfigServiceProvider | 22 | 22 |
| \Bolt\Provider::PathServiceProvider | 17 | 15 |

### CODE REVIEW

**Comment by GawainLynch** [comment]
**Note:** The numbers represent a +/- delta between master and the PRs branch.

**Comment by GawainLynch** [comment]
Build 4973

| PHP 5.3 | PHP 5.4 | PHP 5.5 | PHP 5.6 |
|-----------|------------|------------|------------|
| Time: 10.29 minutes | Time: 6.35 minutes | Time: 5.56 minutes | Time: 10.11 minutes |

Build 4974 (this PR)

| PHP 5.3 | PHP 5.4 | PHP 5.5 | PHP 5.6 |
|-----------|------------|------------|------------|
|  Time: 1.8 minutes | Time: 2.03 minutes | Time: 2.11 minutes | Time: 2.15 minutes |

**Comment by bobdenotter** [comment]
This is cool! :-)

**Comment by bobdenotter** [comment]
Whoop! Merging in!

**Pull request merged**
