### PR TITLE
update gruntfile for magnfic popup

### PR DESCRIPTION
**Pull request by cdowdy**
I forgot to commit the updated gruntfile when I updated magnific popup to 1.0.0.  

Also removed version number from the directory to make future manual updates easier (if not using a package manager like Bower or NPM )

### CODE REVIEW

**Comment by rarila** [comment]
@cdowdy I added them to make updating easier so that you can easily check what version is installed without reading readmes or sourcecode or where ever the version number could be hidden. I even compared sources with some libs where no version was given.

**Comment by cdowdy** [comment]
ahhhh ok that makes sense... Ill revert back to version numbers then !

**Comment by rarila** [comment]
Thx :-)

**Comment by bobdenotter** [comment]
Merging in! :+1:

**Pull request merged**
