### PR TITLE
Don't bind useragents as that is don now on the server

### PR DESCRIPTION
**Pull request by rarila**

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm slightly confused. What does this solve/fix? Or was it just unneeded?

**Comment by rarila** [comment]
Just unneeded. Was there to bind the useragent js stuff Wich is now done in php.

**Comment by rarila** [comment]
@GawainLynch If you find an "e", you can keep it! ;-)

**Comment by GawainLynch** [comment]
Oh look… pretty colours… /me starts to hug everyone

**Comment by bobdenotter** [comment]
Cool! Merging in!

**Comment by GawainLynch** [comment]
:bulb:

**Pull request merged**
