### PR TITLE
Update infos.ru.yml

### PR DESCRIPTION
**Pull request by skinysmn**
Added translation if image field information

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hey @skinysmn, @Boorj,

As you know, my knowledge of Russian is extremely limited. What should `разгуженных` say?

**Comment by Boorj** [comment]
@bobdenotter it's a typo
🚫 `разгуженных`  - incorrect letters order, no such word
✔️  `загруженных` - is correct and means "previously uploaded"

**Comment by horus68** [comment]
Not a russian speaker here but that string translation looks a little short in size and in formating keys.

The english original:
```
Use this field to upload a photo or image. Click the button to upload a file from your
computer, or if you're using a recent version of Chrome or Firefox, you can simply drag'n'drop the file
from your desktop or from a different browser window.<br>
Alternatively, you can use a previously uploaded image. To select a previously uploaded file, just
type (part) of the file name in the input area, and it will be autocompleted.
```
This PR translation (including @Boorj fix) would be:
`Используйте это поле для загрузки изображений или выбора ранее загруженных изображений. Для выбра ранее загруженных изображений, используйте кнопку "Выбрать из сервера" или начните вводить имя файла в поле "Путь до изображения".`

Just as a side note, some user has translated this (using Crowdin https://crowdin.com/translate/bolt ) as:

```
Используйте это поле, чтобы загрузить фотографию или изображение. Нажмите кнопку, чтобы загрузить файл с вашего компьютера, или если вы используете последнюю версию Chrome или Firefox, вы можете просто перетащите файл с рабочего стола или из другого окна браузера.<br>
Кроме того, вы можете использовать ранее загруженного изображения. Чтобы выбрать ранее загруженный файл, просто введите (часть) в имени файла в области ввода, для автозаполнения.
```
Master language for 3.4
https://github.com/bolt/bolt/blob/3.4/app/resources/translations/en_GB/infos.en_GB.yml#L4-L8

**Comment by Boorj** [comment]
@horus68 thanks for that link! I even wanted to suggest using transifex for the same purpose. 
1. I sent request to join team (to @bobdenotter )
2. Yes, in this version my translation is shorter, but my original text was also short ( was changing previous tranlation). Nothing about "chrome and firefox". Crowdin translation is better.

3. 
> Используйте это поле для загрузки изображений или выбора ранее загруженных изображений. Для выбра ранее загруженных изображений, используйте кнопку "Выбрать из сервера" или начните вводить имя файла в поле "Путь до изображения".

is translated as:
>    Use this field to upload images or selecting previously uploaded ones.  To select previously uploaded, use "Select from server" or start typing filename in "image path"

**Comment by bobdenotter** [comment]
I've ninja-fixed the typo in the patch, and will merge it in! Thanks! 👍 

For Bolt 4, we'll move to an online service to manage translations, but for Bolt 3.x this is not feasible. :-)

**Comment by GawainLynch** [comment]
> For Bolt 4, we'll move to an online service to manage translations, but for Bolt 3.x this is not feasible.

Just to add to this. A number of us spent a large amount of time trying to get this integrated into v3, but the required changes were just too much. That said, it is working perfectly in the v4 pre-alpha and we just need to decide *which* service will be used :smile_cat:

**Comment by Boorj** [comment]
@GawainLynch , no problem. I can help with translations, wherever it will be placed. Just tell me where (when?) to do that.

**Comment by GawainLynch** [comment]
We will do … it will still be some months away. We have a lot more work to do first.

We'll port as much of the translations initially that make sense, then put out a community call to get people to either translate and/or take responsibility for a locale. 

But I can tell you, as pointed out a while ago by @horus68, life is so much easier when it isn't something a translator has to use git to do :smile:

**Comment by horus68** [comment]
@GawainLynch 
> We'll port as much of the translations initially that make sense, then put out a community call to get people to either translate and/or take responsibility for a locale.

If you want to use any other service to translate you can download actual translations from Crowdin. Only the translated strings will be downloaded, no need to loose any part of it.

@Boorj I already approved you on Crowdin.
I also used Transifex for Bolt but it wasn't ready yet for the Bolt 2.x language versions. So went on and created the Crowdin project befor version 3. It works out of the box, no need to change anything!
It was not included in the official Bolt release system but that is a long story (parts already explained, others are in some old issue/RFC in github).
I don't care what system will be used, but it needs to be a platform created for translators, not coders!

**Comment by GawainLynch** [comment]
@horus68 Yeah cool, thanks for the heads-up but not where I was going. Basically, the keys themselves are a mess and are not relevant in v4's work as already the changes are quite extensive. I have a migration script that processes and attempts a "best match" … right now it is hooked up to Transifex, but that is not set in stone, just what worked best for the early development workflow.

**Comment by horus68** [comment]
If you upload a new master language file to Crowdin (and do not delete the old file) allstrings with  same values (same words to translate) will get reused from the old file, even if the key part is a different one.
It only works if the value (english words to be translated) are 100% the same.

So no translations will be lost.
So maybe before making new translation files with your script just release the new master file and I will pass it by Crowdin to test.

**Comment by GawainLynch** [comment]
Yes, same with Transifex … but it is a structural problem. The strings were all built using (and abusing) structure. We're removing that NIH approach.

We will lose very little, in fact, what we will lose is just because the structure and/or intent of the message has changed … they are presently the small group … e.g. pluralisation in v3 is done is separate strings, in v4 it is handled gracefully in one string so languages, where it matters, can cope gracefully without having to be forced into English idiomatic expression.

**Pull request merged**
