### PR TITLE
converting front-end JS to bower

### PR DESCRIPTION
**Pull request by cdowdy**
related to: https://github.com/bolt/bolt/issues/2628  

created  
* ```.bowerrc``` file to tell where to install bower components.   
* ```bower.json``` for bower dependencies  
* updated ```lib.js``` with new bower included files  

I've deliberately only added a few files to keep possibly breakage at a mininmum. I diffed these and they weren't custom versions.  

```bootbox.js ```, ```jquery-cookie```, ```jquery.formatDateTime``` and tagcloud are all "locked" to their current version used in bolt inside bower.json.  

This will need to be thoroughly checked before commited :(. Is it more suited toward the canary branch?

### CODE REVIEW

**Comment by bobdenotter** [comment]
Sweet! 

> app/view/lib/tmp/bower-assets.js

Should that file be committed to git?

**Comment by cdowdy** [comment]
> Should that file be committed to git?

I have that there just to mirror the other files in ```lib```.  It doesn't need to be there since its included into lib.min.js. I committed it just in case anyone came across and wondered "where the hades is magnific coming from" since bower_components isn't committed.  

in short no it doesn't need to be committed really haha

**Comment by rarila** [comment]
I would either put ignore the tmp folder or run a delete target on it after run. But I think the whole process can streamlined a bit anyway probably by minify everything and get a sourcemap for free without the need for a tmp file at all. Will eventually have a look into it after merge.

**Comment by bobdenotter** [comment]
In that case.. Merging in, and we'll finetune as we go along. Thanks again, @cdowdy

**Pull request merged**
