### PR TITLE
Make translations overridable

### PR DESCRIPTION
**Pull request by fabschurt**
See #3553 for the initial discussion.

I've added a test case to validate this new functionality, and also 2 other test cases covering the existing behavior of `TranslationServiceProvider`.

Let me know what you think about this.

### CODE REVIEW

**Comment by rossriley** [comment]
Looks good to me :+1:

**Comment by fabschurt** [comment]
Scrutinizer seems angry, I'ma check if I can do something about it.

**Comment by GawainLynch** [comment]
Scrutinizer is just getting upset about the cyclomatic complexity of `addResources()` due to the internal loop.

**Comment by fabschurt** [comment]
Ah, right, so… I don't think there's actually something we can do about that, as 2-level iteration is required here AFAIK.

**Comment by rossriley** [comment]
Yes ignore scrutinizer, it just needs some :beers: and to chill out more.

**Comment by rarila** [comment]
Better let it continue complaining and drink the :beers: yourself :)

**Comment by fabschurt** [comment]
Yeah it kind of reminds me of a grumpy old man, never satisfied about anything :older_man:

**Comment by fabschurt** [comment]
(Just force-pushed a modification to a DocBlock description.)

**Comment by GawainLynch** [comment]
For the sake of the academic conversation… the best approach is generally to break the inner loops out into methods as that makes them easier to examine in a debug context.

With this, that's largely just :cow:

**Comment by fabschurt** [comment]
Yeah I guess the cyclomatic complexity could've been reduced by using `array_filter()` and `array_walk()` for example; it'll be something for me to keep in mind in the future. The use of the `foreach`/`if`/`continue`/`break` idiom is kind of a widespread bad habit in the PHP ecosystem, but the language doesn't exactly make the use of internal iterators very developer-friendly, as opposed to Ruby for example.

**Comment by GawainLynch** [comment]
Hashmaps for the win! The performance gain is quite noticeable for **hot paths**… For every thing else readability of code is often a bigger concern. 

Personally, I like to split logic out and keep functions small as dump()ing a value returned is much easier than dozens of iterations… But that is just my OCD and most certainly not a project requirement.

**Comment by fabschurt** [comment]
I feel you mate, don't even get me started on _my_ OCDs :smile:

**Comment by rarila** [comment]
I more and more get the feeling that Bolt is a collecting basin for OCD affected people.

**Pull request merged**
