### PR TITLE
Require Silex WebProfiler ^1.0.6

### PR DESCRIPTION
**Pull request by GawainLynch**
…would you like some derp with that derp, sir?

### CODE REVIEW

**Comment by GawainLynch** [comment]
Putting a hold on this, as it requires this [PR to be merged](https://github.com/silexphp/Silex-WebProfiler/pull/60) upstream and a version tag.

**Comment by GawainLynch** [comment]
I've updated this to use a temporary, patched, WebProfilerServiceProvider until upstream patches and releases their currently broken version.

This will get it in and working for now, but we won't go to release (unless Fabien takes a couple of months) with this patched class.

Oh… and, why are we using Scrutinizer again?

**Comment by bobdenotter** [comment]
Merging in.. We should just not forget to revert this when the change is done upstream.

**Comment by GawainLynch** [comment]
You really think @CarsonF would let me forget? :stuck_out_tongue:

**Pull request merged**
