### PR TITLE
Fixes for Twig strict-mode with repeater groups

### PR DESCRIPTION
**Pull request by rossriley**
Pinging @bobdenotter @EJanuszewski for test please.

Hopefully Fixes: #4907 

Adds some auto defaults to the base default array that should prevent Twig choking in strict mode.
Also fixes an access issue for the date field which was also causing a failure in strict mode.

### CODE REVIEW

**Comment by GawainLynch** [comment]
@rossriley fixes it for me

**Comment by bobdenotter** [comment]
Works for me, too! :+1: 

Let's see if @EJanuszewski chimes in. He had a different error than Gawain and I got.

**Comment by EJanuszewski** [comment]
Oo I feel special getting pinged :D I shall test it out, although it will be a different environment as I got the error at work, I can test here at home and at work in the morning

**Comment by rossriley** [comment]
pinging @EJanuszewski just because.

**Comment by EJanuszewski** [comment]
@rossriley Getting the same error as I did at work, updated to this and still get the same error, maybe just do it as a separate issue though since it seem unrelated?

```
Impossible to access an attribute ("getEmptySet") on a string variable ("") in "@bolt/editcontent/fields/_repeater.twig" at line 26
```

**Comment by rossriley** [comment]
@EJanuszewski can you paste the contenttypes.yml part where your repeaters are defined and I'll try and reproduce. It's probably just a combination of configs I've not tested against.

**Comment by EJanuszewski** [comment]
@rossriley As far as I was aware mines standard from the master branch, here's the repeater section anyway

```        repeater:
            type: repeater
            group: repeater
            limit: 3
            prefix: "<p>This allows you to create multiple sets of fields. Use the add button at the bottom to create a new empty set.</p>"
            fields:
                repeattitle:
                    type: text
                repeatimage:
                    type: image
                    extensions: [ gif, jpg, png ]
                repeatcontent:
                    type: html
```

and whole config if its useful http://pastebin.com/raw/Jhp2uwjy

**Comment by rossriley** [comment]
Thanks, I think I've got it now. The latest push should make sure we catch that error now.

**Pull request merged**
