### PR TITLE
Feature/password strength indicator

### PR DESCRIPTION
**Pull request by bobdenotter**
This PR adds a password strength indicator, for when you’re adding the first user, or adding new users. No hard cutoffs, just a nudge to let people input a bit more complex passwords.

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
:+1:

**Comment by GawainLynch** [comment]
I, for one, welcome our new password overlords!

**Comment by GawainLynch** [comment]
Just noting, this is not a feature… it is a bug fix… :wink:

**Comment by rarila** [comment]
@bobdenotter Any chance to pull this without ``napa`` because that one already booked a flight :airplane: to visit Dodo and friends over xmas :santa:?

… and why is there no Dodo emoji?!

**Comment by rarila** [comment]
… and does the bar extend to the left on ``12345678``, ``password``, ``qwerty`` and `kittens?``

**Comment by SahAssar** [comment]
rarila: What about `hunter2`?

**Comment by rarila** [comment]
@SahAssar Not that one. My OCD prefers seeing a nice aligned bar when typing in the password …




… who did say this?!

**Comment by bobdenotter** [comment]
> Any chance to pull this without napa because that one already booked a flight :airplane: to visit Dodo and friends over xmas :santa:?

Sure. What should i do instead? Complexify has no real NPM package, so just include the files in `app/src/lib`?

**Pull request merged**
