### PR TITLE
Updating default `debug_error_level` from `6135` to `8181`.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
Well, on 3.2 if you have it turned up that high, Symfony converts errors to exceptions … so do this with caution :smile:

**Comment by bobdenotter** [comment]
@GawainLynch it's `8181` in `config.yml.dist as well, so it makes sense that they're consistent, at least. https://github.com/bolt/bolt/blob/release/3.1/app/config/config.yml.dist#L261

**Comment by GawainLynch** [comment]
Yeah, but we still might want to tone down the default, and advise people tracing issues to turn it up.

**Comment by bobdenotter** [comment]
Actually, this is "toning it down" compared to the previous version, right? 

previous: "all, but not notices and deprecations" 
new: "all, but not notices, deprecations and also not warnings"

**Comment by GawainLynch** [comment]
Possibly… But I've been having to wind my setting down at certain times lately on `release/3.2`+.

**Comment by bobdenotter** [comment]
I'm not at all against reviewing the setting for 3.2, but I think this PR _does_ make it more consistent for 3.1.. And when we update for 3.2, it'll be easier to find the two same values to update them to whatever we choose to set it to. ;-)

**Comment by GawainLynch** [comment]
There you go with the logic again… :stuck_out_tongue_winking_eye:

**Pull request merged**
