### PR TITLE
[Extension] Add a trait to simplify extensions to add tables

### PR DESCRIPTION
**Pull request by GawainLynch**
Allows:

```php
    /**
     * {@inheritdoc}
     */
    protected function registerExtensionTables()
    {
        return [
            'my_table' => new MyTable(),
        ];
    }
```

**DISCLAIMER:** This is the shorthand version (that will still work), however tables should ideally be DI objects.

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
That's cool. Can it also override existing table schemas to add columns? (Like for the users table)

**Comment by GawainLynch** [comment]
Not specifically with the trait right now… but extending/overriding existing `Pimple`s will work fine.

i.e. Very doable, needs documentation, and agreements what we're publishing as supported for v3 :grin:

**Comment by PhillippOhlandt** [comment]
Ah ok. The ability to add contenttypes itself would be cool to, if not implemented yet.

**Comment by GawainLynch** [comment]
That *can* be done now, we load early enough now that a ContentType can be appended to the `Config` array… but you want to know what you're doing :grin:

**Comment by PhillippOhlandt** [comment]
That's nice! I can use it at work to do as much as I can inside my Extension. That would be also good for Extensions like BoltBB, right?

**Comment by bobdenotter** [comment]
Aight. :+1:

**Pull request merged**
