### PR TITLE
TemplateView

### PR DESCRIPTION
**Pull request by CarsonF**
In regards to #6382

Working on how this can be done without breaking BC, but it's proving challenging.

The only response method called in Frontend was the `X-XSS-Protection` header in record route. So I moved it out.

Now you can do something like:
```php
class MyFrontend extends Frontend
{
    protected function render($template, array $context = [], array $globals = [])
    {
        return new TemplateView($template, array_replace($context, $globals));
    }
}
```

and then replace the `controller.frontend` service with that class.

Open to ideas about how to integrate this further. I don't think changing `Controller\Base::render` directly is wise though, since others can base their controllers on it. But maybe if it's something just for Frontend / Backend classes that would be ok. I'm not sure if a separate shortcut even makes much since given how terse the line actually is.

### CODE REVIEW

**Comment by CarsonF** [comment]
`TemplateView` allows template & context to be _modified_ before it is rendered.
`TemplateResponse` allows _read-only_ access to template & context but also allows modification to the response headers or body (string).

Let me give some examples of how this can be used.

Say you want to modify a record:
```php
$app->view(function (TemplateView $view, Request $request) {
    if ($view->context->has('record')) {
        $record = $view->context->get('record');

        // modify record

        $view->context->set('record', $record);
    }
}, 10 /* above default */);
```

Say you want to add a header for a certain record:
```php
$app->after(function (Request $request, Response $response) {
    if ($response instanceof TemplateResponse) {
        $context = $response->getContext();
        $record = isset($context['record']) ? $context['record'] : null;

        if (/* if record is foo */) {
            $response->headers->set('Foo', 'Bar');
        }
    }
});
```

Either of these could be used to retrieve the `record` and do something with it.

**Comment by SahAssar** [comment]
👍 This looks great!

**Comment by GawainLynch** [comment]
FWIW the conceptual approach, as it stands, has my :+1:

**Comment by GawainLynch** [comment]
Welcome to Monday, @CarsonF … Your friendly, weekly, "already-asking-too-much-of-a-person" nudge on this :hugs:

**Comment by bobdenotter** [comment]
No movement on this for 5 weeks. Please don't forget, @CarsonF. :-)

**Comment by CarsonF** [comment]
There is, it's just local. Haven't forgotten.

**Comment by CarsonF** [comment]
This is ready for review now.

**Comment by bobdenotter** [comment]
As discussed during the dev-meeting: :shipit:

**Pull request merged**
