### PR TITLE
Remove nodes from contenttypes.yml

### PR DESCRIPTION
**Pull request by SahAssar**
Remove documention of YAML nodes from contenttypes.yml per #5164 and since it is documented here: https://docs.bolt.cm/release-2-2/contenttypes-and-records#advanced-yaml-repeated-nodes

### CODE REVIEW

**Comment by GawainLynch** [comment]
Just had a water cooler with @bobdenotter about this.

This was added in #3430 with the intent of *also* matching what is in the docs. The discussion at the time was that like the field examples below, it would be useful for the "lazy" type person who doesn't go to the docs.

An example given of the "lazy" type would be people like Bob & I who use the commented routes in `app/config/routing.yml`

That given, @SahAssar, do you still feel there is a valid reason to remove this?

**Comment by SahAssar** [comment]
@GawainLynch well, considering that after config.yml this is the file that is most likely for a newbie to edit I think there is a case that something that the docs puts under the section "Advanced" should not be there. But if we keep it I think we should move the "Possible field types" section above it.

**Comment by bobdenotter** [comment]
> But if we keep it I think we should move the "Possible field types" section above it.

I could live with that. :+1:

**Comment by SahAssar** [comment]
Closing cause #5176

**Pull request closed without merging**
