### PR TITLE
All uploaded files will be lovercase now

### PR DESCRIPTION
**Pull request by jirimedved**

### CODE REVIEW

**Comment by bobdenotter** [comment]
I'm not sure this is a good idea. Why should all files be lowecased?

**Comment by jirimedved** [comment]
Ok, I understand. My problem is with uppercase name extension files (example: JPG, JPEG), I solved it this way :).

**Comment by bobdenotter** [comment]
Hmm, lowercasing the _extension_ only might not be a bad idea. :-)

**Comment by GawainLynch** [comment]
@jirimedved you can already set this in [config.yml](https://github.com/bolt/bolt/blob/master/app/config/config.yml.dist#L151)
```yaml
upload:
  pattern: '[^A-Za-z0-9\.]+'
  replacement: '-'
  lowercase: true
```

Also there is already a call to `setSanitizerCallback()` on line 38, so the one your adding doesn't do anything as it will get overridden by that one, which is configurable.

**Comment by jirimedved** [comment]
@GawainLynch Hm, but it does not work ... (items in config.yml uncommenting )

**Comment by GawainLynch** [comment]
I blame @GawainLynch then… /me shakes his fist at himself

Seriously though, are you on 2.0.x or master?  It was updated no long ago as Adrian added the `setSanitizerCallback()` feature for me a few weeks ago. I just tried it on master and it works for me:
upload

**Comment by jirimedved** [comment]
@GawainLynch Master ...
screenshot_3ku3ue

**Comment by GawainLynch** [comment]
Hmm. Are you sure you're not using modified code?  The '_' is staying there which suggests to me it isn't hitting the regex.

**Comment by bobdenotter** [comment]
Works for me too: 

screen_shot_2015-02-23_at_08_36_22

**Comment by rarila** [comment]
Besides of all boring techno babble… ;-)
I love it: **lover**case :cupid:

**Comment by tobias2k** [comment]
Hey, the **love** parade is probably the world's most famous techno
event... totally appropriate IMO...

On Mon, Feb 23, 2015 at 02:48:51AM -0800, rarila wrote:
> Besides of all boring techno babble… ;-)
> I love it: **lover**case :cupid:
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/pull/2889#issuecomment-75521702

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by jirimedved** [comment]
My fault, sry ...

**Pull request closed without merging**
