### PR TITLE
[4.0] Switch silex/web-profiler to 1.0.x-dev

### PR DESCRIPTION
**Pull request by GawainLynch**
The silex/web-profiler 1.x branch has commits above 1.0.8 that adds compatibility with the remaining Symfony 3.x components.

### CODE REVIEW

**Comment by CarsonF** [comment]
Does it not require pimple v3?

**Comment by GawainLynch** [comment]
Nope … only Silex 2 … this is all Silex 1.x based and there is an upstream issue about the test breakage, and I am guessing the next stable 1.x version is not too far away.

**Comment by CarsonF** [comment]
Silex 2 requires pimple 3. Are you saying it requires silex 1?

**Comment by GawainLynch** [comment]
> Silex 2 requires pimple 3. Are you saying it requires silex 1?

So the title of this PR is 

> [4.0] Switch silex/web-profiler to 1.0.x-dev #6106

The (current) diff is:

```diff
diff --git a/composer.json b/composer.json
index fa2235a..0719d31 100644
--- a/composer.json
+++ b/composer.json
@@ -28,7 +28,7 @@
         "PasswordLib/PasswordLib": "^1.0@beta",
         "php": "^5.6 || ^7.0",
         "silex/silex": "^1.3",
-        "silex/web-profiler": "^1.0",
+        "silex/web-profiler": "1.0.x-dev",
         "siriusphp/upload": "^1.3",
         "stecman/symfony-console-completion": "~0.7",
         "swiftmailer/swiftmailer": "^5.4",
@@ -39,11 +39,11 @@
         "symfony/options-resolver": "^3.0",
         "symfony/process": "^3.0",
         "symfony/security": "^3.0",
-        "symfony/stopwatch": "^2.8",
+        "symfony/stopwatch": "^3.0",
         "symfony/translation": "^3.0",
         "symfony/validator": "^3.0",
         "symfony/var-dumper": "^3.0",
-        "symfony/web-profiler-bundle": "^2.8",
+        "symfony/web-profiler-bundle": "^3.0",
         "symfony/yaml": "^3.0",
         "tdammers/htmlmaid": "~0.7",
         "twig/twig": "^1.28",
```

I am lost where Silex 2 comes into this :smile: 

:coffee: ?

**Comment by CarsonF** [comment]
Sorry the `^1.0` -> `1.0.x-dev` tripped me. Why not `^1.0@dev`?

**Comment by GawainLynch** [comment]
> Why not ^1.0@dev

Well, I had this debate with Rob in the Composer channel the other day, and apparently it doesn't matter … as you'd see from the fact that it installs … and this is for a long term dev branch.

That said, my OCD matches yours in this case and I might just update this to be the same way. This PR is going to be a WiP for a bit in order to get tests passing, as we need to make some changes in the 3.x branch and have that cascade down. Consider it done :wink:

**Comment by GawainLynch** [comment]
@bobdenotter I have rebased this to leave `symfony/web-profiler-bundle` at `^2.8` _for now_, as there are a bunch of changes we need in our Twig handling first, and they need to go into a v3 branch and come down from there.

This should be GTG, the Codeception fails are from Travis being, well, Travis, and hitting everything 3.3+ at the moment.

**Comment by bobdenotter** [comment]
Cool, merging in then!

**Pull request merged**
