### PR TITLE
Database contraints

### LINKED ISSUE #5165: [BUG] Not null constraint failed
Trying to move my old Bolt 2.2 database to Bolt 3.0 beta 2. It works, but once I try to add a new entry it breaks with the following error:

"An exception occurred while executing 'INSERT INTO bolt_entries (slug, datecreated, datechanged, datepublish, datedepublish, username, ownerid, status, templatefields, title, teaser, image, video) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["test-1", "2016-04-12 20:22:40", "2016-04-12 20:22:40", "2016-04-12 20:22:30", null, "", "1", "published", null, "test", "<p>test<\/p>\r\n", "[]", "[]"]:\n
\n
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: bolt_entries.templatefields"

It is possible to make a new page, block or something else. But not new entries. It is still possible to edit old entries.

In the old database the Schema is "CLOB NOT NULL DEFAULT". In the new database it is "CLOB DEFAULT NULL". Somehow I think this is a clue to the problem.

Details
-------

 - Relevant Bolt Version: [3.0 beta 2]
 - Install type: [ Zip/tarball install]
 - PHP version: [ 5.59 ]
 - Used webserver: [ Apache ]
 - For UX/UI issues: [ browser name and version ]

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #5165

### CODE REVIEW

**Comment by bobdenotter** [comment]
👍

**Comment by bobdenotter** [comment]
It seems that this change introduced a bunch of warnings on my setup: 

screenshot 2016-04-18 20 08 18

**Comment by GawainLynch** [comment]
I don't suppose there is a trace in there somewhere?

**Comment by bobdenotter** [comment]
It chokes on `debug_print_backtrace()`. Does this help? 

```
array:20 [▼
  0 => array:7 [▼
    "file" => "/Users/bob/Sites/bolt-origin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php"
    "line" => 450
    "function" => "getDefaultValueDeclarationSQL"
    "class" => "Doctrine\DBAL\Platforms\AbstractPlatform"
    "object" => MySqlPlatform {#1097 ▶}
    "type" => "->"
    "args" => array:1 [▼
      0 => array:12 [▼
        "name" => "value_json_array"
        "type" => JsonArrayType {#1100}
        "default" => []
        "notnull" => true
        "length" => null
        "precision" => 10
        "scale" => 0
        "fixed" => false
        "unsigned" => false
        "autoincrement" => false
        "columnDefinition" => null
        "comment" => "(DC2Type:json_array)"
      ]
    ]
  ]
  1 => array:7 [▼
    "file" => "/Users/bob/Sites/bolt-origin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php"
    "line" => 2193
    "function" => "getDefaultValueDeclarationSQL"
    "class" => "Doctrine\DBAL\Platforms\MySqlPlatform"
    "object" => MySqlPlatform {#1097 ▶}
    "type" => "->"
    "args" => array:1 [▼
      0 => array:12 [▼
        "name" => "value_json_array"
        "type" => JsonArrayType {#1100}
        "default" => []
        "notnull" => true
        "length" => null
        "precision" => 10
        "scale" => 0
        "fixed" => false
        "unsigned" => false
        "autoincrement" => false
        "columnDefinition" => null
        "comment" => "(DC2Type:json_array)"
      ]
    ]
  ]
  2 => array:7 [▼
    "file" => "/Users/bob/Sites/bolt-origin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php"
    "line" => 571
    "function" => "getColumnDeclarationSQL"
    "class" => "Doctrine\DBAL\Platforms\AbstractPlatform"
    "object" => MySqlPlatform {#1097 ▶}
    "type" => "->"
    "args" => array:2 [▼
      0 => "value_json_array"
      1 => array:12 [▼
        "name" => "value_json_array"
        "type" => JsonArrayType {#1100}
        "default" => []
        "notnull" => true
        "length" => null
        "precision" => 10
        "scale" => 0
        "fixed" => false
        "unsigned" => false
        "autoincrement" => false
        "columnDefinition" => null
        "comment" => "(DC2Type:json_array)"
      ]
    ]
  ]
  3 => array:7 [▼
    "file" => "/Users/bob/Sites/bolt-origin/src/Storage/Database/Schema/Comparison/BaseComparator.php"
    "line" => 269
    "function" => "getAlterTableSQL"
    "class" => "Doctrine\DBAL\Platforms\MySqlPlatform"
    "object" => MySqlPlatform {#1097 ▶}
    "type" => "->"
    "args" => array:1 [▼
      0 => TableDiff {#1705 ▼
        +name: "bolt_field_value"
        +newName: false
        +addedColumns: []
        +changedColumns: array:1 [▶]
        +removedColumns: []
        +renamedColumns: []
        +addedIndexes: []
        +changedIndexes: []
        +removedIndexes: []
        +renamedIndexes: []
        +addedForeignKeys: []
        +changedForeignKeys: []
        +removedForeignKeys: []
        +fromTable: Table {#1999 ▶}
      }
    ]
  ]
  4 => array:7 [▼
    "file" => "/Users/bob/Sites/bolt-origin/src/Storage/Database/Schema/Comparison/BaseComparator.php"
    "line" => 95
    "function" => "addAlterResponses"
    "class" => "Bolt\Storage\Database\Schema\Comparison\BaseComparator"
    "object" => MySql {#1434 ▶}
    "type" => "->"
    "args" => []
  ]
  5 => array:7 [▼
    "file" => "/Users/bob/Sites/bolt-origin/src/Storage/Database/Schema/Comparison/BaseComparator.php"
    "line" => 69
    "function" => "compare"
    "class" => "Bolt\Storage\Database\Schema\Comparison\BaseComparator"
    "object" => MySql {#1434 ▶}
    "type" => "->"
    "args" => array:3 [▼
      0 => array:13 [▼
        "authtoken" => Table {#1911 ▶}
        "blocks" => Table {#1940 ▶}
        "cron" => Table {#1948 ▶}
        "entries" => Table {#1978 ▶}
        "field_value" => Table {#1999 ▶}
        "log_change" => Table {#2021 ▶}
        "log_system" => Table {#2042 ▶}
        "pages" => Table {#2072 ▶}
        "relations" => Table {#2088 ▶}
        "showcases" => Table {#2136 ▶}
        "taxonomy" => Table {#2154 ▶}
        "users" => Table {#2178 ▶}
        "wishlist" => Table {#2206 ▶}
      ]
      1 => array:12 [▼
        "authtoken" => Table {#2209 ▶}
        "cron" => Table {#2222 ▶}
        "field_value" => Table {#2230 ▶}
        "log_change" => Table {#2251 ▶}
        "log_system" => Table {#2273 ▶}
        "relations" => Table {#2294 ▶}
        "taxonomy" => Table {#2310 ▶}
        "users" => Table {#2328 ▶}
        "pages" => Table {#2352 ▶}
        "entries" => Table {#2382 ▶}
        "showcases" => Table {#2412 ▶}
        "blocks" => Table {#2458 ▶}
      ]
      2 => array:4 [▼
        0 => "pages"
        1 => "entries"
        2 => "showcases"
        3 => "blocks"
      ]
    ]
  ]
```

**Comment by GawainLynch** [comment]
Oh, this just goes from strange to weird…

Line 2251 is `if (isset($field['type'])) {` but the above dumps are showing an object:
```
 "type" => JsonArrayType
```

**Comment by bobdenotter** [comment]
The error occurs on line 2250, just before that: 

    $default = " DEFAULT '".$field['default']."'";

In this case, `$field['default']` is `[]`.

**Comment by GawainLynch** [comment]
image

**Pull request merged**
