### PR TITLE
added support for taxonomy default in contenttypes.yml

### PR DESCRIPTION
**Pull request by Johardmeier**
with this line in the content constructor we have the option to add a default to the contenttypes.yml.
usage: 
   taxonomy: [mycategories]
   default_mycategories: "category2"

### CODE REVIEW

**Comment by Johardmeier** [comment]
@GawainLynch you closed the pull request after committing @bobdenotter s layout fixes. I am pretty sure they have nothing to do with my PR - I don't know why those two are attached.
But I probably did many things wrong with my PR - if thats the cause why you deleted it: do you mind to give me a hint?
Thank you so much

**Comment by Johardmeier** [comment]
Am 23.07.2015 um 17:11 schrieb Gawain Lynch:
>
> Reopened #3858 <https://github.com/bolt/bolt/pull/3858>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bolt/bolt/pull/3858#event-363505474>.
>
Thank you

**Comment by GawainLynch** [comment]
Ah, pretty simple… Someone who shall remain nameless reference this PR with "Fixes # 3858" in their PR and that make GitHub auto-close it… reopened with our apologies… :grin:

**Comment by CarsonF** [comment]
@Johardmeier Wouldn't this be better defined in `taxonomies.yml`?

**Comment by Johardmeier** [comment]
@CarsonF The Idea is to be able to have different contenttypes with different taxonomy defaults.

**Comment by bobdenotter** [comment]
@Johardmeier Oops, that was my who referenced the wrong issue in the PR! My apologies!

**Comment by bobdenotter** [comment]
Your example describes `default_mycategories`. Shouldn't it be:

```
// add support for taxonomy default per contenttype
if (isset($this->contenttype['default'.$taxonomytype])){
  $defaultValue = $this->contenttype['default'.$taxonomytype];
}
```

**Comment by Johardmeier** [comment]
1st of all: bolt is awesome. Thank you for it. (should have said that right in the beginning...)
2nd:
Knnawwwww. You are of course right. I should test even the smallest changes, shouldn't I ? I'm sorry.
(Actually, I had "cats" and  "defaultcats" in my tests and later changed it to the underscored version).
Still hope this finds your approval.

**Comment by bobdenotter** [comment]
Hi @Johardmeier,

First off, my apologies that we left this linger for a while. I finally got around to testing it a bit more, and spotted two issues: 

 - It doesn't seem to work with tags just yet.
 - It also doesn't work with multiple values. 

Take this example: 

```
    taxonomy: [ categories, tags ]
    default_categories: [ news, music ]
    default_tags: radio
```

Now, when I create a new entry, there should be two categories selected by default, as well as a tag. 

Could you look into this? :-)

**Comment by bobdenotter** [comment]
*bump* :-)

**Comment by Johardmeier** [comment]
Hi bob,
sorry for not answering. I just stumbled upon this after some time ;)
After not hearing anything about this I moved on to another project and didn't use bolt since. So in addition to probably not beeing the astute programmer that is needed to finish here I lack the time to immerse myself back into bolt. Sorry. - So please consider this obsolete.
I wish bolt all the best and will probably come back at alater time.

**Pull request closed without merging**
