### PR TITLE
Adding check for issue 3491 (password must be different from username)

### PR DESCRIPTION
**Pull request by pygillier**
A better PR this time for #3491

### CODE REVIEW

**Comment by GawainLynch** [comment]
Très bien, merci :+1:

**Comment by pygillier** [comment]
Mhh, forgot some checks.

**Comment by GawainLynch** [comment]
Just as a heads up for further PRs to save you some trouble. Once you have opened a *branch* PR, anything you add *in that branch and push* will be valid until the PR is merged. If it comes after merge, you can just open a new PR with the additional commits. Powerful, confusing, but a thing of beauty is git :grin:

**Comment by pygillier** [comment]
Ahah, I now understand how powerful is git. 

So, and accept my apologizes for the mess, I'm reopening.

**Comment by GawainLynch** [comment]
Apologies not needed… contributions welcome :+1:

**Comment by bobdenotter** [comment]
Seems like Travis is failing. 

```
There was 1 error:
1) Bolt\Tests\Controller\BackendTest::testProfile
Symfony\Component\Form\Exception\OutOfBoundsException: Child "username" does not exist.
```

https://travis-ci.org/bolt/bolt/jobs/61442176#L3486

**Comment by pygillier** [comment]
Travis is failing on a test which seems to be completely unrelated to my changes (editContent) @GawainLynch & @bobdenotter any ideas ?

**Comment by rossriley** [comment]
I think the failure is due to an edge case that this test covers but it is, i think, one that should be tested for. It's possible to update the profile without posting a username or password update in which case both the username and password would be equal to `''`

**Comment by bobdenotter** [comment]
Green lights!! All aboard the merge train! :steam_locomotive:  :train: :train: :train: :train:

**Pull request merged**
