### PR TITLE
Possible Fix for #2513

### PR DESCRIPTION
**Pull request by cdowdy**
This is a possible fix for Contenttypes with very long names (#2513). It will truncate the name and use ellipsis to keep the text inside the side bar nav   

__desktop__
ellipses_mixin  

__mobile__
mobile_ellispses_mixin

### CODE REVIEW

**Comment by bobdenotter** [comment]
Looks good to me! Have you tried it on IE as well?

**Comment by cdowdy** [comment]
welp... works in everyting besides ie9 :-(   

ie8  
ie8_bolt  

ie 9  
ie9_bolt  
as soon as font-awesome loads you get the unicode character box  
ie9_bolt_animate  

ie10  
ie10_bolt  

There are bug filed on font-awesome [bug](https://github.com/FortAwesome/Font-Awesome/issues/1079) I've tried the work around I'll tinker some more today see if I can get ie9 to play nice

**Comment by bobdenotter** [comment]
Actually, this would be acceptably to me. IE 8 and IE 10+ are the only ones that have significant share. Most users on IE 9 are auto-upgraded to IE 11 by now, while IE 8 was the latest version before auto-updating.

**Comment by cdowdy** [comment]
Alright! I feel the same way so that works out haha

**Comment by bobdenotter** [comment]
Merging in!

**Pull request merged**
