### PR TITLE
[3.1] Nut user handling

### LINKED ISSUE #5482: User not enabled by default when created with Nut.
When creating a new user with Nut, the user is not enabled, and there is no command to enable a user.

(I can create a PR for this if needed).

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes #5482

### CODE REVIEW

**Comment by SahAssar** [comment]
Tagging that this needs to be included in the docs too :)

**Comment by GawainLynch** [comment]
…and also :koala: didn't write tests for it!

**Comment by GawainLynch** [comment]
@SahAssar Unit tests added and a tiny PR against docs to add to the existing list.

Writing up docs for individual commands should be taken care of at some point, and is low hanging pineapple territory, but I think it is out of scope for this PR.

**Comment by SahAssar** [comment]
Whoop!

**Pull request merged**
