### PR TITLE
XSS and missing close tag issue fixed. Issues 3590 and 3591

### LINKED ISSUE #3590: Application breaks when not closing tags on title.
Hi guys, 

I've been playing with Bolt for a project and I noted that when creating a new Page, Entry or Showcase, the dashboard and the site breaks if the title has an opening hmtl tag such as `<script>` but it is not closed and there is no possibility to delete that Page/Entry/Showcase unless I delete directly from the DB.
bug-dashboard

### LINKED ISSUE #3591: Possible XSS attack
Hi team,

I mounted a server locally and start using bolt. I noticed that any tag can be used in the title bar for Entries/Pages/Showcases. I was able to perform basic XSS attacks, I would like to mention that the attack is possible if the attacker gains access to the bolt admin dashboard and creates a new Entry/Page/Showcase and paste the code in the title bar.

A basic example is putting `<script>alert('XSS');</script> Hello!` in the title bar. This attack is simple and obvious for the admin and everyone visiting the full site, but a carefully crafted attack can be unnoticed for some time.

cookie-stealing-page

### PR DESCRIPTION
**Pull request by Pereida**
Fixes #3590 
Fixed #3591 

Changelog
--------------

* Fixed: Bug that breaks the dashboard and full site if a tag is open but not closed in the title bar. Also prevents possible XSS injection and use of tags in title bar.

### CODE REVIEW

**Comment by CarsonF** [comment]
This should probably be done in Twig

**Comment by GawainLynch** [comment]
> This should probably be done in Twig

…and breaks BC

**Comment by bobdenotter** [comment]
I often do stuff like this: 

    This is a <em>nice</em> title. 

Your PR breaks that, unfortunately.

**Comment by GDmac** [comment]
yes, agree with carson that the twig templates could do with 
an escape in the html ``<title>`` element

**Comment by SahAssar** [comment]
Does #4168 fix this is satisfactory ways for everyone?

**Comment by SahAssar** [comment]
Fixed via #4168, closing this.

**Pull request closed without merging**
