### PR TITLE
[WIP] Smoothen UI for templatefields toggle.

### PR DESCRIPTION
**Pull request by bobdenotter**
This is a tentative fix for #4223.

If the templatefields are filled when resetting it, it shows the warning as usual.. Short video:

http://recordit.co/LtHrCTAnKr

If the fields are cleared, it will hide the "template" tab silently, and it doesn't show the message. Short video:

http://recordit.co/shIEW9vR12

This "fix" is done vary hackishly. Especially this part is flawed, and needs input from @rarila to do properly:

```
$('input[name^="templatefields"]').each(function(){
    if ($(this).val() !== '') {
        templatefieldsEmpty = false;
    }
});
```

### CODE REVIEW

**Comment by GawainLynch** [comment]
Functionally… LGTM

**Comment by bobdenotter** [comment]
*bumping @rarila *

**Comment by rarila** [comment]
From watching the video it solves the issues' issue but the bigger UIX problem (save-refresh) persists.

Technically one could fiddle with a few things, e.g . ``$('#tabindicator-tab-template')`` could be done like ``$('[href="\\#tab-template"]').closest('li')`` or ``$('[href="\\#tab-template"]').parent()`` to save some ids.

Looking at the "hackishly" part… At least it misses select fields, so probably just ``$('[name^="templatefields"]')`` will do the trick. Then selects could return ``object`` for ``$(this).val()``… I guess we can catch this with just ``if ($(this).val()) {`` – To be tested what happens if there's a zero in a textfield and if that's casted to ``number``  ``0`` then … WAT?!
Then there are not only selects, there also checkboxes … And it will break on fields with default values set … Much things to take into account, so:

A much cleaner aproach would be probably to add a ``hasChanged()`` or ``changed()`` method to our fields, taking advantage of the fact that they are now instances. Adding those like ``empty()``, ``changed()`` and ``validates()`` was on my list anyway. One of the nice things widgeted fields brings us. :smile:

**Comment by bobdenotter** [comment]
I made some tweaks, and it's working OK now. There's room for improvement, but it's currently better than it was, and it will likely be redone in the future. So, for now I declare this "Good enough,  ¯\_(ツ)_/¯".

**Comment by GawainLynch** [comment]
OK… let's go for go-go-mobile!

**Pull request merged**
