### PR TITLE
Only regex match from beginning of multi-line

### PR DESCRIPTION
**Pull request by GawainLynch**
More than a slight performance gain on this one :-/

### CODE REVIEW

**Comment by bobdenotter** [comment]
Yay, teamwork! \o/

**Comment by bobdenotter** [comment]
Whoop! merging in!

**Comment by SahAssar** [comment]
I think that this was intentional... See #4368

**Comment by GawainLynch** [comment]
With 2 added JS files, it will raise backend load times from ~200ms to ~16000ms :-/

**Comment by SahAssar** [comment]
o_0

Alright, that's a bit more than I expected...

**Pull request merged**
