### PR TITLE
Make base 2016 default

### PR DESCRIPTION
**Pull request by SahAssar**
I'm proposing making base-2016 the default (as discussed on IRC this morning/lunchtime) now so that we actually find any rough edges before we get into beta/RC. This PR also includes all the necessary test changes (I hope).

### CODE REVIEW

**Comment by GawainLynch** [comment]
:+1:

**Comment by PhillippOhlandt** [comment]
:+1:

**Comment by bobdenotter** [comment]
What's Travis' problem with this?

**Comment by GawainLynch** [comment]
That the Composer install is partially "faked" and *some* things are rsync'ed but not themes. They are safe to ignore in this case.

**Comment by bobdenotter** [comment]
Allright. Let's go then! :+1:

**Pull request merged**
